// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package notificationstore

import (
	"context"
)

const ping = `-- name: Ping :one

SELECT 1::int AS ok
`

// Placeholder so sqlc has something to generate against. sqlc.yaml already
// declared this directory before Phase 2 existed, but nothing had created
// it yet — discovered while closing 2.0's lending/checkout query-directory
// gap, which needs `sqlc generate` to succeed cleanly across every entry in
// sqlc.yaml, not just the two this sub-phase otherwise owns. Notification
// itself is Phase 6 scope.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
