// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notificationstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	FindOverdueCandidateLoans(ctx context.Context, dueAt pgtype.Timestamptz) ([]FindOverdueCandidateLoansRow, error)
	GetDelivery(ctx context.Context, id pgtype.UUID) (DeliveryLog, error)
	GetDeliveryByDedupeKey(ctx context.Context, dedupeKey string) (DeliveryLog, error)
	GetLoanForNotification(ctx context.Context, id pgtype.UUID) (GetLoanForNotificationRow, error)
	GetPreferences(ctx context.Context, userID pgtype.UUID) (NotificationPreference, error)
	HasOverdueEscalation(ctx context.Context, arg HasOverdueEscalationParams) (bool, error)
	// Queries for the notification module (delivery_log, preferences, overdue_escalations)
	InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (DeliveryLog, error)
	ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]DeliveryLog, error)
	ListPendingDeliveries(ctx context.Context, arg ListPendingDeliveriesParams) ([]DeliveryLog, error)
	ListQuarantinedDeliveries(ctx context.Context) ([]DeliveryLog, error)
	RecordOverdueEscalation(ctx context.Context, arg RecordOverdueEscalationParams) (OverdueEscalation, error)
	UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) (DeliveryLog, error)
	UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) (NotificationPreference, error)
}

var _ Querier = (*Queries)(nil)
