// Package listing provides shared list contract parsing, validation, column whitelisting,
// and keyset cursor encoding/decoding for HDMS list endpoints.
package listing

import (
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
)

// CurrentCursorVersion is the version byte expected in keyset cursors.
// Cursors generated by older/incompatible versions or tampered payloads are rejected cleanly.
const CurrentCursorVersion byte = 1

// Default limits.
const (
	DefaultLimit = 50
	MaxLimit     = 200
	MinLimit     = 1
)

var (
	ErrInvalidCursor = errors.New("invalid or malformed pagination cursor")
	ErrStaleCursor   = errors.New("stale pagination cursor version")
	ErrInvalidSort   = errors.New("unknown sort column")
	ErrInvalidOrder  = errors.New("invalid sort order: must be 'asc' or 'desc'")
	ErrInvalidLimit  = errors.New("limit must be an integer between 1 and 200")
	ErrUnknownFilter = errors.New("unknown filter parameter")
)

// Order specifies the sort direction.
type Order string

const (
	OrderAsc  Order = "asc"
	OrderDesc Order = "desc"
)

// Cursor payload structure.
type cursorPayload struct {
	K string `json:"k"` // sort column key
	V string `json:"v"` // sort column value string
	I string `json:"i"` // tiebreaker entity ID (UUID / string)
}

// Cursor is the decoded pagination cursor.
type Cursor struct {
	Version byte
	SortKey string
	SortVal string
	ID      string
}

// TimeVal parses the cursor's sort value as an RFC3339 / RFC3339Nano timestamp.
func (c *Cursor) TimeVal() (*time.Time, error) {
	if c == nil || c.SortVal == "" {
		return nil, nil
	}
	t, err := time.Parse(time.RFC3339Nano, c.SortVal)
	if err != nil {
		t, err = time.Parse(time.RFC3339, c.SortVal)
		if err != nil {
			return nil, fmt.Errorf("invalid cursor timestamp %q: %w", c.SortVal, err)
		}
	}
	return &t, nil
}

// UUIDVal parses the cursor ID as a UUID.
func (c *Cursor) UUIDVal() (*uuid.UUID, error) {
	if c == nil || c.ID == "" {
		return nil, nil
	}
	u, err := uuid.Parse(c.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid cursor id %q: %w", c.ID, err)
	}
	return &u, nil
}

// EncodeCursor encodes a sort key, sort value string, and tiebreaker ID with the specified version byte.
func EncodeCursor(version byte, sortKey, sortVal, id string) string {
	payload := cursorPayload{
		K: sortKey,
		V: sortVal,
		I: id,
	}
	jsonBytes, err := json.Marshal(payload)
	if err != nil {
		return ""
	}
	buf := make([]byte, 1+len(jsonBytes))
	buf[0] = version
	copy(buf[1:], jsonBytes)
	return base64.RawURLEncoding.EncodeToString(buf)
}

// EncodeTimeCursor encodes a timestamp sort value and tiebreaker ID.
func EncodeTimeCursor(sortKey string, t time.Time, id string) string {
	return EncodeCursor(CurrentCursorVersion, sortKey, t.UTC().Format(time.RFC3339Nano), id)
}

// EncodeStringCursor encodes a string sort value and tiebreaker ID.
func EncodeStringCursor(sortKey string, val string, id string) string {
	return EncodeCursor(CurrentCursorVersion, sortKey, val, id)
}

// DecodeCursor decodes and validates a raw base64 cursor.
// If expectedSortKey is non-empty, the cursor's encoded sort key must match.
func DecodeCursor(raw string, expectedSortKey string) (*Cursor, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return nil, nil
	}

	// Support RawURLEncoding, URLEncoding, and StdEncoding.
	var data []byte
	var err error
	data, err = base64.RawURLEncoding.DecodeString(raw)
	if err != nil {
		data, err = base64.URLEncoding.DecodeString(raw)
		if err != nil {
			data, err = base64.StdEncoding.DecodeString(raw)
			if err != nil {
				return nil, fmt.Errorf("%w: base64 decode failed", ErrInvalidCursor)
			}
		}
	}

	if len(data) < 2 {
		return nil, fmt.Errorf("%w: payload too short", ErrInvalidCursor)
	}

	version := data[0]
	if version != CurrentCursorVersion {
		return nil, fmt.Errorf("%w: expected %d, got %d", ErrStaleCursor, CurrentCursorVersion, version)
	}

	var payload cursorPayload
	if err := json.Unmarshal(data[1:], &payload); err != nil {
		return nil, fmt.Errorf("%w: json decode failed", ErrInvalidCursor)
	}

	if strings.TrimSpace(payload.I) == "" {
		return nil, fmt.Errorf("%w: missing id tiebreaker", ErrInvalidCursor)
	}

	if expectedSortKey != "" && payload.K != "" && payload.K != expectedSortKey {
		return nil, fmt.Errorf("%w: cursor sort key %q does not match expected %q", ErrInvalidCursor, payload.K, expectedSortKey)
	}

	return &Cursor{
		Version: version,
		SortKey: payload.K,
		SortVal: payload.V,
		ID:      payload.I,
	}, nil
}

// ResourceSpec declares the sorting and filtering contract for a given resource.
type ResourceSpec struct {
	Name           string
	SortColumns    map[string]bool
	DefaultSort    string
	DefaultOrder   Order
	AllowedFilters map[string]bool
	DefaultLimit   int
	MaxLimit       int
	StrictFilters  bool
}

// Params contains validated listing parameters.
type Params struct {
	Limit      int
	RawCursor  string
	Cursor     *Cursor
	Sort       string
	Order      Order
	Filters    map[string]string
	FilterList map[string][]string
}

// Filter returns the first filter value for key, or empty string.
func (p *Params) Filter(key string) string {
	if p == nil || p.Filters == nil {
		return ""
	}
	return p.Filters[key]
}

// HasFilter returns true if key exists in filters.
func (p *Params) HasFilter(key string) bool {
	if p == nil || p.Filters == nil {
		return false
	}
	_, ok := p.Filters[key]
	return ok
}

// BoolFilter parses a filter value as boolean.
func (p *Params) BoolFilter(key string) (*bool, error) {
	val := p.Filter(key)
	if val == "" {
		return nil, nil
	}
	b, err := strconv.ParseBool(val)
	if err != nil {
		return nil, fmt.Errorf("filter %q must be a boolean (true/false): %w", key, err)
	}
	return &b, nil
}

// TimeFilter parses a filter value as an RFC3339 timestamp.
func (p *Params) TimeFilter(key string) (*time.Time, error) {
	val := p.Filter(key)
	if val == "" {
		return nil, nil
	}
	t, err := time.Parse(time.RFC3339Nano, val)
	if err != nil {
		t, err = time.Parse(time.RFC3339, val)
		if err != nil {
			return nil, fmt.Errorf("filter %q must be an RFC3339 timestamp: %w", key, err)
		}
	}
	return &t, nil
}

// Parse extracts and validates listing parameters from an HTTP request using the resource spec.
func Parse(r *http.Request, spec ResourceSpec) (*Params, error) {
	query := r.URL.Query()

	// 1. Limit
	defaultLimit := spec.DefaultLimit
	if defaultLimit <= 0 {
		defaultLimit = DefaultLimit
	}
	maxLimit := spec.MaxLimit
	if maxLimit <= 0 {
		maxLimit = MaxLimit
	}

	limit := defaultLimit
	if limitStr := strings.TrimSpace(query.Get("limit")); limitStr != "" {
		parsedLimit, err := strconv.Atoi(limitStr)
		if err != nil || parsedLimit < MinLimit || parsedLimit > maxLimit {
			return nil, fmt.Errorf("%w: got %q (allowed %d-%d)", ErrInvalidLimit, limitStr, MinLimit, maxLimit)
		}
		limit = parsedLimit
	}

	// 2. Sort
	sortCol := strings.TrimSpace(query.Get("sort"))
	if sortCol == "" {
		sortCol = spec.DefaultSort
	} else if spec.SortColumns != nil && !spec.SortColumns[sortCol] {
		return nil, fmt.Errorf("%w: %q", ErrInvalidSort, sortCol)
	}

	// 3. Order
	orderStr := strings.ToLower(strings.TrimSpace(query.Get("order")))
	var order Order
	switch orderStr {
	case "":
		if spec.DefaultOrder != "" {
			order = spec.DefaultOrder
		} else {
			order = OrderDesc
		}
	case "asc":
		order = OrderAsc
	case "desc":
		order = OrderDesc
	default:
		return nil, fmt.Errorf("%w: %q", ErrInvalidOrder, orderStr)
	}

	// 4. Cursor
	rawCursor := strings.TrimSpace(query.Get("cursor"))
	var decodedCursor *Cursor
	if rawCursor != "" {
		var err error
		decodedCursor, err = DecodeCursor(rawCursor, sortCol)
		if err != nil {
			return nil, err
		}
	}

	// 5. Filters
	filters := make(map[string]string)
	filterList := make(map[string][]string)

	standardKeys := map[string]bool{
		"limit":  true,
		"cursor": true,
		"sort":   true,
		"order":  true,
	}

	for k, vals := range query {
		if standardKeys[k] {
			continue
		}
		if spec.StrictFilters && spec.AllowedFilters != nil && !spec.AllowedFilters[k] {
			return nil, fmt.Errorf("%w: %q", ErrUnknownFilter, k)
		}
		if len(vals) > 0 {
			filters[k] = vals[0]
			filterList[k] = vals
		}
	}

	return &Params{
		Limit:      limit,
		RawCursor:  rawCursor,
		Cursor:     decodedCursor,
		Sort:       sortCol,
		Order:      order,
		Filters:    filters,
		FilterList: filterList,
	}, nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Standard Resource Specifications
// ─────────────────────────────────────────────────────────────────────────────

var (
	// DevicesSpec defines the listing contract for /v1/devices.
	DevicesSpec = ResourceSpec{
		Name: "devices",
		SortColumns: map[string]bool{
			"created_at": true,
			"asset_tag":  true,
			"name":       true,
			"status":     true,
			"updated_at": true,
		},
		DefaultSort:  "created_at",
		DefaultOrder: OrderDesc,
		AllowedFilters: map[string]bool{
			"status":      true,
			"category":    true,
			"categoryId":  true,
			"category_id": true,
			"q":           true,
		},
		DefaultLimit:  DefaultLimit,
		MaxLimit:      MaxLimit,
		StrictFilters: true,
	}

	// UsersSpec defines the listing contract for /v1/users.
	UsersSpec = ResourceSpec{
		Name: "users",
		SortColumns: map[string]bool{
			"registered_at": true,
			"full_name":     true,
			"employee_no":   true,
			"status":        true,
			"updated_at":    true,
		},
		DefaultSort:  "registered_at",
		DefaultOrder: OrderDesc,
		AllowedFilters: map[string]bool{
			"status":         true,
			"department":     true,
			"departmentId":   true,
			"department_id":  true,
			"hasCredential":  true,
			"has_credential": true,
			"q":              true,
		},
		DefaultLimit:  DefaultLimit,
		MaxLimit:      MaxLimit,
		StrictFilters: true,
	}

	// LoansSpec defines the listing contract for /v1/loans.
	LoansSpec = ResourceSpec{
		Name: "loans",
		SortColumns: map[string]bool{
			"borrowed_at": true,
			"due_at":      true,
			"returned_at": true,
			"status":      true,
			"created_at":  true,
		},
		DefaultSort:  "borrowed_at",
		DefaultOrder: OrderDesc,
		AllowedFilters: map[string]bool{
			"status":    true,
			"origin":    true,
			"userId":    true,
			"user_id":   true,
			"deviceId":  true,
			"device_id": true,
			"from":      true,
			"to":        true,
			"disputed":  true,
		},
		DefaultLimit:  DefaultLimit,
		MaxLimit:      MaxLimit,
		StrictFilters: true,
	}

	// AuditSpec defines the listing contract for /v1/audit.
	AuditSpec = ResourceSpec{
		Name: "audit",
		SortColumns: map[string]bool{
			"at":          true,
			"occurred_at": true,
		},
		DefaultSort:  "at",
		DefaultOrder: OrderDesc,
		AllowedFilters: map[string]bool{
			"actor":   true,
			"action":  true,
			"subject": true,
			"from":    true,
			"to":      true,
			"before":  true,
		},
		DefaultLimit:  DefaultLimit,
		MaxLimit:      MaxLimit,
		StrictFilters: true,
	}

	// CategoriesSpec defines the listing contract for /v1/categories.
	CategoriesSpec = ResourceSpec{
		Name: "categories",
		SortColumns: map[string]bool{
			"name":       true,
			"created_at": true,
		},
		DefaultSort:  "name",
		DefaultOrder: OrderAsc,
		AllowedFilters: map[string]bool{
			"q": true,
		},
		DefaultLimit:  DefaultLimit,
		MaxLimit:      MaxLimit,
		StrictFilters: true,
	}

	// AdminsSpec defines the listing contract for /v1/admins.
	AdminsSpec = ResourceSpec{
		Name: "admins",
		SortColumns: map[string]bool{
			"created_at": true,
			"email":      true,
			"full_name":  true,
			"role":       true,
			"status":     true,
		},
		DefaultSort:  "created_at",
		DefaultOrder: OrderDesc,
		AllowedFilters: map[string]bool{
			"role":   true,
			"status": true,
			"q":      true,
		},
		DefaultLimit:  DefaultLimit,
		MaxLimit:      MaxLimit,
		StrictFilters: true,
	}

	// KiosksSpec defines the listing contract for /v1/kiosks.
	KiosksSpec = ResourceSpec{
		Name: "kiosks",
		SortColumns: map[string]bool{
			"created_at":   true,
			"name":         true,
			"status":       true,
			"last_seen_at": true,
		},
		DefaultSort:  "created_at",
		DefaultOrder: OrderDesc,
		AllowedFilters: map[string]bool{
			"status": true,
			"q":      true,
		},
		DefaultLimit:  DefaultLimit,
		MaxLimit:      MaxLimit,
		StrictFilters: true,
	}

	// ReservationsSpec defines the listing contract for /v1/reservations.
	ReservationsSpec = ResourceSpec{
		Name: "reservations",
		SortColumns: map[string]bool{
			"start_at": true,
		},
		DefaultSort:  "start_at",
		DefaultOrder: OrderDesc,
		AllowedFilters: map[string]bool{
			"status":    true,
			"deviceId":  true,
			"device_id": true,
			"userId":    true,
			"user_id":   true,
		},
		StrictFilters: false,
		DefaultLimit:  DefaultLimit,
		MaxLimit:      MaxLimit,
	}
)
