// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backup.sql

package backupstore

import (
	"context"

	"github.com/google/uuid"
)

const createDestination = `-- name: CreateDestination :one
INSERT INTO backup_destinations (
    id, name, kind, target, provider, enabled, retention_versions, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, name, kind, target, provider, enabled, retention_versions,
          initialized_at, last_ok_at, last_error, created_at, updated_at, updated_by
`

type CreateDestinationParams struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	Kind              string    `json:"kind"`
	Target            string    `json:"target"`
	Provider          string    `json:"provider"`
	Enabled           bool      `json:"enabled"`
	RetentionVersions int32     `json:"retention_versions"`
	UpdatedBy         string    `json:"updated_by"`
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) (BackupDestination, error) {
	row := q.db.QueryRow(ctx, createDestination,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Target,
		arg.Provider,
		arg.Enabled,
		arg.RetentionVersions,
		arg.UpdatedBy,
	)
	var i BackupDestination
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Target,
		&i.Provider,
		&i.Enabled,
		&i.RetentionVersions,
		&i.InitializedAt,
		&i.LastOkAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteDestination = `-- name: DeleteDestination :exec
DELETE FROM backup_destinations WHERE id = $1
`

func (q *Queries) DeleteDestination(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDestination, id)
	return err
}

const getDestination = `-- name: GetDestination :one
SELECT id, name, kind, target, provider, enabled, retention_versions,
       initialized_at, last_ok_at, last_error, created_at, updated_at, updated_by
FROM backup_destinations
WHERE id = $1
`

func (q *Queries) GetDestination(ctx context.Context, id uuid.UUID) (BackupDestination, error) {
	row := q.db.QueryRow(ctx, getDestination, id)
	var i BackupDestination
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Target,
		&i.Provider,
		&i.Enabled,
		&i.RetentionVersions,
		&i.InitializedAt,
		&i.LastOkAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listDestinations = `-- name: ListDestinations :many
SELECT id, name, kind, target, provider, enabled, retention_versions,
       initialized_at, last_ok_at, last_error, created_at, updated_at, updated_by
FROM backup_destinations
ORDER BY name
`

func (q *Queries) ListDestinations(ctx context.Context) ([]BackupDestination, error) {
	rows, err := q.db.Query(ctx, listDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupDestination
	for rows.Next() {
		var i BackupDestination
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Target,
			&i.Provider,
			&i.Enabled,
			&i.RetentionVersions,
			&i.InitializedAt,
			&i.LastOkAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledDestinations = `-- name: ListEnabledDestinations :many
SELECT id, name, kind, target, provider, enabled, retention_versions,
       initialized_at, last_ok_at, last_error, created_at, updated_at, updated_by
FROM backup_destinations
WHERE enabled
ORDER BY name
`

func (q *Queries) ListEnabledDestinations(ctx context.Context) ([]BackupDestination, error) {
	rows, err := q.db.Query(ctx, listEnabledDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupDestination
	for rows.Next() {
		var i BackupDestination
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Target,
			&i.Provider,
			&i.Enabled,
			&i.RetentionVersions,
			&i.InitializedAt,
			&i.LastOkAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDestinationInitialized = `-- name: MarkDestinationInitialized :exec
UPDATE backup_destinations
SET initialized_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkDestinationInitialized(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDestinationInitialized, id)
	return err
}

const recordDestinationOutcome = `-- name: RecordDestinationOutcome :exec
UPDATE backup_destinations
SET last_ok_at = CASE WHEN $1::boolean THEN now() ELSE last_ok_at END,
    last_error = CASE WHEN $1::boolean THEN NULL ELSE $2::text END,
    updated_at = now()
WHERE id = $3
`

type RecordDestinationOutcomeParams struct {
	Ok        bool      `json:"ok"`
	ErrorText string    `json:"error_text"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) RecordDestinationOutcome(ctx context.Context, arg RecordDestinationOutcomeParams) error {
	_, err := q.db.Exec(ctx, recordDestinationOutcome, arg.Ok, arg.ErrorText, arg.ID)
	return err
}

const updateDestination = `-- name: UpdateDestination :one
UPDATE backup_destinations
SET name               = $1,
    enabled            = $2,
    retention_versions = $3,
    updated_at         = now(),
    updated_by         = $4
WHERE id = $5
RETURNING id, name, kind, target, provider, enabled, retention_versions,
          initialized_at, last_ok_at, last_error, created_at, updated_at, updated_by
`

type UpdateDestinationParams struct {
	Name              string    `json:"name"`
	Enabled           bool      `json:"enabled"`
	RetentionVersions int32     `json:"retention_versions"`
	UpdatedBy         string    `json:"updated_by"`
	ID                uuid.UUID `json:"id"`
}

func (q *Queries) UpdateDestination(ctx context.Context, arg UpdateDestinationParams) (BackupDestination, error) {
	row := q.db.QueryRow(ctx, updateDestination,
		arg.Name,
		arg.Enabled,
		arg.RetentionVersions,
		arg.UpdatedBy,
		arg.ID,
	)
	var i BackupDestination
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Target,
		&i.Provider,
		&i.Enabled,
		&i.RetentionVersions,
		&i.InitializedAt,
		&i.LastOkAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
