// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package backupstore

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDestination(ctx context.Context, arg CreateDestinationParams) (BackupDestination, error)
	DeleteDestination(ctx context.Context, id uuid.UUID) error
	GetDestination(ctx context.Context, id uuid.UUID) (BackupDestination, error)
	ListDestinations(ctx context.Context) ([]BackupDestination, error)
	ListEnabledDestinations(ctx context.Context) ([]BackupDestination, error)
	MarkDestinationInitialized(ctx context.Context, id uuid.UUID) error
	RecordDestinationOutcome(ctx context.Context, arg RecordDestinationOutcomeParams) error
	UpdateDestination(ctx context.Context, arg UpdateDestinationParams) (BackupDestination, error)
}

var _ Querier = (*Queries)(nil)
