// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmAdminPendingTotp = `-- name: ConfirmAdminPendingTotp :one
UPDATE admin_accounts
SET totp_secret_enc = totp_pending_secret_enc,
    totp_pending_secret_enc = NULL,
    must_reenrol_totp = false,
    updated_at = now()
WHERE id = $1 AND totp_pending_secret_enc IS NOT NULL
RETURNING id, email, full_name, role, status
`

type ConfirmAdminPendingTotpRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	FullName string      `json:"full_name"`
	Role     AdminRole   `json:"role"`
	Status   AdminStatus `json:"status"`
}

func (q *Queries) ConfirmAdminPendingTotp(ctx context.Context, id pgtype.UUID) (ConfirmAdminPendingTotpRow, error) {
	row := q.db.QueryRow(ctx, confirmAdminPendingTotp, id)
	var i ConfirmAdminPendingTotpRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const countUnusedRecoveryCodesByAdminID = `-- name: CountUnusedRecoveryCodesByAdminID :one
SELECT count(*) FROM admin_recovery_codes
WHERE admin_id = $1 AND used_at IS NULL
`

func (q *Queries) CountUnusedRecoveryCodesByAdminID(ctx context.Context, adminID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedRecoveryCodesByAdminID, adminID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminAccount = `-- name: CreateAdminAccount :one
INSERT INTO admin_accounts (id, email, full_name, password_hash, totp_secret_enc, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, full_name, password_hash, totp_secret_enc, role, status,
          failed_attempts, last_failure_at, locked_until, must_change_password, must_reenrol_totp,
          last_login_at, totp_pending_secret_enc, created_at, updated_at, locale
`

type CreateAdminAccountParams struct {
	ID            pgtype.UUID `json:"id"`
	Email         string      `json:"email"`
	FullName      string      `json:"full_name"`
	PasswordHash  string      `json:"password_hash"`
	TotpSecretEnc []byte      `json:"totp_secret_enc"`
	Role          AdminRole   `json:"role"`
}

type CreateAdminAccountRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Email                string             `json:"email"`
	FullName             string             `json:"full_name"`
	PasswordHash         string             `json:"password_hash"`
	TotpSecretEnc        []byte             `json:"totp_secret_enc"`
	Role                 AdminRole          `json:"role"`
	Status               AdminStatus        `json:"status"`
	FailedAttempts       int32              `json:"failed_attempts"`
	LastFailureAt        pgtype.Timestamptz `json:"last_failure_at"`
	LockedUntil          pgtype.Timestamptz `json:"locked_until"`
	MustChangePassword   bool               `json:"must_change_password"`
	MustReenrolTotp      bool               `json:"must_reenrol_totp"`
	LastLoginAt          pgtype.Timestamptz `json:"last_login_at"`
	TotpPendingSecretEnc []byte             `json:"totp_pending_secret_enc"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Locale               string             `json:"locale"`
}

func (q *Queries) CreateAdminAccount(ctx context.Context, arg CreateAdminAccountParams) (CreateAdminAccountRow, error) {
	row := q.db.QueryRow(ctx, createAdminAccount,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.TotpSecretEnc,
		arg.Role,
	)
	var i CreateAdminAccountRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.Role,
		&i.Status,
		&i.FailedAttempts,
		&i.LastFailureAt,
		&i.LockedUntil,
		&i.MustChangePassword,
		&i.MustReenrolTotp,
		&i.LastLoginAt,
		&i.TotpPendingSecretEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Locale,
	)
	return i, err
}

const createKiosk = `-- name: CreateKiosk :one
INSERT INTO kiosks (id, name, location, token_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, name, location, token_hash, enabled_sources, status, default_locale, last_seen_at, created_at
`

type CreateKioskParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Location  pgtype.Text `json:"location"`
	TokenHash []byte      `json:"token_hash"`
}

type CreateKioskRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Location       pgtype.Text        `json:"location"`
	TokenHash      []byte             `json:"token_hash"`
	EnabledSources []string           `json:"enabled_sources"`
	Status         KioskStatus        `json:"status"`
	DefaultLocale  string             `json:"default_locale"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateKiosk(ctx context.Context, arg CreateKioskParams) (CreateKioskRow, error) {
	row := q.db.QueryRow(ctx, createKiosk,
		arg.ID,
		arg.Name,
		arg.Location,
		arg.TokenHash,
	)
	var i CreateKioskRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.TokenHash,
		&i.EnabledSources,
		&i.Status,
		&i.DefaultLocale,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO admin_sessions (id, admin_id, session_token_hash, csrf_token, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, admin_id, session_token_hash, csrf_token, created_at, last_seen_at, expires_at
`

type CreateSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	AdminID          pgtype.UUID        `json:"admin_id"`
	SessionTokenHash []byte             `json:"session_token_hash"`
	CsrfToken        string             `json:"csrf_token"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.AdminID,
		arg.SessionTokenHash,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.SessionTokenHash,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteOtherSessionsByAdminID = `-- name: DeleteOtherSessionsByAdminID :exec
DELETE FROM admin_sessions WHERE admin_id = $1 AND session_token_hash != $2
`

type DeleteOtherSessionsByAdminIDParams struct {
	AdminID          pgtype.UUID `json:"admin_id"`
	SessionTokenHash []byte      `json:"session_token_hash"`
}

func (q *Queries) DeleteOtherSessionsByAdminID(ctx context.Context, arg DeleteOtherSessionsByAdminIDParams) error {
	_, err := q.db.Exec(ctx, deleteOtherSessionsByAdminID, arg.AdminID, arg.SessionTokenHash)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM admin_sessions WHERE session_token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, sessionTokenHash)
	return err
}

const deleteSessionsByAdminID = `-- name: DeleteSessionsByAdminID :exec
DELETE FROM admin_sessions WHERE admin_id = $1
`

func (q *Queries) DeleteSessionsByAdminID(ctx context.Context, adminID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsByAdminID, adminID)
	return err
}

const deleteUnusedRecoveryCodesByAdminID = `-- name: DeleteUnusedRecoveryCodesByAdminID :exec
DELETE FROM admin_recovery_codes
WHERE admin_id = $1 AND used_at IS NULL
`

func (q *Queries) DeleteUnusedRecoveryCodesByAdminID(ctx context.Context, adminID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnusedRecoveryCodesByAdminID, adminID)
	return err
}

const disableKiosk = `-- name: DisableKiosk :one
UPDATE kiosks
SET status = 'disabled'
WHERE id = $1
RETURNING id, name, location, enabled_sources, status, default_locale, last_seen_at, created_at
`

type DisableKioskRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Location       pgtype.Text        `json:"location"`
	EnabledSources []string           `json:"enabled_sources"`
	Status         KioskStatus        `json:"status"`
	DefaultLocale  string             `json:"default_locale"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) DisableKiosk(ctx context.Context, id pgtype.UUID) (DisableKioskRow, error) {
	row := q.db.QueryRow(ctx, disableKiosk, id)
	var i DisableKioskRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.EnabledSources,
		&i.Status,
		&i.DefaultLocale,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const enableKiosk = `-- name: EnableKiosk :one
UPDATE kiosks
SET status = 'active'
WHERE id = $1
RETURNING id, name, location, enabled_sources, status, default_locale, last_seen_at, created_at
`

type EnableKioskRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Location       pgtype.Text        `json:"location"`
	EnabledSources []string           `json:"enabled_sources"`
	Status         KioskStatus        `json:"status"`
	DefaultLocale  string             `json:"default_locale"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) EnableKiosk(ctx context.Context, id pgtype.UUID) (EnableKioskRow, error) {
	row := q.db.QueryRow(ctx, enableKiosk, id)
	var i EnableKioskRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.EnabledSources,
		&i.Status,
		&i.DefaultLocale,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminAccountByEmail = `-- name: GetAdminAccountByEmail :one
SELECT id, email, full_name, password_hash, totp_secret_enc, role, status,
       failed_attempts, last_failure_at, locked_until, must_change_password, must_reenrol_totp,
       last_login_at, totp_pending_secret_enc, created_at, updated_at, locale
FROM admin_accounts WHERE lower(email) = lower($1)
`

type GetAdminAccountByEmailRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Email                string             `json:"email"`
	FullName             string             `json:"full_name"`
	PasswordHash         string             `json:"password_hash"`
	TotpSecretEnc        []byte             `json:"totp_secret_enc"`
	Role                 AdminRole          `json:"role"`
	Status               AdminStatus        `json:"status"`
	FailedAttempts       int32              `json:"failed_attempts"`
	LastFailureAt        pgtype.Timestamptz `json:"last_failure_at"`
	LockedUntil          pgtype.Timestamptz `json:"locked_until"`
	MustChangePassword   bool               `json:"must_change_password"`
	MustReenrolTotp      bool               `json:"must_reenrol_totp"`
	LastLoginAt          pgtype.Timestamptz `json:"last_login_at"`
	TotpPendingSecretEnc []byte             `json:"totp_pending_secret_enc"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Locale               string             `json:"locale"`
}

// Only used at login, where a non-existent email must fail the same way a
// wrong password does (no user enumeration) — the caller compares errors,
// not this query's behaviour, to keep that response uniform.
func (q *Queries) GetAdminAccountByEmail(ctx context.Context, lower string) (GetAdminAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAdminAccountByEmail, lower)
	var i GetAdminAccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.Role,
		&i.Status,
		&i.FailedAttempts,
		&i.LastFailureAt,
		&i.LockedUntil,
		&i.MustChangePassword,
		&i.MustReenrolTotp,
		&i.LastLoginAt,
		&i.TotpPendingSecretEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Locale,
	)
	return i, err
}

const getAdminAccountByID = `-- name: GetAdminAccountByID :one
SELECT id, email, full_name, password_hash, totp_secret_enc, role, status,
       failed_attempts, last_failure_at, locked_until, must_change_password, must_reenrol_totp,
       last_login_at, totp_pending_secret_enc, created_at, updated_at, locale
FROM admin_accounts WHERE id = $1
`

type GetAdminAccountByIDRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Email                string             `json:"email"`
	FullName             string             `json:"full_name"`
	PasswordHash         string             `json:"password_hash"`
	TotpSecretEnc        []byte             `json:"totp_secret_enc"`
	Role                 AdminRole          `json:"role"`
	Status               AdminStatus        `json:"status"`
	FailedAttempts       int32              `json:"failed_attempts"`
	LastFailureAt        pgtype.Timestamptz `json:"last_failure_at"`
	LockedUntil          pgtype.Timestamptz `json:"locked_until"`
	MustChangePassword   bool               `json:"must_change_password"`
	MustReenrolTotp      bool               `json:"must_reenrol_totp"`
	LastLoginAt          pgtype.Timestamptz `json:"last_login_at"`
	TotpPendingSecretEnc []byte             `json:"totp_pending_secret_enc"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Locale               string             `json:"locale"`
}

func (q *Queries) GetAdminAccountByID(ctx context.Context, id pgtype.UUID) (GetAdminAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminAccountByID, id)
	var i GetAdminAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.Role,
		&i.Status,
		&i.FailedAttempts,
		&i.LastFailureAt,
		&i.LockedUntil,
		&i.MustChangePassword,
		&i.MustReenrolTotp,
		&i.LastLoginAt,
		&i.TotpPendingSecretEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Locale,
	)
	return i, err
}

const getKioskByID = `-- name: GetKioskByID :one
SELECT id, name, location, enabled_sources, status, default_locale, last_seen_at, created_at
FROM kiosks
WHERE id = $1
`

type GetKioskByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Location       pgtype.Text        `json:"location"`
	EnabledSources []string           `json:"enabled_sources"`
	Status         KioskStatus        `json:"status"`
	DefaultLocale  string             `json:"default_locale"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetKioskByID(ctx context.Context, id pgtype.UUID) (GetKioskByIDRow, error) {
	row := q.db.QueryRow(ctx, getKioskByID, id)
	var i GetKioskByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.EnabledSources,
		&i.Status,
		&i.DefaultLocale,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getKioskByPairingCodeHash = `-- name: GetKioskByPairingCodeHash :one
SELECT id, name, pairing_code_expires_at
FROM kiosks
WHERE pairing_code_hash = $1 AND status = 'active'
`

type GetKioskByPairingCodeHashRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	PairingCodeExpiresAt pgtype.Timestamptz `json:"pairing_code_expires_at"`
}

// Scoped to active kiosks so a disabled kiosk's stale pairing code (if any)
// cannot be redeemed.
func (q *Queries) GetKioskByPairingCodeHash(ctx context.Context, pairingCodeHash []byte) (GetKioskByPairingCodeHashRow, error) {
	row := q.db.QueryRow(ctx, getKioskByPairingCodeHash, pairingCodeHash)
	var i GetKioskByPairingCodeHashRow
	err := row.Scan(&i.ID, &i.Name, &i.PairingCodeExpiresAt)
	return i, err
}

const getKioskByTokenHash = `-- name: GetKioskByTokenHash :one
SELECT id, name, location, token_hash, enabled_sources, status, default_locale, last_seen_at, created_at
FROM kiosks WHERE token_hash = $1
`

type GetKioskByTokenHashRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Location       pgtype.Text        `json:"location"`
	TokenHash      []byte             `json:"token_hash"`
	EnabledSources []string           `json:"enabled_sources"`
	Status         KioskStatus        `json:"status"`
	DefaultLocale  string             `json:"default_locale"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetKioskByTokenHash(ctx context.Context, tokenHash []byte) (GetKioskByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getKioskByTokenHash, tokenHash)
	var i GetKioskByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.TokenHash,
		&i.EnabledSources,
		&i.Status,
		&i.DefaultLocale,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    s.id, s.admin_id, s.session_token_hash, s.csrf_token, s.created_at, s.last_seen_at, s.expires_at,
    a.email, a.full_name, a.role, a.status AS admin_status,
    a.must_change_password, a.must_reenrol_totp, a.locked_until, a.last_login_at, a.locale
FROM admin_sessions s
JOIN admin_accounts a ON a.id = s.admin_id
WHERE s.session_token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID                 pgtype.UUID        `json:"id"`
	AdminID            pgtype.UUID        `json:"admin_id"`
	SessionTokenHash   []byte             `json:"session_token_hash"`
	CsrfToken          string             `json:"csrf_token"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	Email              string             `json:"email"`
	FullName           string             `json:"full_name"`
	Role               AdminRole          `json:"role"`
	AdminStatus        AdminStatus        `json:"admin_status"`
	MustChangePassword bool               `json:"must_change_password"`
	MustReenrolTotp    bool               `json:"must_reenrol_totp"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	Locale             string             `json:"locale"`
}

// Joins the owning account so the middleware can reject a disabled account
// on every request without a second round trip.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, sessionTokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.SessionTokenHash,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.AdminStatus,
		&i.MustChangePassword,
		&i.MustReenrolTotp,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.Locale,
	)
	return i, err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO admin_recovery_codes (id, admin_id, code_hash)
VALUES ($1, $2, $3)
`

type InsertRecoveryCodeParams struct {
	ID       pgtype.UUID `json:"id"`
	AdminID  pgtype.UUID `json:"admin_id"`
	CodeHash string      `json:"code_hash"`
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode, arg.ID, arg.AdminID, arg.CodeHash)
	return err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, email, full_name, role, status, failed_attempts, last_failure_at, locked_until,
       must_change_password, must_reenrol_totp, last_login_at, created_at, updated_at, locale
FROM admin_accounts
ORDER BY created_at ASC
`

type ListAdminsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Email              string             `json:"email"`
	FullName           string             `json:"full_name"`
	Role               AdminRole          `json:"role"`
	Status             AdminStatus        `json:"status"`
	FailedAttempts     int32              `json:"failed_attempts"`
	LastFailureAt      pgtype.Timestamptz `json:"last_failure_at"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	MustChangePassword bool               `json:"must_change_password"`
	MustReenrolTotp    bool               `json:"must_reenrol_totp"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Locale             string             `json:"locale"`
}

func (q *Queries) ListAdmins(ctx context.Context) ([]ListAdminsRow, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminsRow
	for rows.Next() {
		var i ListAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.Status,
			&i.FailedAttempts,
			&i.LastFailureAt,
			&i.LockedUntil,
			&i.MustChangePassword,
			&i.MustReenrolTotp,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Locale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKiosks = `-- name: ListKiosks :many
SELECT id, name, location, enabled_sources, status, default_locale, last_seen_at, created_at
FROM kiosks
ORDER BY created_at ASC
`

type ListKiosksRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Location       pgtype.Text        `json:"location"`
	EnabledSources []string           `json:"enabled_sources"`
	Status         KioskStatus        `json:"status"`
	DefaultLocale  string             `json:"default_locale"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListKiosks(ctx context.Context) ([]ListKiosksRow, error) {
	rows, err := q.db.Query(ctx, listKiosks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKiosksRow
	for rows.Next() {
		var i ListKiosksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.EnabledSources,
			&i.Status,
			&i.DefaultLocale,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnusedRecoveryCodesByAdminID = `-- name: ListUnusedRecoveryCodesByAdminID :many
SELECT id, admin_id, code_hash, created_at
FROM admin_recovery_codes
WHERE admin_id = $1 AND used_at IS NULL
`

type ListUnusedRecoveryCodesByAdminIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	AdminID   pgtype.UUID        `json:"admin_id"`
	CodeHash  string             `json:"code_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUnusedRecoveryCodesByAdminID(ctx context.Context, adminID pgtype.UUID) ([]ListUnusedRecoveryCodesByAdminIDRow, error) {
	rows, err := q.db.Query(ctx, listUnusedRecoveryCodesByAdminID, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnusedRecoveryCodesByAdminIDRow
	for rows.Next() {
		var i ListUnusedRecoveryCodesByAdminIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.CodeHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :one
UPDATE admin_recovery_codes
SET used_at = now()
WHERE id = $1 AND used_at IS NULL
RETURNING id, admin_id, code_hash, used_at
`

type MarkRecoveryCodeUsedRow struct {
	ID       pgtype.UUID        `json:"id"`
	AdminID  pgtype.UUID        `json:"admin_id"`
	CodeHash string             `json:"code_hash"`
	UsedAt   pgtype.Timestamptz `json:"used_at"`
}

func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, id pgtype.UUID) (MarkRecoveryCodeUsedRow, error) {
	row := q.db.QueryRow(ctx, markRecoveryCodeUsed, id)
	var i MarkRecoveryCodeUsedRow
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.CodeHash,
		&i.UsedAt,
	)
	return i, err
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
UPDATE admin_accounts
SET failed_attempts = failed_attempts + 1,
    last_failure_at = now(),
    locked_until = $2,
    updated_at = now()
WHERE id = $1
RETURNING failed_attempts, locked_until
`

type RecordLoginFailureParams struct {
	ID          pgtype.UUID        `json:"id"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

type RecordLoginFailureRow struct {
	FailedAttempts int32              `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (RecordLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure, arg.ID, arg.LockedUntil)
	var i RecordLoginFailureRow
	err := row.Scan(&i.FailedAttempts, &i.LockedUntil)
	return i, err
}

const recordLoginSuccess = `-- name: RecordLoginSuccess :exec
UPDATE admin_accounts
SET failed_attempts = 0,
    last_failure_at = NULL,
    locked_until = NULL,
    last_login_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) RecordLoginSuccess(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordLoginSuccess, id)
	return err
}

const redeemKioskPairingCode = `-- name: RedeemKioskPairingCode :one
UPDATE kiosks
SET token_hash = $2, pairing_code_hash = NULL, pairing_code_expires_at = NULL
WHERE id = $1 AND pairing_code_hash = $3
RETURNING id, name, default_locale
`

type RedeemKioskPairingCodeParams struct {
	ID              pgtype.UUID `json:"id"`
	TokenHash       []byte      `json:"token_hash"`
	PairingCodeHash []byte      `json:"pairing_code_hash"`
}

type RedeemKioskPairingCodeRow struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	DefaultLocale string      `json:"default_locale"`
}

// Consumes the code and installs the freshly minted token in one statement,
// so a redeemed code can never be replayed. The pairing_code_hash predicate
// is what makes that true under concurrency as well as sequentially: two
// simultaneous redemptions of the same code both pass the preceding SELECT,
// but the row lock this UPDATE takes serialises them and the loser matches
// nothing (the winner has already nulled the hash), returning no rows
// instead of overwriting the token the winner was just handed.
func (q *Queries) RedeemKioskPairingCode(ctx context.Context, arg RedeemKioskPairingCodeParams) (RedeemKioskPairingCodeRow, error) {
	row := q.db.QueryRow(ctx, redeemKioskPairingCode, arg.ID, arg.TokenHash, arg.PairingCodeHash)
	var i RedeemKioskPairingCodeRow
	err := row.Scan(&i.ID, &i.Name, &i.DefaultLocale)
	return i, err
}

const renewSession = `-- name: RenewSession :one
UPDATE admin_sessions SET last_seen_at = now(), expires_at = $2
WHERE id = $1
RETURNING id, admin_id, session_token_hash, csrf_token, created_at, last_seen_at, expires_at
`

type RenewSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Sliding expiry: called on every valid use with a freshly computed
// expires_at (now + TTL), matching docs/09's "12-hour expiry with sliding
// renewal".
func (q *Queries) RenewSession(ctx context.Context, arg RenewSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, renewSession, arg.ID, arg.ExpiresAt)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.SessionTokenHash,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const resetAdminPassword = `-- name: ResetAdminPassword :one
UPDATE admin_accounts
SET password_hash = $2,
    must_change_password = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, email, full_name, role, status
`

type ResetAdminPasswordParams struct {
	ID                 pgtype.UUID `json:"id"`
	PasswordHash       string      `json:"password_hash"`
	MustChangePassword bool        `json:"must_change_password"`
}

type ResetAdminPasswordRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	FullName string      `json:"full_name"`
	Role     AdminRole   `json:"role"`
	Status   AdminStatus `json:"status"`
}

func (q *Queries) ResetAdminPassword(ctx context.Context, arg ResetAdminPasswordParams) (ResetAdminPasswordRow, error) {
	row := q.db.QueryRow(ctx, resetAdminPassword, arg.ID, arg.PasswordHash, arg.MustChangePassword)
	var i ResetAdminPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const setAdminPendingTotp = `-- name: SetAdminPendingTotp :one
UPDATE admin_accounts
SET totp_pending_secret_enc = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, email, full_name, role, status
`

type SetAdminPendingTotpParams struct {
	ID                   pgtype.UUID `json:"id"`
	TotpPendingSecretEnc []byte      `json:"totp_pending_secret_enc"`
}

type SetAdminPendingTotpRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	FullName string      `json:"full_name"`
	Role     AdminRole   `json:"role"`
	Status   AdminStatus `json:"status"`
}

func (q *Queries) SetAdminPendingTotp(ctx context.Context, arg SetAdminPendingTotpParams) (SetAdminPendingTotpRow, error) {
	row := q.db.QueryRow(ctx, setAdminPendingTotp, arg.ID, arg.TotpPendingSecretEnc)
	var i SetAdminPendingTotpRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const setAdminTotpSecret = `-- name: SetAdminTotpSecret :one
UPDATE admin_accounts
SET totp_secret_enc = $2,
    totp_pending_secret_enc = NULL,
    must_reenrol_totp = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, email, full_name, role, status
`

type SetAdminTotpSecretParams struct {
	ID              pgtype.UUID `json:"id"`
	TotpSecretEnc   []byte      `json:"totp_secret_enc"`
	MustReenrolTotp bool        `json:"must_reenrol_totp"`
}

type SetAdminTotpSecretRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	FullName string      `json:"full_name"`
	Role     AdminRole   `json:"role"`
	Status   AdminStatus `json:"status"`
}

func (q *Queries) SetAdminTotpSecret(ctx context.Context, arg SetAdminTotpSecretParams) (SetAdminTotpSecretRow, error) {
	row := q.db.QueryRow(ctx, setAdminTotpSecret, arg.ID, arg.TotpSecretEnc, arg.MustReenrolTotp)
	var i SetAdminTotpSecretRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const setKioskPairingCode = `-- name: SetKioskPairingCode :one
UPDATE kiosks SET pairing_code_hash = $2, pairing_code_expires_at = $3
WHERE id = $1
RETURNING id, name
`

type SetKioskPairingCodeParams struct {
	ID                   pgtype.UUID        `json:"id"`
	PairingCodeHash      []byte             `json:"pairing_code_hash"`
	PairingCodeExpiresAt pgtype.Timestamptz `json:"pairing_code_expires_at"`
}

type SetKioskPairingCodeRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) SetKioskPairingCode(ctx context.Context, arg SetKioskPairingCodeParams) (SetKioskPairingCodeRow, error) {
	row := q.db.QueryRow(ctx, setKioskPairingCode, arg.ID, arg.PairingCodeHash, arg.PairingCodeExpiresAt)
	var i SetKioskPairingCodeRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const unlockAdminAccount = `-- name: UnlockAdminAccount :one
UPDATE admin_accounts
SET failed_attempts = 0,
    last_failure_at = NULL,
    locked_until = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, email, full_name, role, status, failed_attempts, last_failure_at, locked_until,
          must_change_password, must_reenrol_totp, last_login_at, created_at, updated_at, locale
`

type UnlockAdminAccountRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Email              string             `json:"email"`
	FullName           string             `json:"full_name"`
	Role               AdminRole          `json:"role"`
	Status             AdminStatus        `json:"status"`
	FailedAttempts     int32              `json:"failed_attempts"`
	LastFailureAt      pgtype.Timestamptz `json:"last_failure_at"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	MustChangePassword bool               `json:"must_change_password"`
	MustReenrolTotp    bool               `json:"must_reenrol_totp"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Locale             string             `json:"locale"`
}

func (q *Queries) UnlockAdminAccount(ctx context.Context, id pgtype.UUID) (UnlockAdminAccountRow, error) {
	row := q.db.QueryRow(ctx, unlockAdminAccount, id)
	var i UnlockAdminAccountRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.Status,
		&i.FailedAttempts,
		&i.LastFailureAt,
		&i.LockedUntil,
		&i.MustChangePassword,
		&i.MustReenrolTotp,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Locale,
	)
	return i, err
}

const unlockAdminAccountByEmail = `-- name: UnlockAdminAccountByEmail :one
UPDATE admin_accounts
SET failed_attempts = 0,
    last_failure_at = NULL,
    locked_until = NULL,
    updated_at = now()
WHERE lower(email) = lower($1)
RETURNING id, email, full_name, role, status
`

type UnlockAdminAccountByEmailRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	FullName string      `json:"full_name"`
	Role     AdminRole   `json:"role"`
	Status   AdminStatus `json:"status"`
}

func (q *Queries) UnlockAdminAccountByEmail(ctx context.Context, lower string) (UnlockAdminAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, unlockAdminAccountByEmail, lower)
	var i UnlockAdminAccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const updateAdmin = `-- name: UpdateAdmin :one
UPDATE admin_accounts
SET full_name = COALESCE($1, full_name),
    role = COALESCE($2, role),
    status = COALESCE($3, status),
    updated_at = now()
WHERE id = $4
RETURNING id, email, full_name, role, status, failed_attempts, last_failure_at, locked_until,
          must_change_password, must_reenrol_totp, last_login_at, created_at, updated_at, locale
`

type UpdateAdminParams struct {
	FullName pgtype.Text     `json:"full_name"`
	Role     NullAdminRole   `json:"role"`
	Status   NullAdminStatus `json:"status"`
	ID       pgtype.UUID     `json:"id"`
}

type UpdateAdminRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Email              string             `json:"email"`
	FullName           string             `json:"full_name"`
	Role               AdminRole          `json:"role"`
	Status             AdminStatus        `json:"status"`
	FailedAttempts     int32              `json:"failed_attempts"`
	LastFailureAt      pgtype.Timestamptz `json:"last_failure_at"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	MustChangePassword bool               `json:"must_change_password"`
	MustReenrolTotp    bool               `json:"must_reenrol_totp"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Locale             string             `json:"locale"`
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (UpdateAdminRow, error) {
	row := q.db.QueryRow(ctx, updateAdmin,
		arg.FullName,
		arg.Role,
		arg.Status,
		arg.ID,
	)
	var i UpdateAdminRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.Status,
		&i.FailedAttempts,
		&i.LastFailureAt,
		&i.LockedUntil,
		&i.MustChangePassword,
		&i.MustReenrolTotp,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Locale,
	)
	return i, err
}

const updateAdminLocale = `-- name: UpdateAdminLocale :one
UPDATE admin_accounts
SET locale = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, email, full_name, role, status, failed_attempts, last_failure_at, locked_until,
          must_change_password, must_reenrol_totp, last_login_at, created_at, updated_at, locale
`

type UpdateAdminLocaleParams struct {
	ID     pgtype.UUID `json:"id"`
	Locale string      `json:"locale"`
}

type UpdateAdminLocaleRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Email              string             `json:"email"`
	FullName           string             `json:"full_name"`
	Role               AdminRole          `json:"role"`
	Status             AdminStatus        `json:"status"`
	FailedAttempts     int32              `json:"failed_attempts"`
	LastFailureAt      pgtype.Timestamptz `json:"last_failure_at"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	MustChangePassword bool               `json:"must_change_password"`
	MustReenrolTotp    bool               `json:"must_reenrol_totp"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Locale             string             `json:"locale"`
}

func (q *Queries) UpdateAdminLocale(ctx context.Context, arg UpdateAdminLocaleParams) (UpdateAdminLocaleRow, error) {
	row := q.db.QueryRow(ctx, updateAdminLocale, arg.ID, arg.Locale)
	var i UpdateAdminLocaleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.Status,
		&i.FailedAttempts,
		&i.LastFailureAt,
		&i.LockedUntil,
		&i.MustChangePassword,
		&i.MustReenrolTotp,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Locale,
	)
	return i, err
}

const updateKiosk = `-- name: UpdateKiosk :one
UPDATE kiosks
SET
    name = CASE WHEN $1::boolean THEN $2::text ELSE name END,
    location = CASE WHEN $3::boolean THEN $4::text ELSE location END,
    enabled_sources = CASE WHEN $5::boolean THEN $6::text[] ELSE enabled_sources END,
    default_locale = CASE WHEN $7::boolean THEN $8::text ELSE default_locale END
WHERE id = $9
RETURNING id, name, location, enabled_sources, status, default_locale, last_seen_at, created_at
`

type UpdateKioskParams struct {
	SetName           bool        `json:"set_name"`
	Name              string      `json:"name"`
	SetLocation       bool        `json:"set_location"`
	Location          string      `json:"location"`
	SetEnabledSources bool        `json:"set_enabled_sources"`
	EnabledSources    []string    `json:"enabled_sources"`
	SetDefaultLocale  bool        `json:"set_default_locale"`
	DefaultLocale     string      `json:"default_locale"`
	ID                pgtype.UUID `json:"id"`
}

type UpdateKioskRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Location       pgtype.Text        `json:"location"`
	EnabledSources []string           `json:"enabled_sources"`
	Status         KioskStatus        `json:"status"`
	DefaultLocale  string             `json:"default_locale"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateKiosk(ctx context.Context, arg UpdateKioskParams) (UpdateKioskRow, error) {
	row := q.db.QueryRow(ctx, updateKiosk,
		arg.SetName,
		arg.Name,
		arg.SetLocation,
		arg.Location,
		arg.SetEnabledSources,
		arg.EnabledSources,
		arg.SetDefaultLocale,
		arg.DefaultLocale,
		arg.ID,
	)
	var i UpdateKioskRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.EnabledSources,
		&i.Status,
		&i.DefaultLocale,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateKioskLastSeen = `-- name: UpdateKioskLastSeen :exec
UPDATE kiosks SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) UpdateKioskLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateKioskLastSeen, id)
	return err
}

const updateKioskTokenHash = `-- name: UpdateKioskTokenHash :one
UPDATE kiosks SET token_hash = $2
WHERE id = $1
RETURNING id, name, location, token_hash, enabled_sources, status, default_locale, last_seen_at, created_at
`

type UpdateKioskTokenHashParams struct {
	ID        pgtype.UUID `json:"id"`
	TokenHash []byte      `json:"token_hash"`
}

type UpdateKioskTokenHashRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Location       pgtype.Text        `json:"location"`
	TokenHash      []byte             `json:"token_hash"`
	EnabledSources []string           `json:"enabled_sources"`
	Status         KioskStatus        `json:"status"`
	DefaultLocale  string             `json:"default_locale"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Used by both explicit rotation and pairing-code redemption, which mints
// and reveals a fresh token the same way registration does.
func (q *Queries) UpdateKioskTokenHash(ctx context.Context, arg UpdateKioskTokenHashParams) (UpdateKioskTokenHashRow, error) {
	row := q.db.QueryRow(ctx, updateKioskTokenHash, arg.ID, arg.TokenHash)
	var i UpdateKioskTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.TokenHash,
		&i.EnabledSources,
		&i.Status,
		&i.DefaultLocale,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}
