// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminAccount = `-- name: CreateAdminAccount :one
INSERT INTO admin_accounts (id, email, full_name, password_hash, totp_secret_enc, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, full_name, password_hash, totp_secret_enc, role, status, created_at, updated_at
`

type CreateAdminAccountParams struct {
	ID            pgtype.UUID `json:"id"`
	Email         string      `json:"email"`
	FullName      string      `json:"full_name"`
	PasswordHash  string      `json:"password_hash"`
	TotpSecretEnc []byte      `json:"totp_secret_enc"`
	Role          AdminRole   `json:"role"`
}

func (q *Queries) CreateAdminAccount(ctx context.Context, arg CreateAdminAccountParams) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, createAdminAccount,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.TotpSecretEnc,
		arg.Role,
	)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO admin_sessions (id, admin_id, session_token_hash, csrf_token, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, admin_id, session_token_hash, csrf_token, created_at, last_seen_at, expires_at
`

type CreateSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	AdminID          pgtype.UUID        `json:"admin_id"`
	SessionTokenHash []byte             `json:"session_token_hash"`
	CsrfToken        string             `json:"csrf_token"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.AdminID,
		arg.SessionTokenHash,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.SessionTokenHash,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM admin_sessions WHERE session_token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, sessionTokenHash)
	return err
}

const getAdminAccountByEmail = `-- name: GetAdminAccountByEmail :one
SELECT id, email, full_name, password_hash, totp_secret_enc, role, status, created_at, updated_at
FROM admin_accounts WHERE lower(email) = lower($1)
`

// Only used at login, where a non-existent email must fail the same way a
// wrong password does (no user enumeration) — the caller compares errors,
// not this query's behaviour, to keep that response uniform.
func (q *Queries) GetAdminAccountByEmail(ctx context.Context, lower string) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, getAdminAccountByEmail, lower)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminAccountByID = `-- name: GetAdminAccountByID :one
SELECT id, email, full_name, password_hash, totp_secret_enc, role, status, created_at, updated_at
FROM admin_accounts WHERE id = $1
`

func (q *Queries) GetAdminAccountByID(ctx context.Context, id pgtype.UUID) (AdminAccount, error) {
	row := q.db.QueryRow(ctx, getAdminAccountByID, id)
	var i AdminAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKioskByTokenHash = `-- name: GetKioskByTokenHash :one
SELECT id, name, location, token_hash, enabled_sources, status, last_seen_at, created_at
FROM kiosks WHERE token_hash = $1
`

func (q *Queries) GetKioskByTokenHash(ctx context.Context, tokenHash []byte) (Kiosk, error) {
	row := q.db.QueryRow(ctx, getKioskByTokenHash, tokenHash)
	var i Kiosk
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.TokenHash,
		&i.EnabledSources,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    s.id, s.admin_id, s.session_token_hash, s.csrf_token, s.created_at, s.last_seen_at, s.expires_at,
    a.email, a.full_name, a.role, a.status AS admin_status
FROM admin_sessions s
JOIN admin_accounts a ON a.id = s.admin_id
WHERE s.session_token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID               pgtype.UUID        `json:"id"`
	AdminID          pgtype.UUID        `json:"admin_id"`
	SessionTokenHash []byte             `json:"session_token_hash"`
	CsrfToken        string             `json:"csrf_token"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Email            string             `json:"email"`
	FullName         string             `json:"full_name"`
	Role             AdminRole          `json:"role"`
	AdminStatus      AdminStatus        `json:"admin_status"`
}

// Joins the owning account so the middleware can reject a disabled account
// on every request without a second round trip.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, sessionTokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.SessionTokenHash,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.AdminStatus,
	)
	return i, err
}

const renewSession = `-- name: RenewSession :one
UPDATE admin_sessions SET last_seen_at = now(), expires_at = $2
WHERE id = $1
RETURNING id, admin_id, session_token_hash, csrf_token, created_at, last_seen_at, expires_at
`

type RenewSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Sliding expiry: called on every valid use with a freshly computed
// expires_at (now + TTL), matching docs/09's "12-hour expiry with sliding
// renewal".
func (q *Queries) RenewSession(ctx context.Context, arg RenewSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, renewSession, arg.ID, arg.ExpiresAt)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.SessionTokenHash,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateKioskLastSeen = `-- name: UpdateKioskLastSeen :exec
UPDATE kiosks SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) UpdateKioskLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateKioskLastSeen, id)
	return err
}
