// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAdminAccount(ctx context.Context, arg CreateAdminAccountParams) (AdminAccount, error)
	CreateKiosk(ctx context.Context, arg CreateKioskParams) (CreateKioskRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (AdminSession, error)
	DeleteSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) error
	// Only used at login, where a non-existent email must fail the same way a
	// wrong password does (no user enumeration) — the caller compares errors,
	// not this query's behaviour, to keep that response uniform.
	GetAdminAccountByEmail(ctx context.Context, lower string) (AdminAccount, error)
	GetAdminAccountByID(ctx context.Context, id pgtype.UUID) (AdminAccount, error)
	// Scoped to active kiosks so a disabled kiosk's stale pairing code (if any)
	// cannot be redeemed.
	GetKioskByPairingCodeHash(ctx context.Context, pairingCodeHash []byte) (GetKioskByPairingCodeHashRow, error)
	GetKioskByTokenHash(ctx context.Context, tokenHash []byte) (GetKioskByTokenHashRow, error)
	// Joins the owning account so the middleware can reject a disabled account
	// on every request without a second round trip.
	GetSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) (GetSessionByTokenHashRow, error)
	// Consumes the code and installs the freshly minted token in one statement,
	// so a redeemed code can never be replayed. The pairing_code_hash predicate
	// is what makes that true under concurrency as well as sequentially: two
	// simultaneous redemptions of the same code both pass the preceding SELECT,
	// but the row lock this UPDATE takes serialises them and the loser matches
	// nothing (the winner has already nulled the hash), returning no rows
	// instead of overwriting the token the winner was just handed.
	RedeemKioskPairingCode(ctx context.Context, arg RedeemKioskPairingCodeParams) (RedeemKioskPairingCodeRow, error)
	// Sliding expiry: called on every valid use with a freshly computed
	// expires_at (now + TTL), matching docs/09's "12-hour expiry with sliding
	// renewal".
	RenewSession(ctx context.Context, arg RenewSessionParams) (AdminSession, error)
	SetKioskPairingCode(ctx context.Context, arg SetKioskPairingCodeParams) (SetKioskPairingCodeRow, error)
	UpdateKioskLastSeen(ctx context.Context, id pgtype.UUID) error
	// Used by both explicit rotation and pairing-code redemption, which mints
	// and reveals a fresh token the same way registration does.
	UpdateKioskTokenHash(ctx context.Context, arg UpdateKioskTokenHashParams) (UpdateKioskTokenHashRow, error)
}

var _ Querier = (*Queries)(nil)
