// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAdminAccount(ctx context.Context, arg CreateAdminAccountParams) (AdminAccount, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (AdminSession, error)
	DeleteSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) error
	// Only used at login, where a non-existent email must fail the same way a
	// wrong password does (no user enumeration) — the caller compares errors,
	// not this query's behaviour, to keep that response uniform.
	GetAdminAccountByEmail(ctx context.Context, lower string) (AdminAccount, error)
	GetAdminAccountByID(ctx context.Context, id pgtype.UUID) (AdminAccount, error)
	GetKioskByTokenHash(ctx context.Context, tokenHash []byte) (Kiosk, error)
	// Joins the owning account so the middleware can reject a disabled account
	// on every request without a second round trip.
	GetSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) (GetSessionByTokenHashRow, error)
	// Sliding expiry: called on every valid use with a freshly computed
	// expires_at (now + TTL), matching docs/09's "12-hour expiry with sliding
	// renewal".
	RenewSession(ctx context.Context, arg RenewSessionParams) (AdminSession, error)
	UpdateKioskLastSeen(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
