// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package auditstore

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (id, at, actor, actor_ip, action, subject, payload, request_id)
VALUES ($1, now(), $2, $3, $4, $5, $6, $7)
`

type InsertAuditEventParams struct {
	ID        pgtype.UUID `json:"id"`
	Actor     string      `json:"actor"`
	ActorIp   *netip.Addr `json:"actor_ip"`
	Action    string      `json:"action"`
	Subject   string      `json:"subject"`
	Payload   []byte      `json:"payload"`
	RequestID pgtype.Text `json:"request_id"`
}

// Append-only by design (NFR-15, INV-8): there is no update or delete query
// in this file, and the application database role has no UPDATE/DELETE
// grant on audit_events at all.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.Actor,
		arg.ActorIp,
		arg.Action,
		arg.Subject,
		arg.Payload,
		arg.RequestID,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, at, actor, actor_ip, action, subject, payload, request_id
FROM audit_events
WHERE ($1::text IS NULL OR actor ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR subject ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR action = $3)
  AND ($4::timestamptz IS NULL OR at >= $4)
  AND ($5::timestamptz IS NULL OR at <= $5)
  AND (
    $6::timestamptz IS NULL
    OR at < $6
    OR (at = $6 AND id < $7)
  )
ORDER BY at DESC, id DESC
LIMIT $8
`

type ListAuditEventsParams struct {
	Actor       pgtype.Text        `json:"actor"`
	Subject     pgtype.Text        `json:"subject"`
	Action      pgtype.Text        `json:"action"`
	FromAt      pgtype.Timestamptz `json:"from_at"`
	ToAt        pgtype.Timestamptz `json:"to_at"`
	CursorAt    pgtype.Timestamptz `json:"cursor_at"`
	CursorID    pgtype.UUID        `json:"cursor_id"`
	ResultLimit int32              `json:"result_limit"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.Actor,
		arg.Subject,
		arg.Action,
		arg.FromAt,
		arg.ToAt,
		arg.CursorAt,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Actor,
			&i.ActorIp,
			&i.Action,
			&i.Subject,
			&i.Payload,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamAuditEventsForExport = `-- name: StreamAuditEventsForExport :many
SELECT id, at, actor, actor_ip, action, subject, payload, request_id
FROM audit_events
WHERE ($1::text IS NULL OR actor ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR subject ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR action = $3)
  AND ($4::timestamptz IS NULL OR at >= $4)
  AND ($5::timestamptz IS NULL OR at <= $5)
ORDER BY at DESC, id DESC
`

type StreamAuditEventsForExportParams struct {
	Actor   pgtype.Text        `json:"actor"`
	Subject pgtype.Text        `json:"subject"`
	Action  pgtype.Text        `json:"action"`
	FromAt  pgtype.Timestamptz `json:"from_at"`
	ToAt    pgtype.Timestamptz `json:"to_at"`
}

func (q *Queries) StreamAuditEventsForExport(ctx context.Context, arg StreamAuditEventsForExportParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, streamAuditEventsForExport,
		arg.Actor,
		arg.Subject,
		arg.Action,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Actor,
			&i.ActorIp,
			&i.Action,
			&i.Subject,
			&i.Payload,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
