// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditstore

import (
	"context"
)

type Querier interface {
	// Append-only by design (NFR-15, INV-8): there is no update or delete query
	// in this file, and the application database role has no UPDATE/DELETE
	// grant on audit_events at all.
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
}

var _ Querier = (*Queries)(nil)
