// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reservationsstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelReservation(ctx context.Context, arg CancelReservationParams) (Reservation, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	ExpireReservation(ctx context.Context, id pgtype.UUID) (Reservation, error)
	FindActiveOrUpcomingForDevice(ctx context.Context, arg FindActiveOrUpcomingForDeviceParams) (FindActiveOrUpcomingForDeviceRow, error)
	FindExpiredCandidates(ctx context.Context, arg FindExpiredCandidatesParams) ([]FindExpiredCandidatesRow, error)
	FulfillReservation(ctx context.Context, arg FulfillReservationParams) (Reservation, error)
	GetReservation(ctx context.Context, id pgtype.UUID) (GetReservationRow, error)
	GetReservationForUpdate(ctx context.Context, id pgtype.UUID) (Reservation, error)
	ListReservations(ctx context.Context, arg ListReservationsParams) ([]ListReservationsRow, error)
	ListReservationsByDevice(ctx context.Context, arg ListReservationsByDeviceParams) ([]ListReservationsByDeviceRow, error)
	ListReservationsByUser(ctx context.Context, arg ListReservationsByUserParams) ([]ListReservationsByUserRow, error)
}

var _ Querier = (*Queries)(nil)
