// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reservationsstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelReservation(ctx context.Context, arg CancelReservationParams) (Reservation, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	ExpireReservation(ctx context.Context, id pgtype.UUID) (Reservation, error)
	FindActiveOrUpcomingForDevice(ctx context.Context, arg FindActiveOrUpcomingForDeviceParams) (FindActiveOrUpcomingForDeviceRow, error)
	FindExpiredCandidates(ctx context.Context, arg FindExpiredCandidatesParams) ([]FindExpiredCandidatesRow, error)
	FulfillReservation(ctx context.Context, arg FulfillReservationParams) (Reservation, error)
	GetReservation(ctx context.Context, id pgtype.UUID) (GetReservationRow, error)
	GetReservationForUpdate(ctx context.Context, id pgtype.UUID) (Reservation, error)
	// Live statuses match reservations_no_overlapping_device_window.
	HasReservationWithinBuffer(ctx context.Context, arg HasReservationWithinBufferParams) (bool, error)
	ListReservations(ctx context.Context, arg ListReservationsParams) ([]ListReservationsRow, error)
	ListReservationsByDevice(ctx context.Context, arg ListReservationsByDeviceParams) ([]ListReservationsByDeviceRow, error)
	ListReservationsByUser(ctx context.Context, arg ListReservationsByUserParams) ([]ListReservationsByUserRow, error)
	// The earliest reservation that will still need the device after from_at.
	// Only 'active' counts: a collected reservation is already in its reserver's
	// hands. exclude_id skips the reservation a borrow is collecting.
	NextActiveReservationStart(ctx context.Context, arg NextActiveReservationStartParams) (pgtype.Timestamptz, error)
}

var _ Querier = (*Queries)(nil)
