// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package reservationsstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelReservation = `-- name: CancelReservation :one
UPDATE reservations
SET
    status = 'cancelled',
    cancelled_at = now(),
    cancelled_by = $2,
    cancellation_reason = $3,
    updated_at = now()
WHERE id = $1
  AND status = 'active'
RETURNING
    id,
    device_id,
    user_id,
    status,
    start_at,
    end_at,
    created_by,
    created_source,
    loan_id,
    cancelled_at,
    cancelled_by,
    cancellation_reason,
    created_at,
    updated_at
`

type CancelReservationParams struct {
	ID                 pgtype.UUID `json:"id"`
	CancelledBy        pgtype.Text `json:"cancelled_by"`
	CancellationReason pgtype.Text `json:"cancellation_reason"`
}

func (q *Queries) CancelReservation(ctx context.Context, arg CancelReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, cancelReservation, arg.ID, arg.CancelledBy, arg.CancellationReason)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedBy,
		&i.CreatedSource,
		&i.LoanID,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (
    id,
    device_id,
    user_id,
    status,
    start_at,
    end_at,
    created_by,
    created_source
) VALUES (
    $1,
    $2,
    $3,
    'active',
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id,
    device_id,
    user_id,
    status,
    start_at,
    end_at,
    created_by,
    created_source,
    loan_id,
    cancelled_at,
    cancelled_by,
    cancellation_reason,
    created_at,
    updated_at
`

type CreateReservationParams struct {
	ID            pgtype.UUID        `json:"id"`
	DeviceID      pgtype.UUID        `json:"device_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	StartAt       pgtype.Timestamptz `json:"start_at"`
	EndAt         pgtype.Timestamptz `json:"end_at"`
	CreatedBy     string             `json:"created_by"`
	CreatedSource string             `json:"created_source"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.ID,
		arg.DeviceID,
		arg.UserID,
		arg.StartAt,
		arg.EndAt,
		arg.CreatedBy,
		arg.CreatedSource,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedBy,
		&i.CreatedSource,
		&i.LoanID,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireReservation = `-- name: ExpireReservation :one
UPDATE reservations
SET
    status = 'expired',
    updated_at = now()
WHERE id = $1
  AND status = 'active'
RETURNING
    id,
    device_id,
    user_id,
    status,
    start_at,
    end_at,
    created_by,
    created_source,
    loan_id,
    cancelled_at,
    cancelled_by,
    cancellation_reason,
    created_at,
    updated_at
`

func (q *Queries) ExpireReservation(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, expireReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedBy,
		&i.CreatedSource,
		&i.LoanID,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findActiveOrUpcomingForDevice = `-- name: FindActiveOrUpcomingForDevice :one
SELECT
    r.id,
    r.device_id,
    r.user_id,
    r.status,
    r.start_at,
    r.end_at,
    r.created_by,
    r.created_source,
    r.loan_id,
    r.cancelled_at,
    r.cancelled_by,
    r.cancellation_reason,
    r.created_at,
    r.updated_at,
    d.name AS device_name,
    d.asset_tag AS device_asset_tag,
    u.full_name AS user_name,
    u.employee_no AS user_employee_no
FROM reservations r
JOIN devices d ON d.id = r.device_id
JOIN users u ON u.id = r.user_id
WHERE r.device_id = $1
  AND r.status = 'active'
  AND r.end_at > $2
  AND r.start_at <= ($2 + ($3 * interval '1 second'))
ORDER BY r.start_at ASC
LIMIT 1
`

type FindActiveOrUpcomingForDeviceParams struct {
	DeviceID pgtype.UUID        `json:"device_id"`
	EndAt    pgtype.Timestamptz `json:"end_at"`
	Column3  interface{}        `json:"column_3"`
}

type FindActiveOrUpcomingForDeviceRow struct {
	ID                 pgtype.UUID        `json:"id"`
	DeviceID           pgtype.UUID        `json:"device_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	Status             ReservationStatus  `json:"status"`
	StartAt            pgtype.Timestamptz `json:"start_at"`
	EndAt              pgtype.Timestamptz `json:"end_at"`
	CreatedBy          string             `json:"created_by"`
	CreatedSource      string             `json:"created_source"`
	LoanID             pgtype.UUID        `json:"loan_id"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy        pgtype.Text        `json:"cancelled_by"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeviceName         string             `json:"device_name"`
	DeviceAssetTag     string             `json:"device_asset_tag"`
	UserName           string             `json:"user_name"`
	UserEmployeeNo     string             `json:"user_employee_no"`
}

func (q *Queries) FindActiveOrUpcomingForDevice(ctx context.Context, arg FindActiveOrUpcomingForDeviceParams) (FindActiveOrUpcomingForDeviceRow, error) {
	row := q.db.QueryRow(ctx, findActiveOrUpcomingForDevice, arg.DeviceID, arg.EndAt, arg.Column3)
	var i FindActiveOrUpcomingForDeviceRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedBy,
		&i.CreatedSource,
		&i.LoanID,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceName,
		&i.DeviceAssetTag,
		&i.UserName,
		&i.UserEmployeeNo,
	)
	return i, err
}

const findExpiredCandidates = `-- name: FindExpiredCandidates :many
SELECT
    r.id,
    r.device_id,
    r.user_id,
    r.status,
    r.start_at,
    r.end_at,
    r.created_by,
    r.created_source,
    r.loan_id,
    r.cancelled_at,
    r.cancelled_by,
    r.cancellation_reason,
    r.created_at,
    r.updated_at,
    d.name AS device_name,
    d.asset_tag AS device_asset_tag,
    u.full_name AS user_name,
    u.employee_no AS user_employee_no,
    COALESCE(u.email, '') AS user_email
FROM reservations r
JOIN devices d ON d.id = r.device_id
JOIN users u ON u.id = r.user_id
WHERE r.status = 'active'
  AND (r.start_at + ($1 * interval '1 second')) < $2
ORDER BY r.start_at ASC
`

type FindExpiredCandidatesParams struct {
	Column1 interface{}        `json:"column_1"`
	StartAt pgtype.Timestamptz `json:"start_at"`
}

type FindExpiredCandidatesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	DeviceID           pgtype.UUID        `json:"device_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	Status             ReservationStatus  `json:"status"`
	StartAt            pgtype.Timestamptz `json:"start_at"`
	EndAt              pgtype.Timestamptz `json:"end_at"`
	CreatedBy          string             `json:"created_by"`
	CreatedSource      string             `json:"created_source"`
	LoanID             pgtype.UUID        `json:"loan_id"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy        pgtype.Text        `json:"cancelled_by"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeviceName         string             `json:"device_name"`
	DeviceAssetTag     string             `json:"device_asset_tag"`
	UserName           string             `json:"user_name"`
	UserEmployeeNo     string             `json:"user_employee_no"`
	UserEmail          string             `json:"user_email"`
}

func (q *Queries) FindExpiredCandidates(ctx context.Context, arg FindExpiredCandidatesParams) ([]FindExpiredCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findExpiredCandidates, arg.Column1, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindExpiredCandidatesRow
	for rows.Next() {
		var i FindExpiredCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.UserID,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedBy,
			&i.CreatedSource,
			&i.LoanID,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancellationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceName,
			&i.DeviceAssetTag,
			&i.UserName,
			&i.UserEmployeeNo,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fulfillReservation = `-- name: FulfillReservation :one
UPDATE reservations
SET
    status = 'collected',
    loan_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING
    id,
    device_id,
    user_id,
    status,
    start_at,
    end_at,
    created_by,
    created_source,
    loan_id,
    cancelled_at,
    cancelled_by,
    cancellation_reason,
    created_at,
    updated_at
`

type FulfillReservationParams struct {
	ID     pgtype.UUID `json:"id"`
	LoanID pgtype.UUID `json:"loan_id"`
}

func (q *Queries) FulfillReservation(ctx context.Context, arg FulfillReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, fulfillReservation, arg.ID, arg.LoanID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedBy,
		&i.CreatedSource,
		&i.LoanID,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT
    r.id,
    r.device_id,
    r.user_id,
    r.status,
    r.start_at,
    r.end_at,
    r.created_by,
    r.created_source,
    r.loan_id,
    r.cancelled_at,
    r.cancelled_by,
    r.cancellation_reason,
    r.created_at,
    r.updated_at,
    d.name AS device_name,
    d.asset_tag AS device_asset_tag,
    u.full_name AS user_name,
    u.employee_no AS user_employee_no
FROM reservations r
JOIN devices d ON d.id = r.device_id
JOIN users u ON u.id = r.user_id
WHERE r.id = $1
`

type GetReservationRow struct {
	ID                 pgtype.UUID        `json:"id"`
	DeviceID           pgtype.UUID        `json:"device_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	Status             ReservationStatus  `json:"status"`
	StartAt            pgtype.Timestamptz `json:"start_at"`
	EndAt              pgtype.Timestamptz `json:"end_at"`
	CreatedBy          string             `json:"created_by"`
	CreatedSource      string             `json:"created_source"`
	LoanID             pgtype.UUID        `json:"loan_id"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy        pgtype.Text        `json:"cancelled_by"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeviceName         string             `json:"device_name"`
	DeviceAssetTag     string             `json:"device_asset_tag"`
	UserName           string             `json:"user_name"`
	UserEmployeeNo     string             `json:"user_employee_no"`
}

func (q *Queries) GetReservation(ctx context.Context, id pgtype.UUID) (GetReservationRow, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i GetReservationRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedBy,
		&i.CreatedSource,
		&i.LoanID,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeviceName,
		&i.DeviceAssetTag,
		&i.UserName,
		&i.UserEmployeeNo,
	)
	return i, err
}

const getReservationForUpdate = `-- name: GetReservationForUpdate :one
SELECT
    id,
    device_id,
    user_id,
    status,
    start_at,
    end_at,
    created_by,
    created_source,
    loan_id,
    cancelled_at,
    cancelled_by,
    cancellation_reason,
    created_at,
    updated_at
FROM reservations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetReservationForUpdate(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationForUpdate, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedBy,
		&i.CreatedSource,
		&i.LoanID,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReservations = `-- name: ListReservations :many
SELECT
    r.id,
    r.device_id,
    r.user_id,
    r.status,
    r.start_at,
    r.end_at,
    r.created_by,
    r.created_source,
    r.loan_id,
    r.cancelled_at,
    r.cancelled_by,
    r.cancellation_reason,
    r.created_at,
    r.updated_at,
    d.name AS device_name,
    d.asset_tag AS device_asset_tag,
    u.full_name AS user_name,
    u.employee_no AS user_employee_no
FROM reservations r
JOIN devices d ON d.id = r.device_id
JOIN users u ON u.id = r.user_id
WHERE ($1::uuid IS NULL OR r.device_id = $1)
  AND ($2::uuid IS NULL OR r.user_id = $2)
  AND ($3::reservation_status IS NULL OR r.status = $3)
  AND (
      $4::timestamptz IS NULL
      OR r.start_at < $4
      OR (r.start_at = $4 AND r.id < $5)
  )
ORDER BY r.start_at DESC, r.id DESC
LIMIT $6
`

type ListReservationsParams struct {
	DeviceID      pgtype.UUID           `json:"device_id"`
	UserID        pgtype.UUID           `json:"user_id"`
	Status        NullReservationStatus `json:"status"`
	CursorStartAt pgtype.Timestamptz    `json:"cursor_start_at"`
	CursorID      pgtype.UUID           `json:"cursor_id"`
	ResultLimit   int32                 `json:"result_limit"`
}

type ListReservationsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	DeviceID           pgtype.UUID        `json:"device_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	Status             ReservationStatus  `json:"status"`
	StartAt            pgtype.Timestamptz `json:"start_at"`
	EndAt              pgtype.Timestamptz `json:"end_at"`
	CreatedBy          string             `json:"created_by"`
	CreatedSource      string             `json:"created_source"`
	LoanID             pgtype.UUID        `json:"loan_id"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy        pgtype.Text        `json:"cancelled_by"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeviceName         string             `json:"device_name"`
	DeviceAssetTag     string             `json:"device_asset_tag"`
	UserName           string             `json:"user_name"`
	UserEmployeeNo     string             `json:"user_employee_no"`
}

func (q *Queries) ListReservations(ctx context.Context, arg ListReservationsParams) ([]ListReservationsRow, error) {
	rows, err := q.db.Query(ctx, listReservations,
		arg.DeviceID,
		arg.UserID,
		arg.Status,
		arg.CursorStartAt,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationsRow
	for rows.Next() {
		var i ListReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.UserID,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedBy,
			&i.CreatedSource,
			&i.LoanID,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancellationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceName,
			&i.DeviceAssetTag,
			&i.UserName,
			&i.UserEmployeeNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByDevice = `-- name: ListReservationsByDevice :many
SELECT
    r.id,
    r.device_id,
    r.user_id,
    r.status,
    r.start_at,
    r.end_at,
    r.created_by,
    r.created_source,
    r.loan_id,
    r.cancelled_at,
    r.cancelled_by,
    r.cancellation_reason,
    r.created_at,
    r.updated_at,
    d.name AS device_name,
    d.asset_tag AS device_asset_tag,
    u.full_name AS user_name,
    u.employee_no AS user_employee_no
FROM reservations r
JOIN devices d ON d.id = r.device_id
JOIN users u ON u.id = r.user_id
WHERE r.device_id = $1
  AND ($2::reservation_status IS NULL OR r.status = $2)
  AND (
      $3::timestamptz IS NULL
      OR r.start_at < $3
      OR (r.start_at = $3 AND r.id < $4)
  )
ORDER BY r.start_at DESC, r.id DESC
LIMIT $5
`

type ListReservationsByDeviceParams struct {
	DeviceID      pgtype.UUID           `json:"device_id"`
	Status        NullReservationStatus `json:"status"`
	CursorStartAt pgtype.Timestamptz    `json:"cursor_start_at"`
	CursorID      pgtype.UUID           `json:"cursor_id"`
	ResultLimit   int32                 `json:"result_limit"`
}

type ListReservationsByDeviceRow struct {
	ID                 pgtype.UUID        `json:"id"`
	DeviceID           pgtype.UUID        `json:"device_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	Status             ReservationStatus  `json:"status"`
	StartAt            pgtype.Timestamptz `json:"start_at"`
	EndAt              pgtype.Timestamptz `json:"end_at"`
	CreatedBy          string             `json:"created_by"`
	CreatedSource      string             `json:"created_source"`
	LoanID             pgtype.UUID        `json:"loan_id"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy        pgtype.Text        `json:"cancelled_by"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeviceName         string             `json:"device_name"`
	DeviceAssetTag     string             `json:"device_asset_tag"`
	UserName           string             `json:"user_name"`
	UserEmployeeNo     string             `json:"user_employee_no"`
}

func (q *Queries) ListReservationsByDevice(ctx context.Context, arg ListReservationsByDeviceParams) ([]ListReservationsByDeviceRow, error) {
	rows, err := q.db.Query(ctx, listReservationsByDevice,
		arg.DeviceID,
		arg.Status,
		arg.CursorStartAt,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationsByDeviceRow
	for rows.Next() {
		var i ListReservationsByDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.UserID,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedBy,
			&i.CreatedSource,
			&i.LoanID,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancellationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceName,
			&i.DeviceAssetTag,
			&i.UserName,
			&i.UserEmployeeNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByUser = `-- name: ListReservationsByUser :many
SELECT
    r.id,
    r.device_id,
    r.user_id,
    r.status,
    r.start_at,
    r.end_at,
    r.created_by,
    r.created_source,
    r.loan_id,
    r.cancelled_at,
    r.cancelled_by,
    r.cancellation_reason,
    r.created_at,
    r.updated_at,
    d.name AS device_name,
    d.asset_tag AS device_asset_tag,
    u.full_name AS user_name,
    u.employee_no AS user_employee_no
FROM reservations r
JOIN devices d ON d.id = r.device_id
JOIN users u ON u.id = r.user_id
WHERE r.user_id = $1
  AND ($2::reservation_status IS NULL OR r.status = $2)
  AND (
      $3::timestamptz IS NULL
      OR r.start_at < $3
      OR (r.start_at = $3 AND r.id < $4)
  )
ORDER BY r.start_at DESC, r.id DESC
LIMIT $5
`

type ListReservationsByUserParams struct {
	UserID        pgtype.UUID           `json:"user_id"`
	Status        NullReservationStatus `json:"status"`
	CursorStartAt pgtype.Timestamptz    `json:"cursor_start_at"`
	CursorID      pgtype.UUID           `json:"cursor_id"`
	ResultLimit   int32                 `json:"result_limit"`
}

type ListReservationsByUserRow struct {
	ID                 pgtype.UUID        `json:"id"`
	DeviceID           pgtype.UUID        `json:"device_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	Status             ReservationStatus  `json:"status"`
	StartAt            pgtype.Timestamptz `json:"start_at"`
	EndAt              pgtype.Timestamptz `json:"end_at"`
	CreatedBy          string             `json:"created_by"`
	CreatedSource      string             `json:"created_source"`
	LoanID             pgtype.UUID        `json:"loan_id"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy        pgtype.Text        `json:"cancelled_by"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeviceName         string             `json:"device_name"`
	DeviceAssetTag     string             `json:"device_asset_tag"`
	UserName           string             `json:"user_name"`
	UserEmployeeNo     string             `json:"user_employee_no"`
}

func (q *Queries) ListReservationsByUser(ctx context.Context, arg ListReservationsByUserParams) ([]ListReservationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listReservationsByUser,
		arg.UserID,
		arg.Status,
		arg.CursorStartAt,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReservationsByUserRow
	for rows.Next() {
		var i ListReservationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.UserID,
			&i.Status,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedBy,
			&i.CreatedSource,
			&i.LoanID,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancellationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeviceName,
			&i.DeviceAssetTag,
			&i.UserName,
			&i.UserEmployeeNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
