// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lending.sql

package lendingstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeHistoricalAt = `-- name: CloseHistoricalAt :one
UPDATE loans
SET status = 'returned', returned_at = $2, return_actor = $3, return_source = $4,
    condition_in = COALESCE($5::device_condition, condition_in),
    paper_ref = COALESCE(paper_ref, $6::text),
    recorded_at = COALESCE(recorded_at, $7::timestamptz),
    recorded_by = COALESCE(recorded_by, $8::text),
    backfill_note = COALESCE(backfill_note, $9::text)
WHERE id = $1
  AND NOT disputed
  AND borrowed_at < $2
  AND (returned_at IS NULL OR returned_at > $2)
RETURNING id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
`

type CloseHistoricalAtParams struct {
	ID           pgtype.UUID         `json:"id"`
	ReturnedAt   pgtype.Timestamptz  `json:"returned_at"`
	ReturnActor  pgtype.Text         `json:"return_actor"`
	ReturnSource pgtype.Text         `json:"return_source"`
	ConditionIn  NullDeviceCondition `json:"condition_in"`
	PaperRef     pgtype.Text         `json:"paper_ref"`
	RecordedAt   pgtype.Timestamptz  `json:"recorded_at"`
	RecordedBy   pgtype.Text         `json:"recorded_by"`
	BackfillNote pgtype.Text         `json:"backfill_note"`
}

// 2.4b's historical close: end a loan at an explicit, possibly past,
// instant, moving returned_at EARLIER when it is already set (the
// truncate-existing conflict resolution) or setting it for the first time
// (a paper return row closing an open loan). Paper provenance is filled in
// only where the loan does not already carry any (COALESCE against the
// loan's own values), so closing a kiosk-origin loan never rewrites its
// origin or invents a second provenance story.
func (q *Queries) CloseHistoricalAt(ctx context.Context, arg CloseHistoricalAtParams) (Loan, error) {
	row := q.db.QueryRow(ctx, closeHistoricalAt,
		arg.ID,
		arg.ReturnedAt,
		arg.ReturnActor,
		arg.ReturnSource,
		arg.ConditionIn,
		arg.PaperRef,
		arg.RecordedAt,
		arg.RecordedBy,
		arg.BackfillNote,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const closeLoan = `-- name: CloseLoan :one
UPDATE loans
SET status = 'returned', returned_at = $2, return_kiosk_id = $3, return_actor = $4,
    return_source = $5, condition_in = $6
WHERE id = $1 AND status = 'open'
RETURNING id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
`

type CloseLoanParams struct {
	ID            pgtype.UUID         `json:"id"`
	ReturnedAt    pgtype.Timestamptz  `json:"returned_at"`
	ReturnKioskID pgtype.UUID         `json:"return_kiosk_id"`
	ReturnActor   pgtype.Text         `json:"return_actor"`
	ReturnSource  pgtype.Text         `json:"return_source"`
	ConditionIn   NullDeviceCondition `json:"condition_in"`
}

func (q *Queries) CloseLoan(ctx context.Context, arg CloseLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, closeLoan,
		arg.ID,
		arg.ReturnedAt,
		arg.ReturnKioskID,
		arg.ReturnActor,
		arg.ReturnSource,
		arg.ConditionIn,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const countOpenByDevice = `-- name: CountOpenByDevice :one
SELECT count(*) FROM loans WHERE device_id = $1 AND status = 'open' AND NOT disputed
`

func (q *Queries) CountOpenByDevice(ctx context.Context, deviceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenByDevice, deviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const custodyAt = `-- name: CustodyAt :one
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans
WHERE device_id = $1
  AND status <> 'written_off' AND NOT disputed
  AND tstzrange(borrowed_at, returned_at, '[)') @> $2::timestamptz
`

type CustodyAtParams struct {
	DeviceID pgtype.UUID        `json:"device_id"`
	At       pgtype.Timestamptz `json:"at"`
}

// The loan (open or covering) whose custody window contains `at`, ignoring
// written-off and disputed rows — what ResolveHistorical (2.4b) and the
// backfill conflict report both need.
func (q *Queries) CustodyAt(ctx context.Context, arg CustodyAtParams) (Loan, error) {
	row := q.db.QueryRow(ctx, custodyAt, arg.DeviceID, arg.At)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const forceReturnLoan = `-- name: ForceReturnLoan :one
UPDATE loans
SET status = 'returned', returned_at = $2, return_actor = $3, return_source = 'manual',
    condition_in = $4, notes = $5
WHERE id = $1 AND status = 'open'
RETURNING id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
`

type ForceReturnLoanParams struct {
	ID          pgtype.UUID         `json:"id"`
	ReturnedAt  pgtype.Timestamptz  `json:"returned_at"`
	ReturnActor pgtype.Text         `json:"return_actor"`
	ConditionIn NullDeviceCondition `json:"condition_in"`
	Notes       pgtype.Text         `json:"notes"`
}

func (q *Queries) ForceReturnLoan(ctx context.Context, arg ForceReturnLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, forceReturnLoan,
		arg.ID,
		arg.ReturnedAt,
		arg.ReturnActor,
		arg.ConditionIn,
		arg.Notes,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const getCategoryLoanStatsInWindow = `-- name: GetCategoryLoanStatsInWindow :many
SELECT
    d.category_id,
    COUNT(l.id)::bigint AS loan_count,
    AVG(CASE WHEN l.returned_at IS NOT NULL THEN EXTRACT(EPOCH FROM (l.returned_at - l.borrowed_at)) / 3600.0 ELSE NULL END)::float8 AS avg_duration_hours,
    COALESCE(SUM(
        EXTRACT(EPOCH FROM (
            LEAST(COALESCE(l.returned_at, now(), $1::timestamptz), $1::timestamptz) -
            GREATEST(l.borrowed_at, $2::timestamptz)
        ))
    ), 0)::float8 AS total_loan_seconds
FROM loans l
JOIN devices d ON l.device_id = d.id
WHERE l.borrowed_at <= $1::timestamptz
  AND (l.returned_at IS NULL OR l.returned_at >= $2::timestamptz)
  AND l.status <> 'written_off'
  AND NOT l.disputed
GROUP BY d.category_id
`

type GetCategoryLoanStatsInWindowParams struct {
	ToAt   pgtype.Timestamptz `json:"to_at"`
	FromAt pgtype.Timestamptz `json:"from_at"`
}

type GetCategoryLoanStatsInWindowRow struct {
	CategoryID       pgtype.UUID `json:"category_id"`
	LoanCount        int64       `json:"loan_count"`
	AvgDurationHours float64     `json:"avg_duration_hours"`
	TotalLoanSeconds float64     `json:"total_loan_seconds"`
}

func (q *Queries) GetCategoryLoanStatsInWindow(ctx context.Context, arg GetCategoryLoanStatsInWindowParams) ([]GetCategoryLoanStatsInWindowRow, error) {
	rows, err := q.db.Query(ctx, getCategoryLoanStatsInWindow, arg.ToAt, arg.FromAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryLoanStatsInWindowRow
	for rows.Next() {
		var i GetCategoryLoanStatsInWindowRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.LoanCount,
			&i.AvgDurationHours,
			&i.TotalLoanSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoan = `-- name: GetLoan :one
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans WHERE id = $1
`

func (q *Queries) GetLoan(ctx context.Context, id pgtype.UUID) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoan, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const getReportSummaryStats = `-- name: GetReportSummaryStats :one
SELECT
    COUNT(*)::bigint AS total_loans,
    COUNT(*) FILTER (WHERE status = 'open')::bigint AS open_loans,
    COUNT(*) FILTER (WHERE status = 'open' AND due_at IS NOT NULL AND due_at < now())::bigint AS overdue_count,
    AVG(CASE WHEN returned_at IS NOT NULL THEN EXTRACT(EPOCH FROM (returned_at - borrowed_at)) / 3600.0 ELSE NULL END)::float8 AS avg_duration_hours
FROM loans
WHERE borrowed_at >= $1::timestamptz
  AND borrowed_at <= $2::timestamptz
`

type GetReportSummaryStatsParams struct {
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type GetReportSummaryStatsRow struct {
	TotalLoans       int64   `json:"total_loans"`
	OpenLoans        int64   `json:"open_loans"`
	OverdueCount     int64   `json:"overdue_count"`
	AvgDurationHours float64 `json:"avg_duration_hours"`
}

func (q *Queries) GetReportSummaryStats(ctx context.Context, arg GetReportSummaryStatsParams) (GetReportSummaryStatsRow, error) {
	row := q.db.QueryRow(ctx, getReportSummaryStats, arg.FromAt, arg.ToAt)
	var i GetReportSummaryStatsRow
	err := row.Scan(
		&i.TotalLoans,
		&i.OpenLoans,
		&i.OverdueCount,
		&i.AvgDurationHours,
	)
	return i, err
}

const getTopBorrowers = `-- name: GetTopBorrowers :many
SELECT
    user_id,
    COUNT(*)::bigint AS loan_count
FROM loans
WHERE borrowed_at >= $1::timestamptz
  AND borrowed_at <= $2::timestamptz
GROUP BY user_id
ORDER BY loan_count DESC, user_id ASC
LIMIT 10
`

type GetTopBorrowersParams struct {
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type GetTopBorrowersRow struct {
	UserID    pgtype.UUID `json:"user_id"`
	LoanCount int64       `json:"loan_count"`
}

func (q *Queries) GetTopBorrowers(ctx context.Context, arg GetTopBorrowersParams) ([]GetTopBorrowersRow, error) {
	rows, err := q.db.Query(ctx, getTopBorrowers, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopBorrowersRow
	for rows.Next() {
		var i GetTopBorrowersRow
		if err := rows.Scan(&i.UserID, &i.LoanCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByOriginDay = `-- name: GetTransactionsByOriginDay :many
SELECT
    date_trunc('day', borrowed_at)::timestamptz AS period_start,
    origin,
    COUNT(*)::bigint AS count
FROM loans
WHERE borrowed_at >= $1::timestamptz
  AND borrowed_at <= $2::timestamptz
GROUP BY period_start, origin
ORDER BY period_start ASC, origin ASC
`

type GetTransactionsByOriginDayParams struct {
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type GetTransactionsByOriginDayRow struct {
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	Origin      LoanOrigin         `json:"origin"`
	Count       int64              `json:"count"`
}

func (q *Queries) GetTransactionsByOriginDay(ctx context.Context, arg GetTransactionsByOriginDayParams) ([]GetTransactionsByOriginDayRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsByOriginDay, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByOriginDayRow
	for rows.Next() {
		var i GetTransactionsByOriginDayRow
		if err := rows.Scan(&i.PeriodStart, &i.Origin, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByOriginMonth = `-- name: GetTransactionsByOriginMonth :many
SELECT
    date_trunc('month', borrowed_at)::timestamptz AS period_start,
    origin,
    COUNT(*)::bigint AS count
FROM loans
WHERE borrowed_at >= $1::timestamptz
  AND borrowed_at <= $2::timestamptz
GROUP BY period_start, origin
ORDER BY period_start ASC, origin ASC
`

type GetTransactionsByOriginMonthParams struct {
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type GetTransactionsByOriginMonthRow struct {
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	Origin      LoanOrigin         `json:"origin"`
	Count       int64              `json:"count"`
}

func (q *Queries) GetTransactionsByOriginMonth(ctx context.Context, arg GetTransactionsByOriginMonthParams) ([]GetTransactionsByOriginMonthRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsByOriginMonth, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByOriginMonthRow
	for rows.Next() {
		var i GetTransactionsByOriginMonthRow
		if err := rows.Scan(&i.PeriodStart, &i.Origin, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByOriginWeek = `-- name: GetTransactionsByOriginWeek :many
SELECT
    date_trunc('week', borrowed_at)::timestamptz AS period_start,
    origin,
    COUNT(*)::bigint AS count
FROM loans
WHERE borrowed_at >= $1::timestamptz
  AND borrowed_at <= $2::timestamptz
GROUP BY period_start, origin
ORDER BY period_start ASC, origin ASC
`

type GetTransactionsByOriginWeekParams struct {
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

type GetTransactionsByOriginWeekRow struct {
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	Origin      LoanOrigin         `json:"origin"`
	Count       int64              `json:"count"`
}

func (q *Queries) GetTransactionsByOriginWeek(ctx context.Context, arg GetTransactionsByOriginWeekParams) ([]GetTransactionsByOriginWeekRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsByOriginWeek, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByOriginWeekRow
	for rows.Next() {
		var i GetTransactionsByOriginWeekRow
		if err := rows.Scan(&i.PeriodStart, &i.Origin, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCorrectedLoan = `-- name: InsertCorrectedLoan :one
INSERT INTO loans (
    id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20, $21,
    $22, $23
)
RETURNING id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
`

type InsertCorrectedLoanParams struct {
	ID            pgtype.UUID         `json:"id"`
	DeviceID      pgtype.UUID         `json:"device_id"`
	UserID        pgtype.UUID         `json:"user_id"`
	Status        LoanStatus          `json:"status"`
	Origin        LoanOrigin          `json:"origin"`
	BorrowedAt    pgtype.Timestamptz  `json:"borrowed_at"`
	DueAt         pgtype.Timestamptz  `json:"due_at"`
	ReturnedAt    pgtype.Timestamptz  `json:"returned_at"`
	BorrowKioskID pgtype.UUID         `json:"borrow_kiosk_id"`
	ReturnKioskID pgtype.UUID         `json:"return_kiosk_id"`
	BorrowActor   string              `json:"borrow_actor"`
	ReturnActor   pgtype.Text         `json:"return_actor"`
	BorrowSource  string              `json:"borrow_source"`
	ReturnSource  pgtype.Text         `json:"return_source"`
	ConditionOut  NullDeviceCondition `json:"condition_out"`
	ConditionIn   NullDeviceCondition `json:"condition_in"`
	Notes         pgtype.Text         `json:"notes"`
	SessionID     pgtype.UUID         `json:"session_id"`
	PaperRef      pgtype.Text         `json:"paper_ref"`
	RecordedAt    pgtype.Timestamptz  `json:"recorded_at"`
	RecordedBy    pgtype.Text         `json:"recorded_by"`
	BackfillNote  pgtype.Text         `json:"backfill_note"`
	Disputed      bool                `json:"disputed"`
}

// Inserts a corrected loan linked to an original mis-assigned or typo row.
func (q *Queries) InsertCorrectedLoan(ctx context.Context, arg InsertCorrectedLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, insertCorrectedLoan,
		arg.ID,
		arg.DeviceID,
		arg.UserID,
		arg.Status,
		arg.Origin,
		arg.BorrowedAt,
		arg.DueAt,
		arg.ReturnedAt,
		arg.BorrowKioskID,
		arg.ReturnKioskID,
		arg.BorrowActor,
		arg.ReturnActor,
		arg.BorrowSource,
		arg.ReturnSource,
		arg.ConditionOut,
		arg.ConditionIn,
		arg.Notes,
		arg.SessionID,
		arg.PaperRef,
		arg.RecordedAt,
		arg.RecordedBy,
		arg.BackfillNote,
		arg.Disputed,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const lastPaperEntry = `-- name: LastPaperEntry :many
SELECT paper_ref, recorded_at, recorded_by
FROM loans
WHERE origin = 'paper' AND recorded_at IS NOT NULL
ORDER BY recorded_at DESC
LIMIT 1
`

type LastPaperEntryRow struct {
	PaperRef   pgtype.Text        `json:"paper_ref"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
	RecordedBy pgtype.Text        `json:"recorded_by"`
}

// The most recent paper-origin recording, for the dashboard's "last paper
// entry: N days ago" nag (2.4b.5). :many + LIMIT 1 rather than :one so the
// empty case is an empty slice, not an error the caller must unwrap.
func (q *Queries) LastPaperEntry(ctx context.Context) ([]LastPaperEntryRow, error) {
	rows, err := q.db.Query(ctx, lastPaperEntry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LastPaperEntryRow
	for rows.Next() {
		var i LastPaperEntryRow
		if err := rows.Scan(&i.PaperRef, &i.RecordedAt, &i.RecordedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoans = `-- name: ListLoans :many
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans
WHERE ($1::loan_status IS NULL OR status = $1)
  AND ($2::loan_origin IS NULL OR origin = $2)
  AND ($3::uuid IS NULL OR user_id = $3)
  AND ($4::uuid IS NULL OR device_id = $4)
  AND ($5::boolean IS NULL OR disputed = $5)
  AND ($6::timestamptz IS NULL OR borrowed_at >= $6)
  AND ($7::timestamptz IS NULL OR borrowed_at <= $7)
  AND (
    $8::timestamptz IS NULL
    OR borrowed_at < $8
    OR (borrowed_at = $8 AND id < $9)
  )
ORDER BY borrowed_at DESC, id DESC
LIMIT $10
`

type ListLoansParams struct {
	Status           NullLoanStatus     `json:"status"`
	Origin           NullLoanOrigin     `json:"origin"`
	UserID           pgtype.UUID        `json:"user_id"`
	DeviceID         pgtype.UUID        `json:"device_id"`
	Disputed         pgtype.Bool        `json:"disputed"`
	FromAt           pgtype.Timestamptz `json:"from_at"`
	ToAt             pgtype.Timestamptz `json:"to_at"`
	CursorBorrowedAt pgtype.Timestamptz `json:"cursor_borrowed_at"`
	CursorID         pgtype.UUID        `json:"cursor_id"`
	ResultLimit      int32              `json:"result_limit"`
}

func (q *Queries) ListLoans(ctx context.Context, arg ListLoansParams) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoans,
		arg.Status,
		arg.Origin,
		arg.UserID,
		arg.DeviceID,
		arg.Disputed,
		arg.FromAt,
		arg.ToAt,
		arg.CursorBorrowedAt,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.UserID,
			&i.Status,
			&i.Origin,
			&i.BorrowedAt,
			&i.DueAt,
			&i.ReturnedAt,
			&i.BorrowKioskID,
			&i.ReturnKioskID,
			&i.BorrowActor,
			&i.ReturnActor,
			&i.BorrowSource,
			&i.ReturnSource,
			&i.ConditionOut,
			&i.ConditionIn,
			&i.Notes,
			&i.SessionID,
			&i.PaperRef,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.BackfillNote,
			&i.Disputed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLoanDisputed = `-- name: MarkLoanDisputed :one
UPDATE loans
SET disputed = true, notes = $2
WHERE id = $1
RETURNING id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
`

type MarkLoanDisputedParams struct {
	ID    pgtype.UUID `json:"id"`
	Notes pgtype.Text `json:"notes"`
}

// Marks a loan row as disputed, releasing its temporal custody hold
// while preserving the original borrower and timestamps intact for audit.
func (q *Queries) MarkLoanDisputed(ctx context.Context, arg MarkLoanDisputedParams) (Loan, error) {
	row := q.db.QueryRow(ctx, markLoanDisputed, arg.ID, arg.Notes)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const openLoan = `-- name: OpenLoan :one
INSERT INTO loans (
    id, device_id, user_id, borrowed_at, due_at,
    borrow_kiosk_id, borrow_actor, borrow_source, condition_out, session_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
`

type OpenLoanParams struct {
	ID            pgtype.UUID         `json:"id"`
	DeviceID      pgtype.UUID         `json:"device_id"`
	UserID        pgtype.UUID         `json:"user_id"`
	BorrowedAt    pgtype.Timestamptz  `json:"borrowed_at"`
	DueAt         pgtype.Timestamptz  `json:"due_at"`
	BorrowKioskID pgtype.UUID         `json:"borrow_kiosk_id"`
	BorrowActor   string              `json:"borrow_actor"`
	BorrowSource  string              `json:"borrow_source"`
	ConditionOut  NullDeviceCondition `json:"condition_out"`
	SessionID     pgtype.UUID         `json:"session_id"`
}

// The live path: origin is always 'kiosk' — a loan opened here means a
// device was scanned right now, whether at a kiosk or overridden live by an
// admin. Genuinely backdated loans go through RecordHistorical instead.
func (q *Queries) OpenLoan(ctx context.Context, arg OpenLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, openLoan,
		arg.ID,
		arg.DeviceID,
		arg.UserID,
		arg.BorrowedAt,
		arg.DueAt,
		arg.BorrowKioskID,
		arg.BorrowActor,
		arg.BorrowSource,
		arg.ConditionOut,
		arg.SessionID,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const openLoanForDevice = `-- name: OpenLoanForDevice :one
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans WHERE device_id = $1 AND status = 'open' AND NOT disputed
`

func (q *Queries) OpenLoanForDevice(ctx context.Context, deviceID pgtype.UUID) (Loan, error) {
	row := q.db.QueryRow(ctx, openLoanForDevice, deviceID)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const openLoansForUser = `-- name: OpenLoansForUser :many
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans WHERE user_id = $1 AND status = 'open' AND NOT disputed
ORDER BY borrowed_at DESC
`

// NOT disputed: a disputed row is a recorded claim, never a custody fact,
// so it never appears as one of the user's open loans (2.4b).
func (q *Queries) OpenLoansForUser(ctx context.Context, userID pgtype.UUID) ([]Loan, error) {
	rows, err := q.db.Query(ctx, openLoansForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.UserID,
			&i.Status,
			&i.Origin,
			&i.BorrowedAt,
			&i.DueAt,
			&i.ReturnedAt,
			&i.BorrowKioskID,
			&i.ReturnKioskID,
			&i.BorrowActor,
			&i.ReturnActor,
			&i.BorrowSource,
			&i.ReturnSource,
			&i.ConditionOut,
			&i.ConditionIn,
			&i.Notes,
			&i.SessionID,
			&i.PaperRef,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.BackfillNote,
			&i.Disputed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overdueLoans = `-- name: OverdueLoans :many
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans
WHERE status = 'open' AND NOT disputed AND due_at IS NOT NULL AND due_at < $1
ORDER BY due_at
`

func (q *Queries) OverdueLoans(ctx context.Context, dueAt pgtype.Timestamptz) ([]Loan, error) {
	rows, err := q.db.Query(ctx, overdueLoans, dueAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.UserID,
			&i.Status,
			&i.Origin,
			&i.BorrowedAt,
			&i.DueAt,
			&i.ReturnedAt,
			&i.BorrowKioskID,
			&i.ReturnKioskID,
			&i.BorrowActor,
			&i.ReturnActor,
			&i.BorrowSource,
			&i.ReturnSource,
			&i.ConditionOut,
			&i.ConditionIn,
			&i.Notes,
			&i.SessionID,
			&i.PaperRef,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.BackfillNote,
			&i.Disputed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overlappingLoan = `-- name: OverlappingLoan :one
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans
WHERE device_id = $1
  AND status <> 'written_off' AND NOT disputed
  AND tstzrange(borrowed_at, returned_at, '[)')
      && tstzrange($2::timestamptz, $3::timestamptz, '[)')
LIMIT 1
`

type OverlappingLoanParams struct {
	DeviceID   pgtype.UUID        `json:"device_id"`
	BorrowedAt pgtype.Timestamptz `json:"borrowed_at"`
	ReturnedAt pgtype.Timestamptz `json:"returned_at"`
}

// Re-read used only to populate OverlappingCustodyError.Existing after a
// loans_no_overlapping_custody violation: the specific row whose window
// intersects the range just rejected.
func (q *Queries) OverlappingLoan(ctx context.Context, arg OverlappingLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, overlappingLoan, arg.DeviceID, arg.BorrowedAt, arg.ReturnedAt)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const recordHistorical = `-- name: RecordHistorical :one
INSERT INTO loans (
    id, device_id, user_id, status, origin, borrowed_at, returned_at,
    borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes,
    paper_ref, recorded_at, recorded_by, backfill_note, disputed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17, $18, $19
)
RETURNING id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
`

type RecordHistoricalParams struct {
	ID           pgtype.UUID         `json:"id"`
	DeviceID     pgtype.UUID         `json:"device_id"`
	UserID       pgtype.UUID         `json:"user_id"`
	Status       LoanStatus          `json:"status"`
	Origin       LoanOrigin          `json:"origin"`
	BorrowedAt   pgtype.Timestamptz  `json:"borrowed_at"`
	ReturnedAt   pgtype.Timestamptz  `json:"returned_at"`
	BorrowActor  string              `json:"borrow_actor"`
	ReturnActor  pgtype.Text         `json:"return_actor"`
	BorrowSource string              `json:"borrow_source"`
	ReturnSource pgtype.Text         `json:"return_source"`
	ConditionOut NullDeviceCondition `json:"condition_out"`
	ConditionIn  NullDeviceCondition `json:"condition_in"`
	Notes        pgtype.Text         `json:"notes"`
	PaperRef     pgtype.Text         `json:"paper_ref"`
	RecordedAt   pgtype.Timestamptz  `json:"recorded_at"`
	RecordedBy   pgtype.Text         `json:"recorded_by"`
	BackfillNote pgtype.Text         `json:"backfill_note"`
	Disputed     bool                `json:"disputed"`
}

// The only insert path with an explicit, possibly past, borrowed_at and
// full paper/import provenance (2.4b).
func (q *Queries) RecordHistorical(ctx context.Context, arg RecordHistoricalParams) (Loan, error) {
	row := q.db.QueryRow(ctx, recordHistorical,
		arg.ID,
		arg.DeviceID,
		arg.UserID,
		arg.Status,
		arg.Origin,
		arg.BorrowedAt,
		arg.ReturnedAt,
		arg.BorrowActor,
		arg.ReturnActor,
		arg.BorrowSource,
		arg.ReturnSource,
		arg.ConditionOut,
		arg.ConditionIn,
		arg.Notes,
		arg.PaperRef,
		arg.RecordedAt,
		arg.RecordedBy,
		arg.BackfillNote,
		arg.Disputed,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const streamLoansForExport = `-- name: StreamLoansForExport :many
SELECT
    l.id,
    l.device_id,
    d.asset_tag AS device_asset_tag,
    d.name AS device_name,
    l.user_id,
    u.employee_no AS user_employee_no,
    u.full_name AS user_full_name,
    l.status,
    l.origin,
    l.borrowed_at,
    l.due_at,
    l.returned_at,
    bk.name AS borrow_kiosk_name,
    rk.name AS return_kiosk_name,
    l.borrow_actor,
    l.return_actor,
    l.borrow_source,
    l.return_source,
    l.condition_out,
    l.condition_in,
    l.notes,
    l.paper_ref,
    l.recorded_at,
    l.recorded_by,
    l.backfill_note,
    l.disputed
FROM loans l
JOIN devices d ON l.device_id = d.id
JOIN users u ON l.user_id = u.id
LEFT JOIN kiosks bk ON l.borrow_kiosk_id = bk.id
LEFT JOIN kiosks rk ON l.return_kiosk_id = rk.id
WHERE ($1::loan_status IS NULL OR l.status = $1)
  AND ($2::loan_origin IS NULL OR l.origin = $2)
  AND ($3::uuid IS NULL OR l.user_id = $3)
  AND ($4::uuid IS NULL OR l.device_id = $4)
  AND ($5::boolean IS NULL OR l.disputed = $5)
  AND ($6::timestamptz IS NULL OR l.borrowed_at >= $6)
  AND ($7::timestamptz IS NULL OR l.borrowed_at <= $7)
ORDER BY l.borrowed_at DESC, l.id DESC
`

type StreamLoansForExportParams struct {
	Status   NullLoanStatus     `json:"status"`
	Origin   NullLoanOrigin     `json:"origin"`
	UserID   pgtype.UUID        `json:"user_id"`
	DeviceID pgtype.UUID        `json:"device_id"`
	Disputed pgtype.Bool        `json:"disputed"`
	FromAt   pgtype.Timestamptz `json:"from_at"`
	ToAt     pgtype.Timestamptz `json:"to_at"`
}

type StreamLoansForExportRow struct {
	ID              pgtype.UUID         `json:"id"`
	DeviceID        pgtype.UUID         `json:"device_id"`
	DeviceAssetTag  string              `json:"device_asset_tag"`
	DeviceName      string              `json:"device_name"`
	UserID          pgtype.UUID         `json:"user_id"`
	UserEmployeeNo  string              `json:"user_employee_no"`
	UserFullName    string              `json:"user_full_name"`
	Status          LoanStatus          `json:"status"`
	Origin          LoanOrigin          `json:"origin"`
	BorrowedAt      pgtype.Timestamptz  `json:"borrowed_at"`
	DueAt           pgtype.Timestamptz  `json:"due_at"`
	ReturnedAt      pgtype.Timestamptz  `json:"returned_at"`
	BorrowKioskName pgtype.Text         `json:"borrow_kiosk_name"`
	ReturnKioskName pgtype.Text         `json:"return_kiosk_name"`
	BorrowActor     string              `json:"borrow_actor"`
	ReturnActor     pgtype.Text         `json:"return_actor"`
	BorrowSource    string              `json:"borrow_source"`
	ReturnSource    pgtype.Text         `json:"return_source"`
	ConditionOut    NullDeviceCondition `json:"condition_out"`
	ConditionIn     NullDeviceCondition `json:"condition_in"`
	Notes           pgtype.Text         `json:"notes"`
	PaperRef        pgtype.Text         `json:"paper_ref"`
	RecordedAt      pgtype.Timestamptz  `json:"recorded_at"`
	RecordedBy      pgtype.Text         `json:"recorded_by"`
	BackfillNote    pgtype.Text         `json:"backfill_note"`
	Disputed        bool                `json:"disputed"`
}

func (q *Queries) StreamLoansForExport(ctx context.Context, arg StreamLoansForExportParams) ([]StreamLoansForExportRow, error) {
	rows, err := q.db.Query(ctx, streamLoansForExport,
		arg.Status,
		arg.Origin,
		arg.UserID,
		arg.DeviceID,
		arg.Disputed,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StreamLoansForExportRow
	for rows.Next() {
		var i StreamLoansForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.DeviceAssetTag,
			&i.DeviceName,
			&i.UserID,
			&i.UserEmployeeNo,
			&i.UserFullName,
			&i.Status,
			&i.Origin,
			&i.BorrowedAt,
			&i.DueAt,
			&i.ReturnedAt,
			&i.BorrowKioskName,
			&i.ReturnKioskName,
			&i.BorrowActor,
			&i.ReturnActor,
			&i.BorrowSource,
			&i.ReturnSource,
			&i.ConditionOut,
			&i.ConditionIn,
			&i.Notes,
			&i.PaperRef,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.BackfillNote,
			&i.Disputed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeOffLoan = `-- name: WriteOffLoan :one
UPDATE loans
SET status = 'written_off', returned_at = $2, return_actor = $3, return_source = 'manual', notes = $4
WHERE id = $1 AND status = 'open'
RETURNING id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
`

type WriteOffLoanParams struct {
	ID          pgtype.UUID        `json:"id"`
	ReturnedAt  pgtype.Timestamptz `json:"returned_at"`
	ReturnActor pgtype.Text        `json:"return_actor"`
	Notes       pgtype.Text        `json:"notes"`
}

// returned_at must be set even though the loan is written off, not
// returned: loans_status_matches_return only distinguishes 'open' from
// everything else, so any non-open status requires a non-null returned_at.
func (q *Queries) WriteOffLoan(ctx context.Context, arg WriteOffLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, writeOffLoan,
		arg.ID,
		arg.ReturnedAt,
		arg.ReturnActor,
		arg.Notes,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}
