// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lending.sql

package lendingstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeLoan = `-- name: CloseLoan :one
UPDATE loans
SET status = 'returned', returned_at = $2, return_kiosk_id = $3, return_actor = $4,
    return_source = $5, condition_in = $6
WHERE id = $1 AND status = 'open'
RETURNING id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
`

type CloseLoanParams struct {
	ID            pgtype.UUID         `json:"id"`
	ReturnedAt    pgtype.Timestamptz  `json:"returned_at"`
	ReturnKioskID pgtype.UUID         `json:"return_kiosk_id"`
	ReturnActor   pgtype.Text         `json:"return_actor"`
	ReturnSource  pgtype.Text         `json:"return_source"`
	ConditionIn   NullDeviceCondition `json:"condition_in"`
}

func (q *Queries) CloseLoan(ctx context.Context, arg CloseLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, closeLoan,
		arg.ID,
		arg.ReturnedAt,
		arg.ReturnKioskID,
		arg.ReturnActor,
		arg.ReturnSource,
		arg.ConditionIn,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const countOpenByDevice = `-- name: CountOpenByDevice :one
SELECT count(*) FROM loans WHERE device_id = $1 AND status = 'open'
`

func (q *Queries) CountOpenByDevice(ctx context.Context, deviceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenByDevice, deviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const custodyAt = `-- name: CustodyAt :one
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans
WHERE device_id = $1
  AND status <> 'written_off' AND NOT disputed
  AND tstzrange(borrowed_at, returned_at, '[)') @> $2::timestamptz
`

type CustodyAtParams struct {
	DeviceID pgtype.UUID        `json:"device_id"`
	At       pgtype.Timestamptz `json:"at"`
}

// The loan (open or covering) whose custody window contains `at`, ignoring
// written-off and disputed rows — what ResolveHistorical (2.4b) and the
// backfill conflict report both need.
func (q *Queries) CustodyAt(ctx context.Context, arg CustodyAtParams) (Loan, error) {
	row := q.db.QueryRow(ctx, custodyAt, arg.DeviceID, arg.At)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const forceReturnLoan = `-- name: ForceReturnLoan :one
UPDATE loans
SET status = 'returned', returned_at = $2, return_actor = $3, return_source = 'manual',
    condition_in = $4, notes = $5
WHERE id = $1 AND status = 'open'
RETURNING id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
`

type ForceReturnLoanParams struct {
	ID          pgtype.UUID         `json:"id"`
	ReturnedAt  pgtype.Timestamptz  `json:"returned_at"`
	ReturnActor pgtype.Text         `json:"return_actor"`
	ConditionIn NullDeviceCondition `json:"condition_in"`
	Notes       pgtype.Text         `json:"notes"`
}

func (q *Queries) ForceReturnLoan(ctx context.Context, arg ForceReturnLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, forceReturnLoan,
		arg.ID,
		arg.ReturnedAt,
		arg.ReturnActor,
		arg.ConditionIn,
		arg.Notes,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const getLoan = `-- name: GetLoan :one
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans WHERE id = $1
`

func (q *Queries) GetLoan(ctx context.Context, id pgtype.UUID) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoan, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const listLoans = `-- name: ListLoans :many
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans
WHERE ($1::loan_status IS NULL OR status = $1)
  AND ($2::loan_origin IS NULL OR origin = $2)
  AND ($3::uuid IS NULL OR user_id = $3)
  AND ($4::uuid IS NULL OR device_id = $4)
  AND ($5::timestamptz IS NULL OR borrowed_at >= $5)
  AND ($6::timestamptz IS NULL OR borrowed_at <= $6)
  AND (
    $7::timestamptz IS NULL
    OR borrowed_at < $7
    OR (borrowed_at = $7 AND id < $8)
  )
ORDER BY borrowed_at DESC, id DESC
LIMIT $9
`

type ListLoansParams struct {
	Status           NullLoanStatus     `json:"status"`
	Origin           NullLoanOrigin     `json:"origin"`
	UserID           pgtype.UUID        `json:"user_id"`
	DeviceID         pgtype.UUID        `json:"device_id"`
	FromAt           pgtype.Timestamptz `json:"from_at"`
	ToAt             pgtype.Timestamptz `json:"to_at"`
	CursorBorrowedAt pgtype.Timestamptz `json:"cursor_borrowed_at"`
	CursorID         pgtype.UUID        `json:"cursor_id"`
	ResultLimit      int32              `json:"result_limit"`
}

func (q *Queries) ListLoans(ctx context.Context, arg ListLoansParams) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoans,
		arg.Status,
		arg.Origin,
		arg.UserID,
		arg.DeviceID,
		arg.FromAt,
		arg.ToAt,
		arg.CursorBorrowedAt,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.UserID,
			&i.Status,
			&i.Origin,
			&i.BorrowedAt,
			&i.DueAt,
			&i.ReturnedAt,
			&i.BorrowKioskID,
			&i.ReturnKioskID,
			&i.BorrowActor,
			&i.ReturnActor,
			&i.BorrowSource,
			&i.ReturnSource,
			&i.ConditionOut,
			&i.ConditionIn,
			&i.Notes,
			&i.SessionID,
			&i.PaperRef,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.BackfillNote,
			&i.Disputed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openLoan = `-- name: OpenLoan :one
INSERT INTO loans (
    id, device_id, user_id, borrowed_at, due_at,
    borrow_kiosk_id, borrow_actor, borrow_source, condition_out, session_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
`

type OpenLoanParams struct {
	ID            pgtype.UUID         `json:"id"`
	DeviceID      pgtype.UUID         `json:"device_id"`
	UserID        pgtype.UUID         `json:"user_id"`
	BorrowedAt    pgtype.Timestamptz  `json:"borrowed_at"`
	DueAt         pgtype.Timestamptz  `json:"due_at"`
	BorrowKioskID pgtype.UUID         `json:"borrow_kiosk_id"`
	BorrowActor   string              `json:"borrow_actor"`
	BorrowSource  string              `json:"borrow_source"`
	ConditionOut  NullDeviceCondition `json:"condition_out"`
	SessionID     pgtype.UUID         `json:"session_id"`
}

// The live path: origin is always 'kiosk' — a loan opened here means a
// device was scanned right now, whether at a kiosk or overridden live by an
// admin. Genuinely backdated loans go through RecordHistorical instead.
func (q *Queries) OpenLoan(ctx context.Context, arg OpenLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, openLoan,
		arg.ID,
		arg.DeviceID,
		arg.UserID,
		arg.BorrowedAt,
		arg.DueAt,
		arg.BorrowKioskID,
		arg.BorrowActor,
		arg.BorrowSource,
		arg.ConditionOut,
		arg.SessionID,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const openLoanForDevice = `-- name: OpenLoanForDevice :one
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans WHERE device_id = $1 AND status = 'open'
`

func (q *Queries) OpenLoanForDevice(ctx context.Context, deviceID pgtype.UUID) (Loan, error) {
	row := q.db.QueryRow(ctx, openLoanForDevice, deviceID)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const openLoansForUser = `-- name: OpenLoansForUser :many
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans WHERE user_id = $1 AND status = 'open'
ORDER BY borrowed_at DESC
`

func (q *Queries) OpenLoansForUser(ctx context.Context, userID pgtype.UUID) ([]Loan, error) {
	rows, err := q.db.Query(ctx, openLoansForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.UserID,
			&i.Status,
			&i.Origin,
			&i.BorrowedAt,
			&i.DueAt,
			&i.ReturnedAt,
			&i.BorrowKioskID,
			&i.ReturnKioskID,
			&i.BorrowActor,
			&i.ReturnActor,
			&i.BorrowSource,
			&i.ReturnSource,
			&i.ConditionOut,
			&i.ConditionIn,
			&i.Notes,
			&i.SessionID,
			&i.PaperRef,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.BackfillNote,
			&i.Disputed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overdueLoans = `-- name: OverdueLoans :many
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans
WHERE status = 'open' AND due_at IS NOT NULL AND due_at < $1
ORDER BY due_at
`

func (q *Queries) OverdueLoans(ctx context.Context, dueAt pgtype.Timestamptz) ([]Loan, error) {
	rows, err := q.db.Query(ctx, overdueLoans, dueAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.UserID,
			&i.Status,
			&i.Origin,
			&i.BorrowedAt,
			&i.DueAt,
			&i.ReturnedAt,
			&i.BorrowKioskID,
			&i.ReturnKioskID,
			&i.BorrowActor,
			&i.ReturnActor,
			&i.BorrowSource,
			&i.ReturnSource,
			&i.ConditionOut,
			&i.ConditionIn,
			&i.Notes,
			&i.SessionID,
			&i.PaperRef,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.BackfillNote,
			&i.Disputed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overlappingLoan = `-- name: OverlappingLoan :one
SELECT id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
FROM loans
WHERE device_id = $1
  AND status <> 'written_off' AND NOT disputed
  AND tstzrange(borrowed_at, returned_at, '[)')
      && tstzrange($2::timestamptz, $3::timestamptz, '[)')
LIMIT 1
`

type OverlappingLoanParams struct {
	DeviceID   pgtype.UUID        `json:"device_id"`
	BorrowedAt pgtype.Timestamptz `json:"borrowed_at"`
	ReturnedAt pgtype.Timestamptz `json:"returned_at"`
}

// Re-read used only to populate OverlappingCustodyError.Existing after a
// loans_no_overlapping_custody violation: the specific row whose window
// intersects the range just rejected.
func (q *Queries) OverlappingLoan(ctx context.Context, arg OverlappingLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, overlappingLoan, arg.DeviceID, arg.BorrowedAt, arg.ReturnedAt)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const recordHistorical = `-- name: RecordHistorical :one
INSERT INTO loans (
    id, device_id, user_id, status, origin, borrowed_at, returned_at,
    borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes,
    paper_ref, recorded_at, recorded_by, backfill_note, disputed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17, $18, $19
)
RETURNING id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
`

type RecordHistoricalParams struct {
	ID           pgtype.UUID         `json:"id"`
	DeviceID     pgtype.UUID         `json:"device_id"`
	UserID       pgtype.UUID         `json:"user_id"`
	Status       LoanStatus          `json:"status"`
	Origin       LoanOrigin          `json:"origin"`
	BorrowedAt   pgtype.Timestamptz  `json:"borrowed_at"`
	ReturnedAt   pgtype.Timestamptz  `json:"returned_at"`
	BorrowActor  string              `json:"borrow_actor"`
	ReturnActor  pgtype.Text         `json:"return_actor"`
	BorrowSource string              `json:"borrow_source"`
	ReturnSource pgtype.Text         `json:"return_source"`
	ConditionOut NullDeviceCondition `json:"condition_out"`
	ConditionIn  NullDeviceCondition `json:"condition_in"`
	Notes        pgtype.Text         `json:"notes"`
	PaperRef     pgtype.Text         `json:"paper_ref"`
	RecordedAt   pgtype.Timestamptz  `json:"recorded_at"`
	RecordedBy   pgtype.Text         `json:"recorded_by"`
	BackfillNote pgtype.Text         `json:"backfill_note"`
	Disputed     bool                `json:"disputed"`
}

// The only insert path with an explicit, possibly past, borrowed_at and
// full paper/import provenance (2.4b).
func (q *Queries) RecordHistorical(ctx context.Context, arg RecordHistoricalParams) (Loan, error) {
	row := q.db.QueryRow(ctx, recordHistorical,
		arg.ID,
		arg.DeviceID,
		arg.UserID,
		arg.Status,
		arg.Origin,
		arg.BorrowedAt,
		arg.ReturnedAt,
		arg.BorrowActor,
		arg.ReturnActor,
		arg.BorrowSource,
		arg.ReturnSource,
		arg.ConditionOut,
		arg.ConditionIn,
		arg.Notes,
		arg.PaperRef,
		arg.RecordedAt,
		arg.RecordedBy,
		arg.BackfillNote,
		arg.Disputed,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}

const writeOffLoan = `-- name: WriteOffLoan :one
UPDATE loans
SET status = 'written_off', returned_at = $2, return_actor = $3, return_source = 'manual', notes = $4
WHERE id = $1 AND status = 'open'
RETURNING id, device_id, user_id, status, origin, borrowed_at, due_at, returned_at,
    borrow_kiosk_id, return_kiosk_id, borrow_actor, return_actor, borrow_source, return_source,
    condition_out, condition_in, notes, session_id, paper_ref, recorded_at, recorded_by,
    backfill_note, disputed
`

type WriteOffLoanParams struct {
	ID          pgtype.UUID        `json:"id"`
	ReturnedAt  pgtype.Timestamptz `json:"returned_at"`
	ReturnActor pgtype.Text        `json:"return_actor"`
	Notes       pgtype.Text        `json:"notes"`
}

// returned_at must be set even though the loan is written off, not
// returned: loans_status_matches_return only distinguishes 'open' from
// everything else, so any non-open status requires a non-null returned_at.
func (q *Queries) WriteOffLoan(ctx context.Context, arg WriteOffLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, writeOffLoan,
		arg.ID,
		arg.ReturnedAt,
		arg.ReturnActor,
		arg.Notes,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.UserID,
		&i.Status,
		&i.Origin,
		&i.BorrowedAt,
		&i.DueAt,
		&i.ReturnedAt,
		&i.BorrowKioskID,
		&i.ReturnKioskID,
		&i.BorrowActor,
		&i.ReturnActor,
		&i.BorrowSource,
		&i.ReturnSource,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.SessionID,
		&i.PaperRef,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.BackfillNote,
		&i.Disputed,
	)
	return i, err
}
