// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package lendingstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CloseLoan(ctx context.Context, arg CloseLoanParams) (Loan, error)
	CountOpenByDevice(ctx context.Context, deviceID pgtype.UUID) (int64, error)
	// The loan (open or covering) whose custody window contains `at`, ignoring
	// written-off and disputed rows — what ResolveHistorical (2.4b) and the
	// backfill conflict report both need.
	CustodyAt(ctx context.Context, arg CustodyAtParams) (Loan, error)
	ForceReturnLoan(ctx context.Context, arg ForceReturnLoanParams) (Loan, error)
	GetLoan(ctx context.Context, id pgtype.UUID) (Loan, error)
	ListLoans(ctx context.Context, arg ListLoansParams) ([]Loan, error)
	// The live path: origin is always 'kiosk' — a loan opened here means a
	// device was scanned right now, whether at a kiosk or overridden live by an
	// admin. Genuinely backdated loans go through RecordHistorical instead.
	OpenLoan(ctx context.Context, arg OpenLoanParams) (Loan, error)
	OpenLoanForDevice(ctx context.Context, deviceID pgtype.UUID) (Loan, error)
	OpenLoansForUser(ctx context.Context, userID pgtype.UUID) ([]Loan, error)
	OverdueLoans(ctx context.Context, dueAt pgtype.Timestamptz) ([]Loan, error)
	// Re-read used only to populate OverlappingCustodyError.Existing after a
	// loans_no_overlapping_custody violation: the specific row whose window
	// intersects the range just rejected.
	OverlappingLoan(ctx context.Context, arg OverlappingLoanParams) (Loan, error)
	// The only insert path with an explicit, possibly past, borrowed_at and
	// full paper/import provenance (2.4b).
	RecordHistorical(ctx context.Context, arg RecordHistoricalParams) (Loan, error)
	// returned_at must be set even though the loan is written off, not
	// returned: loans_status_matches_return only distinguishes 'open' from
	// everything else, so any non-open status requires a non-null returned_at.
	WriteOffLoan(ctx context.Context, arg WriteOffLoanParams) (Loan, error)
}

var _ Querier = (*Queries)(nil)
