// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package eventsstore

import (
	"context"
)

const claimUnpublishedBatch = `-- name: ClaimUnpublishedBatch :many
SELECT id, topic, payload, created_at, published_at
FROM outbox
WHERE published_at IS NULL
ORDER BY id
FOR UPDATE SKIP LOCKED
LIMIT $1
`

// FOR UPDATE SKIP LOCKED is what lets two dispatcher instances (two API
// replicas) poll concurrently without double-dispatching: a row already
// locked by one dispatcher's open transaction is simply skipped by the
// other's claim, not blocked on.
func (q *Queries) ClaimUnpublishedBatch(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, claimUnpublishedBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnpublished = `-- name: CountUnpublished :one
SELECT count(*) FROM outbox WHERE published_at IS NULL
`

func (q *Queries) CountUnpublished(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnpublished)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markPublished = `-- name: MarkPublished :exec
UPDATE outbox SET published_at = now() WHERE id = $1
`

func (q *Queries) MarkPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markPublished, id)
	return err
}

const publishEvent = `-- name: PublishEvent :exec
INSERT INTO outbox (topic, payload) VALUES ($1, $2)
`

type PublishEventParams struct {
	Topic   string `json:"topic"`
	Payload []byte `json:"payload"`
}

func (q *Queries) PublishEvent(ctx context.Context, arg PublishEventParams) error {
	_, err := q.db.Exec(ctx, publishEvent, arg.Topic, arg.Payload)
	return err
}

const sweepOldPublished = `-- name: SweepOldPublished :exec
DELETE FROM outbox WHERE published_at IS NOT NULL AND published_at < now() - interval '7 days'
`

func (q *Queries) SweepOldPublished(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sweepOldPublished)
	return err
}
