// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eventsstore

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminRole string

const (
	AdminRoleAdmin      AdminRole = "admin"
	AdminRoleTechnician AdminRole = "technician"
	AdminRoleViewer     AdminRole = "viewer"
)

func (e *AdminRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminRole(s)
	case string:
		*e = AdminRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminRole: %T", src)
	}
	return nil
}

type NullAdminRole struct {
	AdminRole AdminRole `json:"admin_role"`
	Valid     bool      `json:"valid"` // Valid is true if AdminRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminRole) Scan(value interface{}) error {
	if value == nil {
		ns.AdminRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminRole), nil
}

type AdminStatus string

const (
	AdminStatusActive   AdminStatus = "active"
	AdminStatusDisabled AdminStatus = "disabled"
)

func (e *AdminStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminStatus(s)
	case string:
		*e = AdminStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminStatus: %T", src)
	}
	return nil
}

type NullAdminStatus struct {
	AdminStatus AdminStatus `json:"admin_status"`
	Valid       bool        `json:"valid"` // Valid is true if AdminStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AdminStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminStatus), nil
}

type CredentialKind string

const (
	CredentialKindQr      CredentialKind = "qr"
	CredentialKindCode128 CredentialKind = "code128"
	CredentialKindNfc     CredentialKind = "nfc"
	CredentialKindRfid    CredentialKind = "rfid"
	CredentialKindManual  CredentialKind = "manual"
)

func (e *CredentialKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CredentialKind(s)
	case string:
		*e = CredentialKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CredentialKind: %T", src)
	}
	return nil
}

type NullCredentialKind struct {
	CredentialKind CredentialKind `json:"credential_kind"`
	Valid          bool           `json:"valid"` // Valid is true if CredentialKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCredentialKind) Scan(value interface{}) error {
	if value == nil {
		ns.CredentialKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CredentialKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCredentialKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CredentialKind), nil
}

type CredentialStatus string

const (
	CredentialStatusActive  CredentialStatus = "active"
	CredentialStatusRevoked CredentialStatus = "revoked"
	CredentialStatusLost    CredentialStatus = "lost"
)

func (e *CredentialStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CredentialStatus(s)
	case string:
		*e = CredentialStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CredentialStatus: %T", src)
	}
	return nil
}

type NullCredentialStatus struct {
	CredentialStatus CredentialStatus `json:"credential_status"`
	Valid            bool             `json:"valid"` // Valid is true if CredentialStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCredentialStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CredentialStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CredentialStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCredentialStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CredentialStatus), nil
}

type DeviceCondition string

const (
	DeviceConditionGood    DeviceCondition = "good"
	DeviceConditionFair    DeviceCondition = "fair"
	DeviceConditionDamaged DeviceCondition = "damaged"
)

func (e *DeviceCondition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceCondition(s)
	case string:
		*e = DeviceCondition(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceCondition: %T", src)
	}
	return nil
}

type NullDeviceCondition struct {
	DeviceCondition DeviceCondition `json:"device_condition"`
	Valid           bool            `json:"valid"` // Valid is true if DeviceCondition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceCondition) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceCondition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceCondition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceCondition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceCondition), nil
}

type DeviceStatus string

const (
	DeviceStatusAvailable   DeviceStatus = "available"
	DeviceStatusOnLoan      DeviceStatus = "on_loan"
	DeviceStatusMaintenance DeviceStatus = "maintenance"
	DeviceStatusRetired     DeviceStatus = "retired"
	DeviceStatusLost        DeviceStatus = "lost"
)

func (e *DeviceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceStatus(s)
	case string:
		*e = DeviceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceStatus: %T", src)
	}
	return nil
}

type NullDeviceStatus struct {
	DeviceStatus DeviceStatus `json:"device_status"`
	Valid        bool         `json:"valid"` // Valid is true if DeviceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceStatus), nil
}

type KioskStatus string

const (
	KioskStatusActive   KioskStatus = "active"
	KioskStatusDisabled KioskStatus = "disabled"
)

func (e *KioskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KioskStatus(s)
	case string:
		*e = KioskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for KioskStatus: %T", src)
	}
	return nil
}

type NullKioskStatus struct {
	KioskStatus KioskStatus `json:"kiosk_status"`
	Valid       bool        `json:"valid"` // Valid is true if KioskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKioskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.KioskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KioskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKioskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KioskStatus), nil
}

type LoanOrigin string

const (
	LoanOriginKiosk  LoanOrigin = "kiosk"
	LoanOriginAdmin  LoanOrigin = "admin"
	LoanOriginPaper  LoanOrigin = "paper"
	LoanOriginImport LoanOrigin = "import"
)

func (e *LoanOrigin) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoanOrigin(s)
	case string:
		*e = LoanOrigin(s)
	default:
		return fmt.Errorf("unsupported scan type for LoanOrigin: %T", src)
	}
	return nil
}

type NullLoanOrigin struct {
	LoanOrigin LoanOrigin `json:"loan_origin"`
	Valid      bool       `json:"valid"` // Valid is true if LoanOrigin is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoanOrigin) Scan(value interface{}) error {
	if value == nil {
		ns.LoanOrigin, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoanOrigin.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoanOrigin) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoanOrigin), nil
}

type LoanStatus string

const (
	LoanStatusOpen       LoanStatus = "open"
	LoanStatusReturned   LoanStatus = "returned"
	LoanStatusWrittenOff LoanStatus = "written_off"
)

func (e *LoanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoanStatus(s)
	case string:
		*e = LoanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LoanStatus: %T", src)
	}
	return nil
}

type NullLoanStatus struct {
	LoanStatus LoanStatus `json:"loan_status"`
	Valid      bool       `json:"valid"` // Valid is true if LoanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LoanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoanStatus), nil
}

type ReservationStatus string

const (
	ReservationStatusActive    ReservationStatus = "active"
	ReservationStatusCollected ReservationStatus = "collected"
	ReservationStatusCancelled ReservationStatus = "cancelled"
	ReservationStatusExpired   ReservationStatus = "expired"
)

func (e *ReservationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReservationStatus(s)
	case string:
		*e = ReservationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReservationStatus: %T", src)
	}
	return nil
}

type NullReservationStatus struct {
	ReservationStatus ReservationStatus `json:"reservation_status"`
	Valid             bool              `json:"valid"` // Valid is true if ReservationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReservationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReservationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReservationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReservationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReservationStatus), nil
}

type SessionState string

const (
	SessionStateIdle           SessionState = "idle"
	SessionStateAwaitingUser   SessionState = "awaiting_user"
	SessionStateAwaitingDevice SessionState = "awaiting_device"
	SessionStateReady          SessionState = "ready"
	SessionStateCompleted      SessionState = "completed"
	SessionStateExpired        SessionState = "expired"
	SessionStateCancelled      SessionState = "cancelled"
)

func (e *SessionState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionState(s)
	case string:
		*e = SessionState(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionState: %T", src)
	}
	return nil
}

type NullSessionState struct {
	SessionState SessionState `json:"session_state"`
	Valid        bool         `json:"valid"` // Valid is true if SessionState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionState) Scan(value interface{}) error {
	if value == nil {
		ns.SessionState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionState), nil
}

type SubjectType string

const (
	SubjectTypeUser   SubjectType = "user"
	SubjectTypeDevice SubjectType = "device"
)

func (e *SubjectType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubjectType(s)
	case string:
		*e = SubjectType(s)
	default:
		return fmt.Errorf("unsupported scan type for SubjectType: %T", src)
	}
	return nil
}

type NullSubjectType struct {
	SubjectType SubjectType `json:"subject_type"`
	Valid       bool        `json:"valid"` // Valid is true if SubjectType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubjectType) Scan(value interface{}) error {
	if value == nil {
		ns.SubjectType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubjectType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubjectType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubjectType), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusArchived  UserStatus = "archived"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AdminAccount struct {
	ID                   pgtype.UUID        `json:"id"`
	Email                string             `json:"email"`
	FullName             string             `json:"full_name"`
	PasswordHash         string             `json:"password_hash"`
	TotpSecretEnc        []byte             `json:"totp_secret_enc"`
	Role                 AdminRole          `json:"role"`
	Status               AdminStatus        `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	FailedAttempts       int32              `json:"failed_attempts"`
	LastFailureAt        pgtype.Timestamptz `json:"last_failure_at"`
	LockedUntil          pgtype.Timestamptz `json:"locked_until"`
	MustChangePassword   bool               `json:"must_change_password"`
	MustReenrolTotp      bool               `json:"must_reenrol_totp"`
	LastLoginAt          pgtype.Timestamptz `json:"last_login_at"`
	TotpPendingSecretEnc []byte             `json:"totp_pending_secret_enc"`
	Locale               string             `json:"locale"`
}

type AdminRecoveryCode struct {
	ID        pgtype.UUID        `json:"id"`
	AdminID   pgtype.UUID        `json:"admin_id"`
	CodeHash  string             `json:"code_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type AdminSession struct {
	ID               pgtype.UUID        `json:"id"`
	AdminID          pgtype.UUID        `json:"admin_id"`
	SessionTokenHash []byte             `json:"session_token_hash"`
	CsrfToken        string             `json:"csrf_token"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type AuditEvent struct {
	ID        pgtype.UUID        `json:"id"`
	At        pgtype.Timestamptz `json:"at"`
	Actor     string             `json:"actor"`
	ActorIp   *netip.Addr        `json:"actor_ip"`
	Action    string             `json:"action"`
	Subject   string             `json:"subject"`
	Payload   []byte             `json:"payload"`
	RequestID pgtype.Text        `json:"request_id"`
}

type BackupDestination struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Kind              string             `json:"kind"`
	Target            string             `json:"target"`
	Provider          string             `json:"provider"`
	Enabled           bool               `json:"enabled"`
	RetentionVersions int32              `json:"retention_versions"`
	InitializedAt     pgtype.Timestamptz `json:"initialized_at"`
	LastOkAt          pgtype.Timestamptz `json:"last_ok_at"`
	LastError         pgtype.Text        `json:"last_error"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         string             `json:"updated_by"`
}

type Credential struct {
	ID            pgtype.UUID        `json:"id"`
	SubjectType   SubjectType        `json:"subject_type"`
	SubjectID     pgtype.UUID        `json:"subject_id"`
	Kind          CredentialKind     `json:"kind"`
	TokenHash     []byte             `json:"token_hash"`
	TokenPreview  string             `json:"token_preview"`
	TokenEnc      []byte             `json:"token_enc"`
	Label         pgtype.Text        `json:"label"`
	Status        CredentialStatus   `json:"status"`
	IssueSeq      int32              `json:"issue_seq"`
	ReplacesID    pgtype.UUID        `json:"replaces_id"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	IssuedBy      string             `json:"issued_by"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedBy     pgtype.Text        `json:"revoked_by"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
	PrintedCount  int32              `json:"printed_count"`
	LastPrintedAt pgtype.Timestamptz `json:"last_printed_at"`
}

type CredentialEvent struct {
	ID           pgtype.UUID        `json:"id"`
	CredentialID pgtype.UUID        `json:"credential_id"`
	At           pgtype.Timestamptz `json:"at"`
	Kind         string             `json:"kind"`
	Actor        string             `json:"actor"`
	Reason       pgtype.Text        `json:"reason"`
	Payload      []byte             `json:"payload"`
}

type DeliveryLog struct {
	ID             pgtype.UUID        `json:"id"`
	Recipient      string             `json:"recipient"`
	Channel        string             `json:"channel"`
	Template       string             `json:"template"`
	DedupeKey      string             `json:"dedupe_key"`
	AttemptCount   int32              `json:"attempt_count"`
	Status         string             `json:"status"`
	LastError      pgtype.Text        `json:"last_error"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LoanID         pgtype.UUID        `json:"loan_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	EscalationStep pgtype.Int4        `json:"escalation_step"`
	Payload        []byte             `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Department struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID           pgtype.UUID        `json:"id"`
	AssetTag     string             `json:"asset_tag"`
	Name         string             `json:"name"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Manufacturer pgtype.Text        `json:"manufacturer"`
	Model        pgtype.Text        `json:"model"`
	SerialNo     pgtype.Text        `json:"serial_no"`
	Status       DeviceStatus       `json:"status"`
	Condition    DeviceCondition    `json:"condition"`
	HomeLocation pgtype.Text        `json:"home_location"`
	Notes        pgtype.Text        `json:"notes"`
	AcquiredOn   pgtype.Date        `json:"acquired_on"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DeviceCategory struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	DefaultLoanPeriod pgtype.Interval    `json:"default_loan_period"`
	RequiresApproval  bool               `json:"requires_approval"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyKey struct {
	Key          string             `json:"key"`
	Actor        string             `json:"actor"`
	RequestHash  []byte             `json:"request_hash"`
	StatusCode   pgtype.Int4        `json:"status_code"`
	ResponseBody []byte             `json:"response_body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type ImportBatch struct {
	ID           string             `json:"id"`
	Kind         string             `json:"kind"`
	Actor        string             `json:"actor"`
	Filename     string             `json:"filename"`
	TotalRows    int32              `json:"total_rows"`
	CreatedCount int32              `json:"created_count"`
	UpdatedCount int32              `json:"updated_count"`
	SkippedCount int32              `json:"skipped_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type JobRun struct {
	ID         int64              `json:"id"`
	Job        string             `json:"job"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Outcome    string             `json:"outcome"`
	Detail     []byte             `json:"detail"`
}

type Kiosk struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Location             pgtype.Text        `json:"location"`
	TokenHash            []byte             `json:"token_hash"`
	EnabledSources       []string           `json:"enabled_sources"`
	Status               KioskStatus        `json:"status"`
	LastSeenAt           pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	PairingCodeHash      []byte             `json:"pairing_code_hash"`
	PairingCodeExpiresAt pgtype.Timestamptz `json:"pairing_code_expires_at"`
	DefaultLocale        string             `json:"default_locale"`
}

type Loan struct {
	ID            pgtype.UUID         `json:"id"`
	DeviceID      pgtype.UUID         `json:"device_id"`
	UserID        pgtype.UUID         `json:"user_id"`
	Status        LoanStatus          `json:"status"`
	Origin        LoanOrigin          `json:"origin"`
	BorrowedAt    pgtype.Timestamptz  `json:"borrowed_at"`
	DueAt         pgtype.Timestamptz  `json:"due_at"`
	ReturnedAt    pgtype.Timestamptz  `json:"returned_at"`
	BorrowKioskID pgtype.UUID         `json:"borrow_kiosk_id"`
	ReturnKioskID pgtype.UUID         `json:"return_kiosk_id"`
	BorrowActor   string              `json:"borrow_actor"`
	ReturnActor   pgtype.Text         `json:"return_actor"`
	BorrowSource  string              `json:"borrow_source"`
	ReturnSource  pgtype.Text         `json:"return_source"`
	ConditionOut  NullDeviceCondition `json:"condition_out"`
	ConditionIn   NullDeviceCondition `json:"condition_in"`
	Notes         pgtype.Text         `json:"notes"`
	SessionID     pgtype.UUID         `json:"session_id"`
	PaperRef      pgtype.Text         `json:"paper_ref"`
	RecordedAt    pgtype.Timestamptz  `json:"recorded_at"`
	RecordedBy    pgtype.Text         `json:"recorded_by"`
	BackfillNote  pgtype.Text         `json:"backfill_note"`
	Disputed      bool                `json:"disputed"`
}

type NotificationPreference struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Channel   string             `json:"channel"`
	OptedOut  bool               `json:"opted_out"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy string             `json:"updated_by"`
}

type OauthLoginState struct {
	StateHash   []byte             `json:"state_hash"`
	VerifierEnc []byte             `json:"verifier_enc"`
	RedirectTo  pgtype.Text        `json:"redirect_to"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
}

type Outbox struct {
	ID            int64              `json:"id"`
	Topic         string             `json:"topic"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
	FailedAt      pgtype.Timestamptz `json:"failed_at"`
}

type OverdueEscalation struct {
	LoanID         pgtype.UUID        `json:"loan_id"`
	EscalationStep int32              `json:"escalation_step"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
}

type Reservation struct {
	ID                 pgtype.UUID        `json:"id"`
	DeviceID           pgtype.UUID        `json:"device_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	Status             ReservationStatus  `json:"status"`
	StartAt            pgtype.Timestamptz `json:"start_at"`
	EndAt              pgtype.Timestamptz `json:"end_at"`
	CreatedBy          string             `json:"created_by"`
	CreatedSource      string             `json:"created_source"`
	LoanID             pgtype.UUID        `json:"loan_id"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy        pgtype.Text        `json:"cancelled_by"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ScanEvent struct {
	ID           pgtype.UUID        `json:"id"`
	SessionID    pgtype.UUID        `json:"session_id"`
	At           pgtype.Timestamptz `json:"at"`
	Source       string             `json:"source"`
	TokenPreview string             `json:"token_preview"`
	ResolvedType pgtype.Text        `json:"resolved_type"`
	ResolvedID   pgtype.UUID        `json:"resolved_id"`
	Result       string             `json:"result"`
	Reason       pgtype.Text        `json:"reason"`
}

type ScanSession struct {
	ID            pgtype.UUID        `json:"id"`
	KioskID       pgtype.UUID        `json:"kiosk_id"`
	State         SessionState       `json:"state"`
	UserID        pgtype.UUID        `json:"user_id"`
	PendingDevice pgtype.UUID        `json:"pending_device"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	LastActivity  pgtype.Timestamptz `json:"last_activity"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ClosedAt      pgtype.Timestamptz `json:"closed_at"`
	Outcome       pgtype.Text        `json:"outcome"`
	LastTokenHash []byte             `json:"last_token_hash"`
	LastScanAt    pgtype.Timestamptz `json:"last_scan_at"`
}

type Setting struct {
	ID                            int32              `json:"id"`
	BlockOnOverdue                bool               `json:"block_on_overdue"`
	SessionIdleTimeoutSeconds     int32              `json:"session_idle_timeout_seconds"`
	KioskSoundEnabled             bool               `json:"kiosk_sound_enabled"`
	LowStockThreshold             int32              `json:"low_stock_threshold"`
	PaperBacklogHours             int32              `json:"paper_backlog_hours"`
	SheetWidthMm                  float64            `json:"sheet_width_mm"`
	SheetHeightMm                 float64            `json:"sheet_height_mm"`
	LabelColumns                  int32              `json:"label_columns"`
	LabelRows                     int32              `json:"label_rows"`
	MarginTopMm                   float64            `json:"margin_top_mm"`
	MarginLeftMm                  float64            `json:"margin_left_mm"`
	GutterXMm                     float64            `json:"gutter_x_mm"`
	GutterYMm                     float64            `json:"gutter_y_mm"`
	LabelWidthMm                  float64            `json:"label_width_mm"`
	LabelHeightMm                 float64            `json:"label_height_mm"`
	HospitalName                  string             `json:"hospital_name"`
	PageRefFormat                 string             `json:"page_ref_format"`
	SlipRowsPerPage               int32              `json:"slip_rows_per_page"`
	SlipColumns                   []string           `json:"slip_columns"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy                     string             `json:"updated_by"`
	ReservationPreWindowMinutes   int32              `json:"reservation_pre_window_minutes"`
	ReservationExpiryGraceMinutes int32              `json:"reservation_expiry_grace_minutes"`
}

type StaffAccount struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	PasswordHash       pgtype.Text        `json:"password_hash"`
	MustChangePassword bool               `json:"must_change_password"`
	ProfileComplete    bool               `json:"profile_complete"`
	FailedAttempts     int32              `json:"failed_attempts"`
	LastFailureAt      pgtype.Timestamptz `json:"last_failure_at"`
	LockedUntil        pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedBy          string             `json:"created_by"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type StaffIdentity struct {
	ID             pgtype.UUID        `json:"id"`
	StaffAccountID pgtype.UUID        `json:"staff_account_id"`
	Provider       string             `json:"provider"`
	Subject        string             `json:"subject"`
	TenantID       string             `json:"tenant_id"`
	EmailAtLink    pgtype.Text        `json:"email_at_link"`
	LinkedAt       pgtype.Timestamptz `json:"linked_at"`
}

type StaffSession struct {
	ID               pgtype.UUID        `json:"id"`
	StaffAccountID   pgtype.UUID        `json:"staff_account_id"`
	SessionTokenHash []byte             `json:"session_token_hash"`
	CsrfToken        string             `json:"csrf_token"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	EmployeeNo    string             `json:"employee_no"`
	FullName      string             `json:"full_name"`
	DepartmentID  pgtype.UUID        `json:"department_id"`
	Email         pgtype.Text        `json:"email"`
	Phone         pgtype.Text        `json:"phone"`
	Status        UserStatus         `json:"status"`
	Notes         pgtype.Text        `json:"notes"`
	RegisteredAt  pgtype.Timestamptz `json:"registered_at"`
	RegisteredBy  string             `json:"registered_by"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ImportBatchID pgtype.Text        `json:"import_batch_id"`
}

type UserDirectoryLink struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Issuer              string             `json:"issuer"`
	Subject             string             `json:"subject"`
	LastSeenInDirectory pgtype.Timestamptz `json:"last_seen_in_directory"`
	SyncState           string             `json:"sync_state"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
