// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package eventsstore

import (
	"context"
)

type Querier interface {
	// FOR UPDATE SKIP LOCKED is what lets two dispatcher instances (two API
	// replicas) poll concurrently without double-dispatching: a row already
	// locked by one dispatcher's open transaction is simply skipped by the
	// other's claim, not blocked on.
	ClaimUnpublishedBatch(ctx context.Context, limit int32) ([]Outbox, error)
	CountUnpublished(ctx context.Context) (int64, error)
	MarkPublished(ctx context.Context, id int64) error
	PublishEvent(ctx context.Context, arg PublishEventParams) error
	SweepOldPublished(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
