// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package staffauthstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ConsumeLoginState(ctx context.Context, stateHash []byte) (OauthLoginState, error)
	CreateLoginState(ctx context.Context, arg CreateLoginStateParams) error
	CreateStaffAccount(ctx context.Context, arg CreateStaffAccountParams) (StaffAccount, error)
	CreateStaffSession(ctx context.Context, arg CreateStaffSessionParams) (StaffSession, error)
	DeleteExpiredLoginStates(ctx context.Context) error
	DeleteExpiredStaffSessions(ctx context.Context) error
	DeleteStaffSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) error
	DeleteStaffSessionsForAccount(ctx context.Context, staffAccountID pgtype.UUID) error
	GetStaffAccountByID(ctx context.Context, id pgtype.UUID) (StaffAccount, error)
	GetStaffAccountByUserID(ctx context.Context, userID pgtype.UUID) (StaffAccount, error)
	GetStaffIdentity(ctx context.Context, arg GetStaffIdentityParams) (StaffIdentity, error)
	GetStaffSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) (StaffSession, error)
	LinkStaffIdentity(ctx context.Context, arg LinkStaffIdentityParams) (StaffIdentity, error)
	MarkStaffProfileComplete(ctx context.Context, id pgtype.UUID) (StaffAccount, error)
	RecordStaffLoginFailure(ctx context.Context, arg RecordStaffLoginFailureParams) (StaffAccount, error)
	RecordStaffLoginSuccess(ctx context.Context, id pgtype.UUID) error
	SetStaffPassword(ctx context.Context, arg SetStaffPasswordParams) (StaffAccount, error)
	SlideStaffSession(ctx context.Context, arg SlideStaffSessionParams) error
}

var _ Querier = (*Queries)(nil)
