// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staffauth.sql

package staffauthstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeLoginState = `-- name: ConsumeLoginState :one
UPDATE oauth_login_states SET consumed_at = now()
WHERE state_hash = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING state_hash, verifier_enc, redirect_to, created_at, expires_at, consumed_at
`

func (q *Queries) ConsumeLoginState(ctx context.Context, stateHash []byte) (OauthLoginState, error) {
	row := q.db.QueryRow(ctx, consumeLoginState, stateHash)
	var i OauthLoginState
	err := row.Scan(
		&i.StateHash,
		&i.VerifierEnc,
		&i.RedirectTo,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createLoginState = `-- name: CreateLoginState :exec
INSERT INTO oauth_login_states (state_hash, verifier_enc, redirect_to, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateLoginStateParams struct {
	StateHash   []byte             `json:"state_hash"`
	VerifierEnc []byte             `json:"verifier_enc"`
	RedirectTo  pgtype.Text        `json:"redirect_to"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateLoginState(ctx context.Context, arg CreateLoginStateParams) error {
	_, err := q.db.Exec(ctx, createLoginState,
		arg.StateHash,
		arg.VerifierEnc,
		arg.RedirectTo,
		arg.ExpiresAt,
	)
	return err
}

const createStaffAccount = `-- name: CreateStaffAccount :one
INSERT INTO staff_accounts (id, user_id, password_hash, must_change_password, profile_complete, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, password_hash, must_change_password, profile_complete, failed_attempts, last_failure_at, locked_until, last_login_at, created_at, created_by, updated_at
`

type CreateStaffAccountParams struct {
	ID                 pgtype.UUID `json:"id"`
	UserID             pgtype.UUID `json:"user_id"`
	PasswordHash       pgtype.Text `json:"password_hash"`
	MustChangePassword bool        `json:"must_change_password"`
	ProfileComplete    bool        `json:"profile_complete"`
	CreatedBy          string      `json:"created_by"`
}

func (q *Queries) CreateStaffAccount(ctx context.Context, arg CreateStaffAccountParams) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, createStaffAccount,
		arg.ID,
		arg.UserID,
		arg.PasswordHash,
		arg.MustChangePassword,
		arg.ProfileComplete,
		arg.CreatedBy,
	)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.ProfileComplete,
		&i.FailedAttempts,
		&i.LastFailureAt,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createStaffSession = `-- name: CreateStaffSession :one
INSERT INTO staff_sessions (id, staff_account_id, session_token_hash, csrf_token, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, staff_account_id, session_token_hash, csrf_token, created_at, last_seen_at, expires_at
`

type CreateStaffSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	StaffAccountID   pgtype.UUID        `json:"staff_account_id"`
	SessionTokenHash []byte             `json:"session_token_hash"`
	CsrfToken        string             `json:"csrf_token"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateStaffSession(ctx context.Context, arg CreateStaffSessionParams) (StaffSession, error) {
	row := q.db.QueryRow(ctx, createStaffSession,
		arg.ID,
		arg.StaffAccountID,
		arg.SessionTokenHash,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	var i StaffSession
	err := row.Scan(
		&i.ID,
		&i.StaffAccountID,
		&i.SessionTokenHash,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredLoginStates = `-- name: DeleteExpiredLoginStates :exec
DELETE FROM oauth_login_states WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredLoginStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredLoginStates)
	return err
}

const deleteExpiredStaffSessions = `-- name: DeleteExpiredStaffSessions :exec
DELETE FROM staff_sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredStaffSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredStaffSessions)
	return err
}

const deleteStaffSessionByTokenHash = `-- name: DeleteStaffSessionByTokenHash :exec
DELETE FROM staff_sessions WHERE session_token_hash = $1
`

func (q *Queries) DeleteStaffSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteStaffSessionByTokenHash, sessionTokenHash)
	return err
}

const deleteStaffSessionsForAccount = `-- name: DeleteStaffSessionsForAccount :exec
DELETE FROM staff_sessions WHERE staff_account_id = $1
`

func (q *Queries) DeleteStaffSessionsForAccount(ctx context.Context, staffAccountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStaffSessionsForAccount, staffAccountID)
	return err
}

const getStaffAccountByID = `-- name: GetStaffAccountByID :one
SELECT id, user_id, password_hash, must_change_password, profile_complete, failed_attempts, last_failure_at, locked_until, last_login_at, created_at, created_by, updated_at FROM staff_accounts WHERE id = $1
`

func (q *Queries) GetStaffAccountByID(ctx context.Context, id pgtype.UUID) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, getStaffAccountByID, id)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.ProfileComplete,
		&i.FailedAttempts,
		&i.LastFailureAt,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffAccountByUserID = `-- name: GetStaffAccountByUserID :one
SELECT id, user_id, password_hash, must_change_password, profile_complete, failed_attempts, last_failure_at, locked_until, last_login_at, created_at, created_by, updated_at FROM staff_accounts WHERE user_id = $1
`

func (q *Queries) GetStaffAccountByUserID(ctx context.Context, userID pgtype.UUID) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, getStaffAccountByUserID, userID)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.ProfileComplete,
		&i.FailedAttempts,
		&i.LastFailureAt,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffIdentity = `-- name: GetStaffIdentity :one
SELECT id, staff_account_id, provider, subject, tenant_id, email_at_link, linked_at FROM staff_identities WHERE provider = $1 AND subject = $2
`

type GetStaffIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetStaffIdentity(ctx context.Context, arg GetStaffIdentityParams) (StaffIdentity, error) {
	row := q.db.QueryRow(ctx, getStaffIdentity, arg.Provider, arg.Subject)
	var i StaffIdentity
	err := row.Scan(
		&i.ID,
		&i.StaffAccountID,
		&i.Provider,
		&i.Subject,
		&i.TenantID,
		&i.EmailAtLink,
		&i.LinkedAt,
	)
	return i, err
}

const getStaffSessionByTokenHash = `-- name: GetStaffSessionByTokenHash :one
SELECT id, staff_account_id, session_token_hash, csrf_token, created_at, last_seen_at, expires_at FROM staff_sessions WHERE session_token_hash = $1
`

func (q *Queries) GetStaffSessionByTokenHash(ctx context.Context, sessionTokenHash []byte) (StaffSession, error) {
	row := q.db.QueryRow(ctx, getStaffSessionByTokenHash, sessionTokenHash)
	var i StaffSession
	err := row.Scan(
		&i.ID,
		&i.StaffAccountID,
		&i.SessionTokenHash,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const linkStaffIdentity = `-- name: LinkStaffIdentity :one
INSERT INTO staff_identities (id, staff_account_id, provider, subject, tenant_id, email_at_link)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, staff_account_id, provider, subject, tenant_id, email_at_link, linked_at
`

type LinkStaffIdentityParams struct {
	ID             pgtype.UUID `json:"id"`
	StaffAccountID pgtype.UUID `json:"staff_account_id"`
	Provider       string      `json:"provider"`
	Subject        string      `json:"subject"`
	TenantID       string      `json:"tenant_id"`
	EmailAtLink    pgtype.Text `json:"email_at_link"`
}

func (q *Queries) LinkStaffIdentity(ctx context.Context, arg LinkStaffIdentityParams) (StaffIdentity, error) {
	row := q.db.QueryRow(ctx, linkStaffIdentity,
		arg.ID,
		arg.StaffAccountID,
		arg.Provider,
		arg.Subject,
		arg.TenantID,
		arg.EmailAtLink,
	)
	var i StaffIdentity
	err := row.Scan(
		&i.ID,
		&i.StaffAccountID,
		&i.Provider,
		&i.Subject,
		&i.TenantID,
		&i.EmailAtLink,
		&i.LinkedAt,
	)
	return i, err
}

const listStaffIdentitiesForAccount = `-- name: ListStaffIdentitiesForAccount :many
SELECT id, staff_account_id, provider, subject, tenant_id, email_at_link, linked_at FROM staff_identities WHERE staff_account_id = $1
`

func (q *Queries) ListStaffIdentitiesForAccount(ctx context.Context, staffAccountID pgtype.UUID) ([]StaffIdentity, error) {
	rows, err := q.db.Query(ctx, listStaffIdentitiesForAccount, staffAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffIdentity
	for rows.Next() {
		var i StaffIdentity
		if err := rows.Scan(
			&i.ID,
			&i.StaffAccountID,
			&i.Provider,
			&i.Subject,
			&i.TenantID,
			&i.EmailAtLink,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaffProfileComplete = `-- name: MarkStaffProfileComplete :one
UPDATE staff_accounts SET profile_complete = true, updated_at = now()
WHERE id = $1
RETURNING id, user_id, password_hash, must_change_password, profile_complete, failed_attempts, last_failure_at, locked_until, last_login_at, created_at, created_by, updated_at
`

func (q *Queries) MarkStaffProfileComplete(ctx context.Context, id pgtype.UUID) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, markStaffProfileComplete, id)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.ProfileComplete,
		&i.FailedAttempts,
		&i.LastFailureAt,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const recordStaffLoginFailure = `-- name: RecordStaffLoginFailure :one
UPDATE staff_accounts
SET failed_attempts = failed_attempts + 1,
    last_failure_at = now(),
    locked_until = CASE WHEN failed_attempts + 1 >= $2 THEN now() + $3::interval ELSE locked_until END,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, password_hash, must_change_password, profile_complete, failed_attempts, last_failure_at, locked_until, last_login_at, created_at, created_by, updated_at
`

type RecordStaffLoginFailureParams struct {
	ID             pgtype.UUID     `json:"id"`
	FailedAttempts int32           `json:"failed_attempts"`
	Column3        pgtype.Interval `json:"column_3"`
}

func (q *Queries) RecordStaffLoginFailure(ctx context.Context, arg RecordStaffLoginFailureParams) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, recordStaffLoginFailure, arg.ID, arg.FailedAttempts, arg.Column3)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.ProfileComplete,
		&i.FailedAttempts,
		&i.LastFailureAt,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const recordStaffLoginSuccess = `-- name: RecordStaffLoginSuccess :exec
UPDATE staff_accounts
SET failed_attempts = 0, locked_until = NULL, last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) RecordStaffLoginSuccess(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordStaffLoginSuccess, id)
	return err
}

const setStaffPassword = `-- name: SetStaffPassword :one
UPDATE staff_accounts
SET password_hash = $2, must_change_password = $3, failed_attempts = 0,
    locked_until = NULL, updated_at = now()
WHERE id = $1
RETURNING id, user_id, password_hash, must_change_password, profile_complete, failed_attempts, last_failure_at, locked_until, last_login_at, created_at, created_by, updated_at
`

type SetStaffPasswordParams struct {
	ID                 pgtype.UUID `json:"id"`
	PasswordHash       pgtype.Text `json:"password_hash"`
	MustChangePassword bool        `json:"must_change_password"`
}

func (q *Queries) SetStaffPassword(ctx context.Context, arg SetStaffPasswordParams) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, setStaffPassword, arg.ID, arg.PasswordHash, arg.MustChangePassword)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.ProfileComplete,
		&i.FailedAttempts,
		&i.LastFailureAt,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const slideStaffSession = `-- name: SlideStaffSession :exec
UPDATE staff_sessions SET last_seen_at = now(), expires_at = $2 WHERE id = $1
`

type SlideStaffSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) SlideStaffSession(ctx context.Context, arg SlideStaffSessionParams) error {
	_, err := q.db.Exec(ctx, slideStaffSession, arg.ID, arg.ExpiresAt)
	return err
}
