// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package catalogstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO device_categories (id, name, default_loan_period, requires_approval)
VALUES ($1, $2, $3, $4)
RETURNING id, name, default_loan_period, requires_approval, created_at
`

type CreateCategoryParams struct {
	ID                pgtype.UUID     `json:"id"`
	Name              string          `json:"name"`
	DefaultLoanPeriod pgtype.Interval `json:"default_loan_period"`
	RequiresApproval  bool            `json:"requires_approval"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (DeviceCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.DefaultLoanPeriod,
		arg.RequiresApproval,
	)
	var i DeviceCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultLoanPeriod,
		&i.RequiresApproval,
		&i.CreatedAt,
	)
	return i, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, asset_tag, name, category_id, manufacturer, model, serial_no, home_location, notes, acquired_on)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, asset_tag, name, category_id, manufacturer, model, serial_no, status, condition, home_location, notes, acquired_on, created_at, updated_at
`

type CreateDeviceParams struct {
	ID           pgtype.UUID `json:"id"`
	AssetTag     string      `json:"asset_tag"`
	Name         string      `json:"name"`
	CategoryID   pgtype.UUID `json:"category_id"`
	Manufacturer pgtype.Text `json:"manufacturer"`
	Model        pgtype.Text `json:"model"`
	SerialNo     pgtype.Text `json:"serial_no"`
	HomeLocation pgtype.Text `json:"home_location"`
	Notes        pgtype.Text `json:"notes"`
	AcquiredOn   pgtype.Date `json:"acquired_on"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.AssetTag,
		arg.Name,
		arg.CategoryID,
		arg.Manufacturer,
		arg.Model,
		arg.SerialNo,
		arg.HomeLocation,
		arg.Notes,
		arg.AcquiredOn,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.AssetTag,
		&i.Name,
		&i.CategoryID,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNo,
		&i.Status,
		&i.Condition,
		&i.HomeLocation,
		&i.Notes,
		&i.AcquiredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, default_loan_period, requires_approval, created_at
FROM device_categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (DeviceCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i DeviceCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultLoanPeriod,
		&i.RequiresApproval,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByAssetTag = `-- name: GetDeviceByAssetTag :one
SELECT id, asset_tag, name, category_id, manufacturer, model, serial_no, status, condition, home_location, notes, acquired_on, created_at, updated_at
FROM devices WHERE upper(asset_tag) = upper($1) AND status <> 'retired'
`

// Only among live (non-retired) devices, matching the live-uniqueness index.
func (q *Queries) GetDeviceByAssetTag(ctx context.Context, upper interface{}) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByAssetTag, upper)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.AssetTag,
		&i.Name,
		&i.CategoryID,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNo,
		&i.Status,
		&i.Condition,
		&i.HomeLocation,
		&i.Notes,
		&i.AcquiredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, asset_tag, name, category_id, manufacturer, model, serial_no, status, condition, home_location, notes, acquired_on, created_at, updated_at
FROM devices WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id pgtype.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.AssetTag,
		&i.Name,
		&i.CategoryID,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNo,
		&i.Status,
		&i.Condition,
		&i.HomeLocation,
		&i.Notes,
		&i.AcquiredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrCreateCategory = `-- name: GetOrCreateCategory :one
INSERT INTO device_categories (id, name)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, default_loan_period, requires_approval, created_at
`

type GetOrCreateCategoryParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

// Used by bulk import, which resolves a category name from a CSV column
// without needing a separate "does it exist" round trip.
func (q *Queries) GetOrCreateCategory(ctx context.Context, arg GetOrCreateCategoryParams) (DeviceCategory, error) {
	row := q.db.QueryRow(ctx, getOrCreateCategory, arg.ID, arg.Name)
	var i DeviceCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultLoanPeriod,
		&i.RequiresApproval,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, default_loan_period, requires_approval, created_at
FROM device_categories ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]DeviceCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceCategory
	for rows.Next() {
		var i DeviceCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultLoanPeriod,
			&i.RequiresApproval,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevices = `-- name: ListDevices :many
SELECT id, asset_tag, name, category_id, manufacturer, model, serial_no, status, condition, home_location, notes, acquired_on, created_at, updated_at
FROM devices
WHERE ($1::device_status IS NULL OR status = $1)
  AND ($2::uuid IS NULL OR category_id = $2)
  AND (
    $3::text IS NULL
    OR asset_tag ILIKE '%' || $3 || '%'
    OR name       ILIKE '%' || $3 || '%'
    OR model      ILIKE '%' || $3 || '%'
    OR serial_no  ILIKE '%' || $3 || '%'
  )
  AND (
    $4::timestamptz IS NULL
    OR created_at < $4
    OR (created_at = $4 AND id < $5)
  )
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListDevicesParams struct {
	Status          NullDeviceStatus   `json:"status"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	Query           pgtype.Text        `json:"query"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	ResultLimit     int32              `json:"result_limit"`
}

// The "full-text-ish search" is a plain ILIKE across the four fields an
// attendant is likely to have on hand: asset tag, name, model, serial.
func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices,
		arg.Status,
		arg.CategoryID,
		arg.Query,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.AssetTag,
			&i.Name,
			&i.CategoryID,
			&i.Manufacturer,
			&i.Model,
			&i.SerialNo,
			&i.Status,
			&i.Condition,
			&i.HomeLocation,
			&i.Notes,
			&i.AcquiredOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE device_categories
SET name = $2, default_loan_period = $3, requires_approval = $4
WHERE id = $1
RETURNING id, name, default_loan_period, requires_approval, created_at
`

type UpdateCategoryParams struct {
	ID                pgtype.UUID     `json:"id"`
	Name              string          `json:"name"`
	DefaultLoanPeriod pgtype.Interval `json:"default_loan_period"`
	RequiresApproval  bool            `json:"requires_approval"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (DeviceCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.DefaultLoanPeriod,
		arg.RequiresApproval,
	)
	var i DeviceCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultLoanPeriod,
		&i.RequiresApproval,
		&i.CreatedAt,
	)
	return i, err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET name = $2, category_id = $3, manufacturer = $4, model = $5, serial_no = $6,
    home_location = $7, notes = $8, acquired_on = $9, updated_at = now()
WHERE id = $1 AND status <> 'retired'
RETURNING id, asset_tag, name, category_id, manufacturer, model, serial_no, status, condition, home_location, notes, acquired_on, created_at, updated_at
`

type UpdateDeviceParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	CategoryID   pgtype.UUID `json:"category_id"`
	Manufacturer pgtype.Text `json:"manufacturer"`
	Model        pgtype.Text `json:"model"`
	SerialNo     pgtype.Text `json:"serial_no"`
	HomeLocation pgtype.Text `json:"home_location"`
	Notes        pgtype.Text `json:"notes"`
	AcquiredOn   pgtype.Date `json:"acquired_on"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.Name,
		arg.CategoryID,
		arg.Manufacturer,
		arg.Model,
		arg.SerialNo,
		arg.HomeLocation,
		arg.Notes,
		arg.AcquiredOn,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.AssetTag,
		&i.Name,
		&i.CategoryID,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNo,
		&i.Status,
		&i.Condition,
		&i.HomeLocation,
		&i.Notes,
		&i.AcquiredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeviceCondition = `-- name: UpdateDeviceCondition :one
UPDATE devices SET condition = $2, updated_at = now()
WHERE id = $1
RETURNING id, asset_tag, name, category_id, manufacturer, model, serial_no, status, condition, home_location, notes, acquired_on, created_at, updated_at
`

type UpdateDeviceConditionParams struct {
	ID        pgtype.UUID     `json:"id"`
	Condition DeviceCondition `json:"condition"`
}

func (q *Queries) UpdateDeviceCondition(ctx context.Context, arg UpdateDeviceConditionParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceCondition, arg.ID, arg.Condition)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.AssetTag,
		&i.Name,
		&i.CategoryID,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNo,
		&i.Status,
		&i.Condition,
		&i.HomeLocation,
		&i.Notes,
		&i.AcquiredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeviceStatus = `-- name: UpdateDeviceStatus :one
UPDATE devices SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, asset_tag, name, category_id, manufacturer, model, serial_no, status, condition, home_location, notes, acquired_on, created_at, updated_at
`

type UpdateDeviceStatusParams struct {
	ID     pgtype.UUID  `json:"id"`
	Status DeviceStatus `json:"status"`
}

func (q *Queries) UpdateDeviceStatus(ctx context.Context, arg UpdateDeviceStatusParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceStatus, arg.ID, arg.Status)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.AssetTag,
		&i.Name,
		&i.CategoryID,
		&i.Manufacturer,
		&i.Model,
		&i.SerialNo,
		&i.Status,
		&i.Condition,
		&i.HomeLocation,
		&i.Notes,
		&i.AcquiredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
