// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogstore

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminRole string

const (
	AdminRoleSuperadmin AdminRole = "superadmin"
	AdminRoleAdmin      AdminRole = "admin"
	AdminRoleOperator   AdminRole = "operator"
)

func (e *AdminRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminRole(s)
	case string:
		*e = AdminRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminRole: %T", src)
	}
	return nil
}

type NullAdminRole struct {
	AdminRole AdminRole `json:"admin_role"`
	Valid     bool      `json:"valid"` // Valid is true if AdminRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminRole) Scan(value interface{}) error {
	if value == nil {
		ns.AdminRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminRole), nil
}

type AdminStatus string

const (
	AdminStatusActive   AdminStatus = "active"
	AdminStatusDisabled AdminStatus = "disabled"
)

func (e *AdminStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminStatus(s)
	case string:
		*e = AdminStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminStatus: %T", src)
	}
	return nil
}

type NullAdminStatus struct {
	AdminStatus AdminStatus `json:"admin_status"`
	Valid       bool        `json:"valid"` // Valid is true if AdminStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AdminStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminStatus), nil
}

type CredentialKind string

const (
	CredentialKindQr      CredentialKind = "qr"
	CredentialKindCode128 CredentialKind = "code128"
	CredentialKindNfc     CredentialKind = "nfc"
	CredentialKindRfid    CredentialKind = "rfid"
	CredentialKindManual  CredentialKind = "manual"
)

func (e *CredentialKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CredentialKind(s)
	case string:
		*e = CredentialKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CredentialKind: %T", src)
	}
	return nil
}

type NullCredentialKind struct {
	CredentialKind CredentialKind `json:"credential_kind"`
	Valid          bool           `json:"valid"` // Valid is true if CredentialKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCredentialKind) Scan(value interface{}) error {
	if value == nil {
		ns.CredentialKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CredentialKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCredentialKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CredentialKind), nil
}

type CredentialStatus string

const (
	CredentialStatusActive  CredentialStatus = "active"
	CredentialStatusRevoked CredentialStatus = "revoked"
	CredentialStatusLost    CredentialStatus = "lost"
)

func (e *CredentialStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CredentialStatus(s)
	case string:
		*e = CredentialStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CredentialStatus: %T", src)
	}
	return nil
}

type NullCredentialStatus struct {
	CredentialStatus CredentialStatus `json:"credential_status"`
	Valid            bool             `json:"valid"` // Valid is true if CredentialStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCredentialStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CredentialStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CredentialStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCredentialStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CredentialStatus), nil
}

type DeviceCondition string

const (
	DeviceConditionGood    DeviceCondition = "good"
	DeviceConditionFair    DeviceCondition = "fair"
	DeviceConditionDamaged DeviceCondition = "damaged"
)

func (e *DeviceCondition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceCondition(s)
	case string:
		*e = DeviceCondition(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceCondition: %T", src)
	}
	return nil
}

type NullDeviceCondition struct {
	DeviceCondition DeviceCondition `json:"device_condition"`
	Valid           bool            `json:"valid"` // Valid is true if DeviceCondition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceCondition) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceCondition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceCondition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceCondition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceCondition), nil
}

type DeviceStatus string

const (
	DeviceStatusAvailable   DeviceStatus = "available"
	DeviceStatusOnLoan      DeviceStatus = "on_loan"
	DeviceStatusMaintenance DeviceStatus = "maintenance"
	DeviceStatusRetired     DeviceStatus = "retired"
	DeviceStatusLost        DeviceStatus = "lost"
)

func (e *DeviceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceStatus(s)
	case string:
		*e = DeviceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceStatus: %T", src)
	}
	return nil
}

type NullDeviceStatus struct {
	DeviceStatus DeviceStatus `json:"device_status"`
	Valid        bool         `json:"valid"` // Valid is true if DeviceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceStatus), nil
}

type KioskStatus string

const (
	KioskStatusActive   KioskStatus = "active"
	KioskStatusDisabled KioskStatus = "disabled"
)

func (e *KioskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KioskStatus(s)
	case string:
		*e = KioskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for KioskStatus: %T", src)
	}
	return nil
}

type NullKioskStatus struct {
	KioskStatus KioskStatus `json:"kiosk_status"`
	Valid       bool        `json:"valid"` // Valid is true if KioskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKioskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.KioskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KioskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKioskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KioskStatus), nil
}

type SubjectType string

const (
	SubjectTypeUser   SubjectType = "user"
	SubjectTypeDevice SubjectType = "device"
)

func (e *SubjectType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubjectType(s)
	case string:
		*e = SubjectType(s)
	default:
		return fmt.Errorf("unsupported scan type for SubjectType: %T", src)
	}
	return nil
}

type NullSubjectType struct {
	SubjectType SubjectType `json:"subject_type"`
	Valid       bool        `json:"valid"` // Valid is true if SubjectType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubjectType) Scan(value interface{}) error {
	if value == nil {
		ns.SubjectType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubjectType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubjectType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubjectType), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusArchived  UserStatus = "archived"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AdminAccount struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	FullName      string             `json:"full_name"`
	PasswordHash  string             `json:"password_hash"`
	TotpSecretEnc []byte             `json:"totp_secret_enc"`
	Role          AdminRole          `json:"role"`
	Status        AdminStatus        `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AdminSession struct {
	ID               pgtype.UUID        `json:"id"`
	AdminID          pgtype.UUID        `json:"admin_id"`
	SessionTokenHash []byte             `json:"session_token_hash"`
	CsrfToken        string             `json:"csrf_token"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type AuditEvent struct {
	ID        pgtype.UUID        `json:"id"`
	At        pgtype.Timestamptz `json:"at"`
	Actor     string             `json:"actor"`
	ActorIp   *netip.Addr        `json:"actor_ip"`
	Action    string             `json:"action"`
	Subject   string             `json:"subject"`
	Payload   []byte             `json:"payload"`
	RequestID pgtype.Text        `json:"request_id"`
}

type Credential struct {
	ID            pgtype.UUID        `json:"id"`
	SubjectType   SubjectType        `json:"subject_type"`
	SubjectID     pgtype.UUID        `json:"subject_id"`
	Kind          CredentialKind     `json:"kind"`
	TokenHash     []byte             `json:"token_hash"`
	TokenPreview  string             `json:"token_preview"`
	TokenEnc      []byte             `json:"token_enc"`
	Label         pgtype.Text        `json:"label"`
	Status        CredentialStatus   `json:"status"`
	IssueSeq      int32              `json:"issue_seq"`
	ReplacesID    pgtype.UUID        `json:"replaces_id"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	IssuedBy      string             `json:"issued_by"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedBy     pgtype.Text        `json:"revoked_by"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
	PrintedCount  int32              `json:"printed_count"`
	LastPrintedAt pgtype.Timestamptz `json:"last_printed_at"`
}

type CredentialEvent struct {
	ID           pgtype.UUID        `json:"id"`
	CredentialID pgtype.UUID        `json:"credential_id"`
	At           pgtype.Timestamptz `json:"at"`
	Kind         string             `json:"kind"`
	Actor        string             `json:"actor"`
	Reason       pgtype.Text        `json:"reason"`
	Payload      []byte             `json:"payload"`
}

type Department struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID           pgtype.UUID        `json:"id"`
	AssetTag     string             `json:"asset_tag"`
	Name         string             `json:"name"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Manufacturer pgtype.Text        `json:"manufacturer"`
	Model        pgtype.Text        `json:"model"`
	SerialNo     pgtype.Text        `json:"serial_no"`
	Status       DeviceStatus       `json:"status"`
	Condition    DeviceCondition    `json:"condition"`
	HomeLocation pgtype.Text        `json:"home_location"`
	Notes        pgtype.Text        `json:"notes"`
	AcquiredOn   pgtype.Date        `json:"acquired_on"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DeviceCategory struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	DefaultLoanPeriod pgtype.Interval    `json:"default_loan_period"`
	RequiresApproval  bool               `json:"requires_approval"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Kiosk struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Location       pgtype.Text        `json:"location"`
	TokenHash      []byte             `json:"token_hash"`
	EnabledSources []string           `json:"enabled_sources"`
	Status         KioskStatus        `json:"status"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Outbox struct {
	ID          int64              `json:"id"`
	Topic       string             `json:"topic"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	EmployeeNo   string             `json:"employee_no"`
	FullName     string             `json:"full_name"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Status       UserStatus         `json:"status"`
	Notes        pgtype.Text        `json:"notes"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	RegisteredBy string             `json:"registered_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
