// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountLiveDevicesByCategory(ctx context.Context) ([]CountLiveDevicesByCategoryRow, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (DeviceCategory, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	GetCategoryByID(ctx context.Context, id pgtype.UUID) (DeviceCategory, error)
	// Only among live (non-retired) devices, matching the live-uniqueness index.
	GetDeviceByAssetTag(ctx context.Context, upper interface{}) (Device, error)
	GetDeviceByID(ctx context.Context, id pgtype.UUID) (Device, error)
	// Used by bulk import, which resolves a category name from a CSV column
	// without needing a separate "does it exist" round trip.
	GetOrCreateCategory(ctx context.Context, arg GetOrCreateCategoryParams) (DeviceCategory, error)
	ListCategories(ctx context.Context) ([]DeviceCategory, error)
	// The "full-text-ish search" is a plain ILIKE across the four fields an
	// attendant is likely to have on hand: asset tag, name, model, serial.
	ListDevices(ctx context.Context, arg ListDevicesParams) ([]Device, error)
	StreamDevicesForExport(ctx context.Context, arg StreamDevicesForExportParams) ([]StreamDevicesForExportRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (DeviceCategory, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error)
	UpdateDeviceCondition(ctx context.Context, arg UpdateDeviceConditionParams) (Device, error)
	UpdateDeviceStatus(ctx context.Context, arg UpdateDeviceStatusParams) (Device, error)
}

var _ Querier = (*Queries)(nil)
