// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkout.sql

package checkoutstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeSession = `-- name: CloseSession :one
UPDATE scan_sessions
SET state = $2, closed_at = $3, outcome = $4
WHERE id = $1
RETURNING id, kiosk_id, state, user_id, pending_device, started_at, last_activity, expires_at, closed_at, outcome, last_token_hash, last_scan_at
`

type CloseSessionParams struct {
	ID       pgtype.UUID        `json:"id"`
	State    SessionState       `json:"state"`
	ClosedAt pgtype.Timestamptz `json:"closed_at"`
	Outcome  pgtype.Text        `json:"outcome"`
}

func (q *Queries) CloseSession(ctx context.Context, arg CloseSessionParams) (ScanSession, error) {
	row := q.db.QueryRow(ctx, closeSession,
		arg.ID,
		arg.State,
		arg.ClosedAt,
		arg.Outcome,
	)
	var i ScanSession
	err := row.Scan(
		&i.ID,
		&i.KioskID,
		&i.State,
		&i.UserID,
		&i.PendingDevice,
		&i.StartedAt,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.Outcome,
		&i.LastTokenHash,
		&i.LastScanAt,
	)
	return i, err
}

const countScanRejectionsSince = `-- name: CountScanRejectionsSince :many
SELECT resolved_type, COUNT(DISTINCT token_preview) AS distinct_tokens, COUNT(*) AS total_scans
FROM scan_events
WHERE result = 'rejected' AND at >= $1
GROUP BY resolved_type
`

type CountScanRejectionsSinceRow struct {
	ResolvedType   pgtype.Text `json:"resolved_type"`
	DistinctTokens int64       `json:"distinct_tokens"`
	TotalScans     int64       `json:"total_scans"`
}

// The dashboard's "people turned away" number (2.4), grouped by
// resolved_type and counted by distinct token_preview — the same person
// re-scanning three times is one person to go and register, not three.
func (q *Queries) CountScanRejectionsSince(ctx context.Context, at pgtype.Timestamptz) ([]CountScanRejectionsSinceRow, error) {
	rows, err := q.db.Query(ctx, countScanRejectionsSince, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountScanRejectionsSinceRow
	for rows.Next() {
		var i CountScanRejectionsSinceRow
		if err := rows.Scan(&i.ResolvedType, &i.DistinctTokens, &i.TotalScans); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSession = `-- name: CreateSession :one
INSERT INTO scan_sessions (id, kiosk_id, state, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, kiosk_id, state, user_id, pending_device, started_at, last_activity, expires_at, closed_at, outcome, last_token_hash, last_scan_at
`

type CreateSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	KioskID   pgtype.UUID        `json:"kiosk_id"`
	State     SessionState       `json:"state"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (ScanSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.KioskID,
		arg.State,
		arg.ExpiresAt,
	)
	var i ScanSession
	err := row.Scan(
		&i.ID,
		&i.KioskID,
		&i.State,
		&i.UserID,
		&i.PendingDevice,
		&i.StartedAt,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.Outcome,
		&i.LastTokenHash,
		&i.LastScanAt,
	)
	return i, err
}

const expireSessions = `-- name: ExpireSessions :many
UPDATE scan_sessions
SET state = 'expired', closed_at = $1, outcome = 'expired'
WHERE expires_at < $1 AND closed_at IS NULL
RETURNING id, kiosk_id, state, user_id, pending_device, started_at, last_activity, expires_at, closed_at, outcome, last_token_hash, last_scan_at
`

// The sweeper's bulk close (2.3c): every session past its expiry that
// nobody closed, in one statement.
func (q *Queries) ExpireSessions(ctx context.Context, closedAt pgtype.Timestamptz) ([]ScanSession, error) {
	rows, err := q.db.Query(ctx, expireSessions, closedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanSession
	for rows.Next() {
		var i ScanSession
		if err := rows.Scan(
			&i.ID,
			&i.KioskID,
			&i.State,
			&i.UserID,
			&i.PendingDevice,
			&i.StartedAt,
			&i.LastActivity,
			&i.ExpiresAt,
			&i.ClosedAt,
			&i.Outcome,
			&i.LastTokenHash,
			&i.LastScanAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLiveSessionForKiosk = `-- name: GetLiveSessionForKiosk :one
SELECT id, kiosk_id, state, user_id, pending_device, started_at, last_activity, expires_at, closed_at, outcome, last_token_hash, last_scan_at FROM scan_sessions WHERE kiosk_id = $1 AND closed_at IS NULL
`

func (q *Queries) GetLiveSessionForKiosk(ctx context.Context, kioskID pgtype.UUID) (ScanSession, error) {
	row := q.db.QueryRow(ctx, getLiveSessionForKiosk, kioskID)
	var i ScanSession
	err := row.Scan(
		&i.ID,
		&i.KioskID,
		&i.State,
		&i.UserID,
		&i.PendingDevice,
		&i.StartedAt,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.Outcome,
		&i.LastTokenHash,
		&i.LastScanAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, kiosk_id, state, user_id, pending_device, started_at, last_activity, expires_at, closed_at, outcome, last_token_hash, last_scan_at FROM scan_sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (ScanSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i ScanSession
	err := row.Scan(
		&i.ID,
		&i.KioskID,
		&i.State,
		&i.UserID,
		&i.PendingDevice,
		&i.StartedAt,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.Outcome,
		&i.LastTokenHash,
		&i.LastScanAt,
	)
	return i, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, kiosk_id, state, user_id, pending_device, started_at, last_activity, expires_at, closed_at, outcome, last_token_hash, last_scan_at FROM scan_sessions WHERE id = $1 FOR UPDATE
`

// The serialisation point for concurrent scans on one session (2.3c): a
// row lock, held only for the duration of the transaction that executes
// one scan's decision.
func (q *Queries) GetSessionForUpdate(ctx context.Context, id pgtype.UUID) (ScanSession, error) {
	row := q.db.QueryRow(ctx, getSessionForUpdate, id)
	var i ScanSession
	err := row.Scan(
		&i.ID,
		&i.KioskID,
		&i.State,
		&i.UserID,
		&i.PendingDevice,
		&i.StartedAt,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.Outcome,
		&i.LastTokenHash,
		&i.LastScanAt,
	)
	return i, err
}

const insertScanEvent = `-- name: InsertScanEvent :one
INSERT INTO scan_events (id, session_id, at, source, token_preview, resolved_type, resolved_id, result, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, session_id, at, source, token_preview, resolved_type, resolved_id, result, reason
`

type InsertScanEventParams struct {
	ID           pgtype.UUID        `json:"id"`
	SessionID    pgtype.UUID        `json:"session_id"`
	At           pgtype.Timestamptz `json:"at"`
	Source       string             `json:"source"`
	TokenPreview string             `json:"token_preview"`
	ResolvedType pgtype.Text        `json:"resolved_type"`
	ResolvedID   pgtype.UUID        `json:"resolved_id"`
	Result       string             `json:"result"`
	Reason       pgtype.Text        `json:"reason"`
}

func (q *Queries) InsertScanEvent(ctx context.Context, arg InsertScanEventParams) (ScanEvent, error) {
	row := q.db.QueryRow(ctx, insertScanEvent,
		arg.ID,
		arg.SessionID,
		arg.At,
		arg.Source,
		arg.TokenPreview,
		arg.ResolvedType,
		arg.ResolvedID,
		arg.Result,
		arg.Reason,
	)
	var i ScanEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.At,
		&i.Source,
		&i.TokenPreview,
		&i.ResolvedType,
		&i.ResolvedID,
		&i.Result,
		&i.Reason,
	)
	return i, err
}

const listScanEventsForSession = `-- name: ListScanEventsForSession :many
SELECT id, session_id, at, source, token_preview, resolved_type, resolved_id, result, reason FROM scan_events WHERE session_id = $1 ORDER BY at
`

func (q *Queries) ListScanEventsForSession(ctx context.Context, sessionID pgtype.UUID) ([]ScanEvent, error) {
	rows, err := q.db.Query(ctx, listScanEventsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanEvent
	for rows.Next() {
		var i ScanEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.At,
			&i.Source,
			&i.TokenPreview,
			&i.ResolvedType,
			&i.ResolvedID,
			&i.Result,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :one
UPDATE scan_sessions
SET last_activity = $2, expires_at = $3
WHERE id = $1
RETURNING id, kiosk_id, state, user_id, pending_device, started_at, last_activity, expires_at, closed_at, outcome, last_token_hash, last_scan_at
`

type TouchSessionParams struct {
	ID           pgtype.UUID        `json:"id"`
	LastActivity pgtype.Timestamptz `json:"last_activity"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (ScanSession, error) {
	row := q.db.QueryRow(ctx, touchSession, arg.ID, arg.LastActivity, arg.ExpiresAt)
	var i ScanSession
	err := row.Scan(
		&i.ID,
		&i.KioskID,
		&i.State,
		&i.UserID,
		&i.PendingDevice,
		&i.StartedAt,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.Outcome,
		&i.LastTokenHash,
		&i.LastScanAt,
	)
	return i, err
}

const updateSessionState = `-- name: UpdateSessionState :one
UPDATE scan_sessions
SET state = $2, user_id = $3, pending_device = $4,
    last_activity = $5, expires_at = $6,
    last_token_hash = $7, last_scan_at = $8
WHERE id = $1
RETURNING id, kiosk_id, state, user_id, pending_device, started_at, last_activity, expires_at, closed_at, outcome, last_token_hash, last_scan_at
`

type UpdateSessionStateParams struct {
	ID            pgtype.UUID        `json:"id"`
	State         SessionState       `json:"state"`
	UserID        pgtype.UUID        `json:"user_id"`
	PendingDevice pgtype.UUID        `json:"pending_device"`
	LastActivity  pgtype.Timestamptz `json:"last_activity"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	LastTokenHash []byte             `json:"last_token_hash"`
	LastScanAt    pgtype.Timestamptz `json:"last_scan_at"`
}

func (q *Queries) UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) (ScanSession, error) {
	row := q.db.QueryRow(ctx, updateSessionState,
		arg.ID,
		arg.State,
		arg.UserID,
		arg.PendingDevice,
		arg.LastActivity,
		arg.ExpiresAt,
		arg.LastTokenHash,
		arg.LastScanAt,
	)
	var i ScanSession
	err := row.Scan(
		&i.ID,
		&i.KioskID,
		&i.State,
		&i.UserID,
		&i.PendingDevice,
		&i.StartedAt,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.Outcome,
		&i.LastTokenHash,
		&i.LastScanAt,
	)
	return i, err
}
