// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package checkoutstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CloseSession(ctx context.Context, arg CloseSessionParams) (ScanSession, error)
	// The dashboard's "people turned away" number (2.4), grouped by
	// resolved_type and counted by distinct token_preview — the same person
	// re-scanning three times is one person to go and register, not three.
	CountScanRejectionsSince(ctx context.Context, at pgtype.Timestamptz) ([]CountScanRejectionsSinceRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (ScanSession, error)
	// The sweeper's bulk close (2.3c): every session past its expiry that
	// nobody closed, in one statement.
	ExpireSessions(ctx context.Context, closedAt pgtype.Timestamptz) ([]ScanSession, error)
	GetLiveSessionForKiosk(ctx context.Context, kioskID pgtype.UUID) (ScanSession, error)
	GetOperationalHealthStats(ctx context.Context, arg GetOperationalHealthStatsParams) (GetOperationalHealthStatsRow, error)
	GetScanRejectionReasons(ctx context.Context, arg GetScanRejectionReasonsParams) ([]GetScanRejectionReasonsRow, error)
	GetScansBySource(ctx context.Context, arg GetScansBySourceParams) ([]GetScansBySourceRow, error)
	GetSession(ctx context.Context, id pgtype.UUID) (ScanSession, error)
	// The serialisation point for concurrent scans on one session (2.3c): a
	// row lock, held only for the duration of the transaction that executes
	// one scan's decision.
	GetSessionForUpdate(ctx context.Context, id pgtype.UUID) (ScanSession, error)
	InsertScanEvent(ctx context.Context, arg InsertScanEventParams) (ScanEvent, error)
	ListScanEventsForSession(ctx context.Context, sessionID pgtype.UUID) ([]ScanEvent, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) (ScanSession, error)
	UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) (ScanSession, error)
}

var _ Querier = (*Queries)(nil)
