// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package settingsstore

import (
	"context"
)

type Querier interface {
	GetSettings(ctx context.Context) (Setting, error)
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error)
}

var _ Querier = (*Queries)(nil)
