// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package credentialsstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindCredential = `-- name: BindCredential :one
UPDATE credentials
SET subject_id = $2
WHERE id = $1 AND subject_id IS NULL AND status = 'active'
RETURNING id, subject_type, subject_id, kind, token_hash, token_preview, token_enc, label, status, issue_seq, replaces_id, issued_at, issued_by, revoked_at, revoked_by, revoked_reason, printed_count, last_printed_at
`

type BindCredentialParams struct {
	ID        pgtype.UUID `json:"id"`
	SubjectID pgtype.UUID `json:"subject_id"`
}

// Binds a blank (unbound, active) card to a subject. The WHERE clause is
// the guard: it is a no-op update (zero rows) rather than a corruption if
// the card was already bound or is no longer active.
func (q *Queries) BindCredential(ctx context.Context, arg BindCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, bindCredential, arg.ID, arg.SubjectID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Kind,
		&i.TokenHash,
		&i.TokenPreview,
		&i.TokenEnc,
		&i.Label,
		&i.Status,
		&i.IssueSeq,
		&i.ReplacesID,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
		&i.PrintedCount,
		&i.LastPrintedAt,
	)
	return i, err
}

const countUnboundCredentials = `-- name: CountUnboundCredentials :one
SELECT count(*) FROM credentials WHERE subject_id IS NULL AND status = 'active'
`

// Backs the "blank card stock running low" dashboard warning.
func (q *Queries) CountUnboundCredentials(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnboundCredentials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (id, subject_type, subject_id, kind, token_hash, token_preview, token_enc, label, issue_seq, replaces_id, issued_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, subject_type, subject_id, kind, token_hash, token_preview, token_enc, label, status, issue_seq, replaces_id, issued_at, issued_by, revoked_at, revoked_by, revoked_reason, printed_count, last_printed_at
`

type CreateCredentialParams struct {
	ID           pgtype.UUID    `json:"id"`
	SubjectType  SubjectType    `json:"subject_type"`
	SubjectID    pgtype.UUID    `json:"subject_id"`
	Kind         CredentialKind `json:"kind"`
	TokenHash    []byte         `json:"token_hash"`
	TokenPreview string         `json:"token_preview"`
	TokenEnc     []byte         `json:"token_enc"`
	Label        pgtype.Text    `json:"label"`
	IssueSeq     int32          `json:"issue_seq"`
	ReplacesID   pgtype.UUID    `json:"replaces_id"`
	IssuedBy     string         `json:"issued_by"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Kind,
		arg.TokenHash,
		arg.TokenPreview,
		arg.TokenEnc,
		arg.Label,
		arg.IssueSeq,
		arg.ReplacesID,
		arg.IssuedBy,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Kind,
		&i.TokenHash,
		&i.TokenPreview,
		&i.TokenEnc,
		&i.Label,
		&i.Status,
		&i.IssueSeq,
		&i.ReplacesID,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
		&i.PrintedCount,
		&i.LastPrintedAt,
	)
	return i, err
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT id, subject_type, subject_id, kind, token_hash, token_preview, token_enc, label, status, issue_seq, replaces_id, issued_at, issued_by, revoked_at, revoked_by, revoked_reason, printed_count, last_printed_at FROM credentials WHERE id = $1
`

func (q *Queries) GetCredentialByID(ctx context.Context, id pgtype.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByID, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Kind,
		&i.TokenHash,
		&i.TokenPreview,
		&i.TokenEnc,
		&i.Label,
		&i.Status,
		&i.IssueSeq,
		&i.ReplacesID,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
		&i.PrintedCount,
		&i.LastPrintedAt,
	)
	return i, err
}

const getCredentialByTokenHash = `-- name: GetCredentialByTokenHash :one
SELECT id, subject_type, subject_id, kind, token_hash, token_preview, token_enc, label, status, issue_seq, replaces_id, issued_at, issued_by, revoked_at, revoked_by, revoked_reason, printed_count, last_printed_at FROM credentials WHERE token_hash = $1 ORDER BY issued_at DESC LIMIT 1
`

// Includes revoked/lost rows too (INV-4): a dead card must resolve with an
// explanation, never "not found". issued_at DESC is a defensive tie-break
// in the astronomically unlikely event two rows ever shared a hash.
func (q *Queries) GetCredentialByTokenHash(ctx context.Context, tokenHash []byte) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByTokenHash, tokenHash)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Kind,
		&i.TokenHash,
		&i.TokenPreview,
		&i.TokenEnc,
		&i.Label,
		&i.Status,
		&i.IssueSeq,
		&i.ReplacesID,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
		&i.PrintedCount,
		&i.LastPrintedAt,
	)
	return i, err
}

const insertCredentialEvent = `-- name: InsertCredentialEvent :exec
INSERT INTO credential_events (id, credential_id, kind, actor, reason, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCredentialEventParams struct {
	ID           pgtype.UUID `json:"id"`
	CredentialID pgtype.UUID `json:"credential_id"`
	Kind         string      `json:"kind"`
	Actor        string      `json:"actor"`
	Reason       pgtype.Text `json:"reason"`
	Payload      []byte      `json:"payload"`
}

func (q *Queries) InsertCredentialEvent(ctx context.Context, arg InsertCredentialEventParams) error {
	_, err := q.db.Exec(ctx, insertCredentialEvent,
		arg.ID,
		arg.CredentialID,
		arg.Kind,
		arg.Actor,
		arg.Reason,
		arg.Payload,
	)
	return err
}

const listCredentialEvents = `-- name: ListCredentialEvents :many
SELECT id, credential_id, at, kind, actor, reason, payload
FROM credential_events WHERE credential_id = $1 ORDER BY at DESC
`

func (q *Queries) ListCredentialEvents(ctx context.Context, credentialID pgtype.UUID) ([]CredentialEvent, error) {
	rows, err := q.db.Query(ctx, listCredentialEvents, credentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CredentialEvent
	for rows.Next() {
		var i CredentialEvent
		if err := rows.Scan(
			&i.ID,
			&i.CredentialID,
			&i.At,
			&i.Kind,
			&i.Actor,
			&i.Reason,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsBySubject = `-- name: ListCredentialsBySubject :many
SELECT id, subject_type, subject_id, kind, token_hash, token_preview, token_enc, label, status, issue_seq, replaces_id, issued_at, issued_by, revoked_at, revoked_by, revoked_reason, printed_count, last_printed_at FROM credentials WHERE subject_type = $1 AND subject_id = $2 ORDER BY issued_at DESC
`

type ListCredentialsBySubjectParams struct {
	SubjectType SubjectType `json:"subject_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
}

func (q *Queries) ListCredentialsBySubject(ctx context.Context, arg ListCredentialsBySubjectParams) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentialsBySubject, arg.SubjectType, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Kind,
			&i.TokenHash,
			&i.TokenPreview,
			&i.TokenEnc,
			&i.Label,
			&i.Status,
			&i.IssueSeq,
			&i.ReplacesID,
			&i.IssuedAt,
			&i.IssuedBy,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokedReason,
			&i.PrintedCount,
			&i.LastPrintedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnboundCredentials = `-- name: ListUnboundCredentials :many
SELECT id, subject_type, subject_id, kind, token_hash, token_preview, token_enc, label, status, issue_seq, replaces_id, issued_at, issued_by, revoked_at, revoked_by, revoked_reason, printed_count, last_printed_at FROM credentials
WHERE subject_id IS NULL AND status = 'active'
ORDER BY issued_at
LIMIT $1
`

func (q *Queries) ListUnboundCredentials(ctx context.Context, resultLimit int32) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listUnboundCredentials, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Kind,
			&i.TokenHash,
			&i.TokenPreview,
			&i.TokenEnc,
			&i.Label,
			&i.Status,
			&i.IssueSeq,
			&i.ReplacesID,
			&i.IssuedAt,
			&i.IssuedBy,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.RevokedReason,
			&i.PrintedCount,
			&i.LastPrintedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCredentialLostForReissue = `-- name: MarkCredentialLostForReissue :one
UPDATE credentials
SET status = 'lost', revoked_at = now(), revoked_by = $2, revoked_reason = $3
WHERE id = $1 AND status = 'active'
RETURNING id, subject_type, subject_id, kind, token_hash, token_preview, token_enc, label, status, issue_seq, replaces_id, issued_at, issued_by, revoked_at, revoked_by, revoked_reason, printed_count, last_printed_at
`

type MarkCredentialLostForReissueParams struct {
	ID            pgtype.UUID `json:"id"`
	RevokedBy     pgtype.Text `json:"revoked_by"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

// The first half of Reissue: the old token dies as 'lost' (distinct from a
// plain Revoke) so a found copy of it can be explained precisely, while the
// second half — minting the replacement — is a separate CreateCredential
// call with replaces_id set, in the same transaction.
func (q *Queries) MarkCredentialLostForReissue(ctx context.Context, arg MarkCredentialLostForReissueParams) (Credential, error) {
	row := q.db.QueryRow(ctx, markCredentialLostForReissue, arg.ID, arg.RevokedBy, arg.RevokedReason)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Kind,
		&i.TokenHash,
		&i.TokenPreview,
		&i.TokenEnc,
		&i.Label,
		&i.Status,
		&i.IssueSeq,
		&i.ReplacesID,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
		&i.PrintedCount,
		&i.LastPrintedAt,
	)
	return i, err
}

const recordCredentialPrint = `-- name: RecordCredentialPrint :one
UPDATE credentials
SET printed_count = printed_count + 1, last_printed_at = now()
WHERE id = $1
RETURNING id, subject_type, subject_id, kind, token_hash, token_preview, token_enc, label, status, issue_seq, replaces_id, issued_at, issued_by, revoked_at, revoked_by, revoked_reason, printed_count, last_printed_at
`

func (q *Queries) RecordCredentialPrint(ctx context.Context, id pgtype.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, recordCredentialPrint, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Kind,
		&i.TokenHash,
		&i.TokenPreview,
		&i.TokenEnc,
		&i.Label,
		&i.Status,
		&i.IssueSeq,
		&i.ReplacesID,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
		&i.PrintedCount,
		&i.LastPrintedAt,
	)
	return i, err
}

const revokeCredential = `-- name: RevokeCredential :one
UPDATE credentials
SET status = 'revoked', revoked_at = now(), revoked_by = $2, revoked_reason = $3
WHERE id = $1 AND status = 'active'
RETURNING id, subject_type, subject_id, kind, token_hash, token_preview, token_enc, label, status, issue_seq, replaces_id, issued_at, issued_by, revoked_at, revoked_by, revoked_reason, printed_count, last_printed_at
`

type RevokeCredentialParams struct {
	ID            pgtype.UUID `json:"id"`
	RevokedBy     pgtype.Text `json:"revoked_by"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

// Terminal: kills a token with no replacement minted.
func (q *Queries) RevokeCredential(ctx context.Context, arg RevokeCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, revokeCredential, arg.ID, arg.RevokedBy, arg.RevokedReason)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Kind,
		&i.TokenHash,
		&i.TokenPreview,
		&i.TokenEnc,
		&i.Label,
		&i.Status,
		&i.IssueSeq,
		&i.ReplacesID,
		&i.IssuedAt,
		&i.IssuedBy,
		&i.RevokedAt,
		&i.RevokedBy,
		&i.RevokedReason,
		&i.PrintedCount,
		&i.LastPrintedAt,
	)
	return i, err
}
