// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package credentialsstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Binds a blank (unbound, active) card to a subject. The WHERE clause is
	// the guard: it is a no-op update (zero rows) rather than a corruption if
	// the card was already bound or is no longer active.
	BindCredential(ctx context.Context, arg BindCredentialParams) (Credential, error)
	// Backs the "blank card stock running low" dashboard warning.
	CountUnboundCredentials(ctx context.Context) (int64, error)
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error)
	GetCredentialByID(ctx context.Context, id pgtype.UUID) (Credential, error)
	// Includes revoked/lost rows too (INV-4): a dead card must resolve with an
	// explanation, never "not found". issued_at DESC is a defensive tie-break
	// in the astronomically unlikely event two rows ever shared a hash.
	GetCredentialByTokenHash(ctx context.Context, tokenHash []byte) (Credential, error)
	InsertCredentialEvent(ctx context.Context, arg InsertCredentialEventParams) error
	ListCredentialEvents(ctx context.Context, credentialID pgtype.UUID) ([]CredentialEvent, error)
	ListCredentialsBySubject(ctx context.Context, arg ListCredentialsBySubjectParams) ([]Credential, error)
	ListUnboundCredentials(ctx context.Context, resultLimit int32) ([]Credential, error)
	// The first half of Reissue: the old token dies as 'lost' (distinct from a
	// plain Revoke) so a found copy of it can be explained precisely, while the
	// second half — minting the replacement — is a separate CreateCredential
	// call with replaces_id set, in the same transaction.
	MarkCredentialLostForReissue(ctx context.Context, arg MarkCredentialLostForReissueParams) (Credential, error)
	RecordCredentialPrint(ctx context.Context, id pgtype.UUID) (Credential, error)
	// Terminal: kills a token with no replacement minted.
	RevokeCredential(ctx context.Context, arg RevokeCredentialParams) (Credential, error)
}

var _ Querier = (*Queries)(nil)
