// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package identitystore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at
`

type CreateDepartmentParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.ID, arg.Name)
	var i Department
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createDirectoryLink = `-- name: CreateDirectoryLink :one
INSERT INTO user_directory_links (
    id, user_id, issuer, subject, last_seen_in_directory, sync_state
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, issuer, subject, last_seen_in_directory, sync_state, created_at, updated_at
`

type CreateDirectoryLinkParams struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Issuer              string             `json:"issuer"`
	Subject             string             `json:"subject"`
	LastSeenInDirectory pgtype.Timestamptz `json:"last_seen_in_directory"`
	SyncState           string             `json:"sync_state"`
}

func (q *Queries) CreateDirectoryLink(ctx context.Context, arg CreateDirectoryLinkParams) (UserDirectoryLink, error) {
	row := q.db.QueryRow(ctx, createDirectoryLink,
		arg.ID,
		arg.UserID,
		arg.Issuer,
		arg.Subject,
		arg.LastSeenInDirectory,
		arg.SyncState,
	)
	var i UserDirectoryLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.LastSeenInDirectory,
		&i.SyncState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO import_batches (id, kind, actor, filename, total_rows, created_count, updated_count, skipped_count, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, kind, actor, filename, total_rows, created_count, updated_count, skipped_count, created_at
`

type CreateImportBatchParams struct {
	ID           string             `json:"id"`
	Kind         string             `json:"kind"`
	Actor        string             `json:"actor"`
	Filename     string             `json:"filename"`
	TotalRows    int32              `json:"total_rows"`
	CreatedCount int32              `json:"created_count"`
	UpdatedCount int32              `json:"updated_count"`
	SkippedCount int32              `json:"skipped_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch,
		arg.ID,
		arg.Kind,
		arg.Actor,
		arg.Filename,
		arg.TotalRows,
		arg.CreatedCount,
		arg.UpdatedCount,
		arg.SkippedCount,
		arg.CreatedAt,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Actor,
		&i.Filename,
		&i.TotalRows,
		&i.CreatedCount,
		&i.UpdatedCount,
		&i.SkippedCount,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, employee_no, full_name, department_id, email, phone, notes, registered_by, import_batch_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
`

type CreateUserParams struct {
	ID            pgtype.UUID `json:"id"`
	EmployeeNo    string      `json:"employee_no"`
	FullName      string      `json:"full_name"`
	DepartmentID  pgtype.UUID `json:"department_id"`
	Email         pgtype.Text `json:"email"`
	Phone         pgtype.Text `json:"phone"`
	Notes         pgtype.Text `json:"notes"`
	RegisteredBy  string      `json:"registered_by"`
	ImportBatchID pgtype.Text `json:"import_batch_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.EmployeeNo,
		arg.FullName,
		arg.DepartmentID,
		arg.Email,
		arg.Phone,
		arg.Notes,
		arg.RegisteredBy,
		arg.ImportBatchID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FullName,
		&i.DepartmentID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Notes,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :one
DELETE FROM departments d
WHERE d.id = $1
  AND NOT EXISTS (SELECT 1 FROM users u WHERE u.department_id = d.id)
RETURNING d.id
`

func (q *Queries) DeleteDepartment(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteDepartment, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, name, created_at FROM departments WHERE id = $1
`

func (q *Queries) GetDepartmentByID(ctx context.Context, id pgtype.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i Department
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getDirectoryLinkBySubject = `-- name: GetDirectoryLinkBySubject :one
SELECT id, user_id, issuer, subject, last_seen_in_directory, sync_state, created_at, updated_at
FROM user_directory_links
WHERE issuer = $1 AND subject = $2
`

type GetDirectoryLinkBySubjectParams struct {
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
}

func (q *Queries) GetDirectoryLinkBySubject(ctx context.Context, arg GetDirectoryLinkBySubjectParams) (UserDirectoryLink, error) {
	row := q.db.QueryRow(ctx, getDirectoryLinkBySubject, arg.Issuer, arg.Subject)
	var i UserDirectoryLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.LastSeenInDirectory,
		&i.SyncState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDirectoryLinkByUserID = `-- name: GetDirectoryLinkByUserID :one
SELECT id, user_id, issuer, subject, last_seen_in_directory, sync_state, created_at, updated_at
FROM user_directory_links
WHERE user_id = $1
`

func (q *Queries) GetDirectoryLinkByUserID(ctx context.Context, userID pgtype.UUID) (UserDirectoryLink, error) {
	row := q.db.QueryRow(ctx, getDirectoryLinkByUserID, userID)
	var i UserDirectoryLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.LastSeenInDirectory,
		&i.SyncState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportBatch = `-- name: GetImportBatch :one
SELECT id, kind, actor, filename, total_rows, created_count, updated_count, skipped_count, created_at
FROM import_batches WHERE id = $1
`

func (q *Queries) GetImportBatch(ctx context.Context, id string) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, getImportBatch, id)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Actor,
		&i.Filename,
		&i.TotalRows,
		&i.CreatedCount,
		&i.UpdatedCount,
		&i.SkippedCount,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateDepartment = `-- name: GetOrCreateDepartment :one
INSERT INTO departments (id, name)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

type GetOrCreateDepartmentParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

// Used by bulk import, which resolves a department name from a CSV column
// without needing a separate "does it exist" round trip.
func (q *Queries) GetOrCreateDepartment(ctx context.Context, arg GetOrCreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, getOrCreateDepartment, arg.ID, arg.Name)
	var i Department
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
FROM users WHERE lower(email) = lower($1) AND status <> 'archived'
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FullName,
		&i.DepartmentID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Notes,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}

const getUserByEmployeeNo = `-- name: GetUserByEmployeeNo :one
SELECT id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
FROM users WHERE lower(employee_no) = lower($1) AND status <> 'archived'
`

// Only among live (non-archived) users, matching the live-uniqueness index:
// an archived duplicate must not shadow a re-hire's new record.
func (q *Queries) GetUserByEmployeeNo(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmployeeNo, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FullName,
		&i.DepartmentID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Notes,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FullName,
		&i.DepartmentID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Notes,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, created_at FROM departments ORDER BY name
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectoryLinks = `-- name: ListDirectoryLinks :many
SELECT id, user_id, issuer, subject, last_seen_in_directory, sync_state, created_at, updated_at
FROM user_directory_links
WHERE issuer = $1
ORDER BY id
`

func (q *Queries) ListDirectoryLinks(ctx context.Context, issuer string) ([]UserDirectoryLink, error) {
	rows, err := q.db.Query(ctx, listDirectoryLinks, issuer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDirectoryLink
	for rows.Next() {
		var i UserDirectoryLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Issuer,
			&i.Subject,
			&i.LastSeenInDirectory,
			&i.SyncState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectoryLinksForSuspension = `-- name: ListDirectoryLinksForSuspension :many
SELECT id, user_id, issuer, subject, last_seen_in_directory, sync_state, created_at, updated_at
FROM user_directory_links
WHERE issuer = $1
  AND sync_state <> 'suspended'
  AND last_seen_in_directory < $2
ORDER BY last_seen_in_directory ASC
`

type ListDirectoryLinksForSuspensionParams struct {
	Issuer              string             `json:"issuer"`
	LastSeenInDirectory pgtype.Timestamptz `json:"last_seen_in_directory"`
}

func (q *Queries) ListDirectoryLinksForSuspension(ctx context.Context, arg ListDirectoryLinksForSuspensionParams) ([]UserDirectoryLink, error) {
	rows, err := q.db.Query(ctx, listDirectoryLinksForSuspension, arg.Issuer, arg.LastSeenInDirectory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDirectoryLink
	for rows.Next() {
		var i UserDirectoryLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Issuer,
			&i.Subject,
			&i.LastSeenInDirectory,
			&i.SyncState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaverEscalations = `-- name: ListLeaverEscalations :many
SELECT l.id AS loan_id,
       l.device_id,
       d.name AS device_name,
       d.asset_tag AS device_asset_tag,
       u.id AS user_id,
       u.full_name AS borrower_name,
       u.employee_no AS borrower_employee_no,
       dept.id AS department_id,
       COALESCE(dept.name, '') AS department_name,
       l.borrowed_at,
       l.due_at,
       u.updated_at AS suspended_at
FROM loans l
JOIN users u ON u.id = l.user_id
JOIN user_directory_links udl ON udl.user_id = u.id
JOIN devices d ON d.id = l.device_id
LEFT JOIN departments dept ON dept.id = u.department_id
WHERE l.status = 'open'
  AND u.status = 'suspended'
ORDER BY l.borrowed_at ASC
`

type ListLeaverEscalationsRow struct {
	LoanID             pgtype.UUID        `json:"loan_id"`
	DeviceID           pgtype.UUID        `json:"device_id"`
	DeviceName         string             `json:"device_name"`
	DeviceAssetTag     string             `json:"device_asset_tag"`
	UserID             pgtype.UUID        `json:"user_id"`
	BorrowerName       string             `json:"borrower_name"`
	BorrowerEmployeeNo string             `json:"borrower_employee_no"`
	DepartmentID       pgtype.UUID        `json:"department_id"`
	DepartmentName     string             `json:"department_name"`
	BorrowedAt         pgtype.Timestamptz `json:"borrowed_at"`
	DueAt              pgtype.Timestamptz `json:"due_at"`
	SuspendedAt        pgtype.Timestamptz `json:"suspended_at"`
}

func (q *Queries) ListLeaverEscalations(ctx context.Context) ([]ListLeaverEscalationsRow, error) {
	rows, err := q.db.Query(ctx, listLeaverEscalations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeaverEscalationsRow
	for rows.Next() {
		var i ListLeaverEscalationsRow
		if err := rows.Scan(
			&i.LoanID,
			&i.DeviceID,
			&i.DeviceName,
			&i.DeviceAssetTag,
			&i.UserID,
			&i.BorrowerName,
			&i.BorrowerEmployeeNo,
			&i.DepartmentID,
			&i.DepartmentName,
			&i.BorrowedAt,
			&i.DueAt,
			&i.SuspendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
FROM users u
WHERE ($1::user_status IS NULL OR u.status = $1)
  AND ($2::uuid IS NULL OR u.department_id = $2)
  AND (
    $3::text IS NULL
    OR u.full_name ILIKE '%' || $3 || '%'
    OR u.employee_no ILIKE '%' || $3 || '%'
  )
  AND (
    $4::boolean IS NULL
    OR ($4::boolean = TRUE AND EXISTS (
      SELECT 1 FROM credentials c
      WHERE c.subject_type = 'user' AND c.subject_id = u.id AND c.status = 'active'
    ))
    OR ($4::boolean = FALSE AND NOT EXISTS (
      SELECT 1 FROM credentials c
      WHERE c.subject_type = 'user' AND c.subject_id = u.id AND c.status = 'active'
    ))
  )
  AND (
    $5::timestamptz IS NULL
    OR u.registered_at < $5
    OR (u.registered_at = $5 AND u.id < $6)
  )
ORDER BY u.registered_at DESC, u.id DESC
LIMIT $7
`

type ListUsersParams struct {
	Status             NullUserStatus     `json:"status"`
	DepartmentID       pgtype.UUID        `json:"department_id"`
	Query              pgtype.Text        `json:"query"`
	HasCredential      pgtype.Bool        `json:"has_credential"`
	CursorRegisteredAt pgtype.Timestamptz `json:"cursor_registered_at"`
	CursorID           pgtype.UUID        `json:"cursor_id"`
	ResultLimit        int32              `json:"result_limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Status,
		arg.DepartmentID,
		arg.Query,
		arg.HasCredential,
		arg.CursorRegisteredAt,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeNo,
			&i.FullName,
			&i.DepartmentID,
			&i.Email,
			&i.Phone,
			&i.Status,
			&i.Notes,
			&i.RegisteredAt,
			&i.RegisteredBy,
			&i.UpdatedAt,
			&i.ImportBatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserEmployeeNo = `-- name: SetUserEmployeeNo :one
UPDATE users
SET employee_no = $2, updated_at = now()
WHERE id = $1 AND status <> 'archived'
RETURNING id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
`

type SetUserEmployeeNoParams struct {
	ID         pgtype.UUID `json:"id"`
	EmployeeNo string      `json:"employee_no"`
}

func (q *Queries) SetUserEmployeeNo(ctx context.Context, arg SetUserEmployeeNoParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserEmployeeNo, arg.ID, arg.EmployeeNo)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FullName,
		&i.DepartmentID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Notes,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}

const streamUsersForExport = `-- name: StreamUsersForExport :many
SELECT
    u.id,
    u.employee_no,
    u.full_name,
    d.name AS department_name,
    u.email,
    u.phone,
    u.status,
    u.notes,
    u.registered_at,
    u.registered_by,
    u.updated_at,
    EXISTS (
      SELECT 1 FROM credentials c
      WHERE c.subject_type = 'user' AND c.subject_id = u.id AND c.status = 'active'
    )::boolean AS has_credential
FROM users u
LEFT JOIN departments d ON u.department_id = d.id
WHERE ($1::user_status IS NULL OR u.status = $1)
  AND ($2::uuid IS NULL OR u.department_id = $2)
  AND (
    $3::text IS NULL
    OR u.full_name ILIKE '%' || $3 || '%'
    OR u.employee_no ILIKE '%' || $3 || '%'
  )
  AND (
    $4::boolean IS NULL
    OR ($4::boolean = TRUE AND EXISTS (
      SELECT 1 FROM credentials c
      WHERE c.subject_type = 'user' AND c.subject_id = u.id AND c.status = 'active'
    ))
    OR ($4::boolean = FALSE AND NOT EXISTS (
      SELECT 1 FROM credentials c
      WHERE c.subject_type = 'user' AND c.subject_id = u.id AND c.status = 'active'
    ))
  )
ORDER BY u.registered_at DESC, u.id DESC
`

type StreamUsersForExportParams struct {
	Status        NullUserStatus `json:"status"`
	DepartmentID  pgtype.UUID    `json:"department_id"`
	Query         pgtype.Text    `json:"query"`
	HasCredential pgtype.Bool    `json:"has_credential"`
}

type StreamUsersForExportRow struct {
	ID             pgtype.UUID        `json:"id"`
	EmployeeNo     string             `json:"employee_no"`
	FullName       string             `json:"full_name"`
	DepartmentName pgtype.Text        `json:"department_name"`
	Email          pgtype.Text        `json:"email"`
	Phone          pgtype.Text        `json:"phone"`
	Status         UserStatus         `json:"status"`
	Notes          pgtype.Text        `json:"notes"`
	RegisteredAt   pgtype.Timestamptz `json:"registered_at"`
	RegisteredBy   string             `json:"registered_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	HasCredential  bool               `json:"has_credential"`
}

func (q *Queries) StreamUsersForExport(ctx context.Context, arg StreamUsersForExportParams) ([]StreamUsersForExportRow, error) {
	rows, err := q.db.Query(ctx, streamUsersForExport,
		arg.Status,
		arg.DepartmentID,
		arg.Query,
		arg.HasCredential,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StreamUsersForExportRow
	for rows.Next() {
		var i StreamUsersForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeNo,
			&i.FullName,
			&i.DepartmentName,
			&i.Email,
			&i.Phone,
			&i.Status,
			&i.Notes,
			&i.RegisteredAt,
			&i.RegisteredBy,
			&i.UpdatedAt,
			&i.HasCredential,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET name = $2
WHERE id = $1
RETURNING id, name, created_at
`

type UpdateDepartmentParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment, arg.ID, arg.Name)
	var i Department
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const updateDirectoryLinkLastSeen = `-- name: UpdateDirectoryLinkLastSeen :one
UPDATE user_directory_links
SET last_seen_in_directory = $2,
    sync_state = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, issuer, subject, last_seen_in_directory, sync_state, created_at, updated_at
`

type UpdateDirectoryLinkLastSeenParams struct {
	ID                  pgtype.UUID        `json:"id"`
	LastSeenInDirectory pgtype.Timestamptz `json:"last_seen_in_directory"`
	SyncState           string             `json:"sync_state"`
}

func (q *Queries) UpdateDirectoryLinkLastSeen(ctx context.Context, arg UpdateDirectoryLinkLastSeenParams) (UserDirectoryLink, error) {
	row := q.db.QueryRow(ctx, updateDirectoryLinkLastSeen, arg.ID, arg.LastSeenInDirectory, arg.SyncState)
	var i UserDirectoryLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.LastSeenInDirectory,
		&i.SyncState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDirectoryLinkSyncState = `-- name: UpdateDirectoryLinkSyncState :one
UPDATE user_directory_links
SET sync_state = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, issuer, subject, last_seen_in_directory, sync_state, created_at, updated_at
`

type UpdateDirectoryLinkSyncStateParams struct {
	ID        pgtype.UUID `json:"id"`
	SyncState string      `json:"sync_state"`
}

func (q *Queries) UpdateDirectoryLinkSyncState(ctx context.Context, arg UpdateDirectoryLinkSyncStateParams) (UserDirectoryLink, error) {
	row := q.db.QueryRow(ctx, updateDirectoryLinkSyncState, arg.ID, arg.SyncState)
	var i UserDirectoryLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.LastSeenInDirectory,
		&i.SyncState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name = $2, department_id = $3, email = $4, phone = $5, notes = $6, updated_at = now()
WHERE id = $1 AND status <> 'archived'
RETURNING id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
`

type UpdateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	FullName     string      `json:"full_name"`
	DepartmentID pgtype.UUID `json:"department_id"`
	Email        pgtype.Text `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.DepartmentID,
		arg.Email,
		arg.Phone,
		arg.Notes,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FullName,
		&i.DepartmentID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Notes,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
`

type UpdateUserStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status UserStatus  `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FullName,
		&i.DepartmentID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Notes,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}

const upsertDirectoryLink = `-- name: UpsertDirectoryLink :one
INSERT INTO user_directory_links (
    id, user_id, issuer, subject, last_seen_in_directory, sync_state
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (issuer, subject) DO UPDATE
SET last_seen_in_directory = EXCLUDED.last_seen_in_directory,
    sync_state = EXCLUDED.sync_state,
    updated_at = now()
RETURNING id, user_id, issuer, subject, last_seen_in_directory, sync_state, created_at, updated_at
`

type UpsertDirectoryLinkParams struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Issuer              string             `json:"issuer"`
	Subject             string             `json:"subject"`
	LastSeenInDirectory pgtype.Timestamptz `json:"last_seen_in_directory"`
	SyncState           string             `json:"sync_state"`
}

func (q *Queries) UpsertDirectoryLink(ctx context.Context, arg UpsertDirectoryLinkParams) (UserDirectoryLink, error) {
	row := q.db.QueryRow(ctx, upsertDirectoryLink,
		arg.ID,
		arg.UserID,
		arg.Issuer,
		arg.Subject,
		arg.LastSeenInDirectory,
		arg.SyncState,
	)
	var i UserDirectoryLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.LastSeenInDirectory,
		&i.SyncState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
