// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package identitystore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO import_batches (id, kind, actor, filename, total_rows, created_count, updated_count, skipped_count, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, kind, actor, filename, total_rows, created_count, updated_count, skipped_count, created_at
`

type CreateImportBatchParams struct {
	ID           string             `json:"id"`
	Kind         string             `json:"kind"`
	Actor        string             `json:"actor"`
	Filename     string             `json:"filename"`
	TotalRows    int32              `json:"total_rows"`
	CreatedCount int32              `json:"created_count"`
	UpdatedCount int32              `json:"updated_count"`
	SkippedCount int32              `json:"skipped_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch,
		arg.ID,
		arg.Kind,
		arg.Actor,
		arg.Filename,
		arg.TotalRows,
		arg.CreatedCount,
		arg.UpdatedCount,
		arg.SkippedCount,
		arg.CreatedAt,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Actor,
		&i.Filename,
		&i.TotalRows,
		&i.CreatedCount,
		&i.UpdatedCount,
		&i.SkippedCount,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, employee_no, full_name, department_id, email, phone, notes, registered_by, import_batch_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
`

type CreateUserParams struct {
	ID            pgtype.UUID `json:"id"`
	EmployeeNo    string      `json:"employee_no"`
	FullName      string      `json:"full_name"`
	DepartmentID  pgtype.UUID `json:"department_id"`
	Email         pgtype.Text `json:"email"`
	Phone         pgtype.Text `json:"phone"`
	Notes         pgtype.Text `json:"notes"`
	RegisteredBy  string      `json:"registered_by"`
	ImportBatchID pgtype.Text `json:"import_batch_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.EmployeeNo,
		arg.FullName,
		arg.DepartmentID,
		arg.Email,
		arg.Phone,
		arg.Notes,
		arg.RegisteredBy,
		arg.ImportBatchID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FullName,
		&i.DepartmentID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Notes,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, name, created_at FROM departments WHERE id = $1
`

func (q *Queries) GetDepartmentByID(ctx context.Context, id pgtype.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i Department
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getImportBatch = `-- name: GetImportBatch :one
SELECT id, kind, actor, filename, total_rows, created_count, updated_count, skipped_count, created_at
FROM import_batches WHERE id = $1
`

func (q *Queries) GetImportBatch(ctx context.Context, id string) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, getImportBatch, id)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Actor,
		&i.Filename,
		&i.TotalRows,
		&i.CreatedCount,
		&i.UpdatedCount,
		&i.SkippedCount,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateDepartment = `-- name: GetOrCreateDepartment :one
INSERT INTO departments (id, name)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

type GetOrCreateDepartmentParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

// Used by bulk import, which resolves a department name from a CSV column
// without needing a separate "does it exist" round trip.
func (q *Queries) GetOrCreateDepartment(ctx context.Context, arg GetOrCreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, getOrCreateDepartment, arg.ID, arg.Name)
	var i Department
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getUserByEmployeeNo = `-- name: GetUserByEmployeeNo :one
SELECT id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
FROM users WHERE lower(employee_no) = lower($1) AND status <> 'archived'
`

// Only among live (non-archived) users, matching the live-uniqueness index:
// an archived duplicate must not shadow a re-hire's new record.
func (q *Queries) GetUserByEmployeeNo(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmployeeNo, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FullName,
		&i.DepartmentID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Notes,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FullName,
		&i.DepartmentID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Notes,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, created_at FROM departments ORDER BY name
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
FROM users u
WHERE ($1::user_status IS NULL OR u.status = $1)
  AND ($2::uuid IS NULL OR u.department_id = $2)
  AND (
    $3::text IS NULL
    OR u.full_name ILIKE '%' || $3 || '%'
    OR u.employee_no ILIKE '%' || $3 || '%'
  )
  AND (
    $4::boolean IS NULL
    OR ($4::boolean = TRUE AND EXISTS (
      SELECT 1 FROM credentials c
      WHERE c.subject_type = 'user' AND c.subject_id = u.id AND c.status = 'active'
    ))
    OR ($4::boolean = FALSE AND NOT EXISTS (
      SELECT 1 FROM credentials c
      WHERE c.subject_type = 'user' AND c.subject_id = u.id AND c.status = 'active'
    ))
  )
  AND (
    $5::timestamptz IS NULL
    OR u.registered_at < $5
    OR (u.registered_at = $5 AND u.id < $6)
  )
ORDER BY u.registered_at DESC, u.id DESC
LIMIT $7
`

type ListUsersParams struct {
	Status             NullUserStatus     `json:"status"`
	DepartmentID       pgtype.UUID        `json:"department_id"`
	Query              pgtype.Text        `json:"query"`
	HasCredential      pgtype.Bool        `json:"has_credential"`
	CursorRegisteredAt pgtype.Timestamptz `json:"cursor_registered_at"`
	CursorID           pgtype.UUID        `json:"cursor_id"`
	ResultLimit        int32              `json:"result_limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Status,
		arg.DepartmentID,
		arg.Query,
		arg.HasCredential,
		arg.CursorRegisteredAt,
		arg.CursorID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeNo,
			&i.FullName,
			&i.DepartmentID,
			&i.Email,
			&i.Phone,
			&i.Status,
			&i.Notes,
			&i.RegisteredAt,
			&i.RegisteredBy,
			&i.UpdatedAt,
			&i.ImportBatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name = $2, department_id = $3, email = $4, phone = $5, notes = $6, updated_at = now()
WHERE id = $1 AND status <> 'archived'
RETURNING id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
`

type UpdateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	FullName     string      `json:"full_name"`
	DepartmentID pgtype.UUID `json:"department_id"`
	Email        pgtype.Text `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.DepartmentID,
		arg.Email,
		arg.Phone,
		arg.Notes,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FullName,
		&i.DepartmentID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Notes,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, employee_no, full_name, department_id, email, phone, status, notes, registered_at, registered_by, updated_at, import_batch_id
`

type UpdateUserStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status UserStatus  `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FullName,
		&i.DepartmentID,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Notes,
		&i.RegisteredAt,
		&i.RegisteredBy,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}
