// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitystore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetDepartmentByID(ctx context.Context, id pgtype.UUID) (Department, error)
	GetImportBatch(ctx context.Context, id string) (ImportBatch, error)
	// Used by bulk import, which resolves a department name from a CSV column
	// without needing a separate "does it exist" round trip.
	GetOrCreateDepartment(ctx context.Context, arg GetOrCreateDepartmentParams) (Department, error)
	// Only among live (non-archived) users, matching the live-uniqueness index:
	// an archived duplicate must not shadow a re-hire's new record.
	GetUserByEmployeeNo(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListDepartments(ctx context.Context) ([]Department, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	StreamUsersForExport(ctx context.Context, arg StreamUsersForExportParams) ([]StreamUsersForExportRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
