// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package idempotencystore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET status_code = $3, response_body = $4, completed_at = now()
WHERE key = $1 AND actor = $2
`

type CompleteIdempotencyKeyParams struct {
	Key          string      `json:"key"`
	Actor        string      `json:"actor"`
	StatusCode   pgtype.Int4 `json:"status_code"`
	ResponseBody []byte      `json:"response_body"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.Key,
		arg.Actor,
		arg.StatusCode,
		arg.ResponseBody,
	)
	return err
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE key = $1 AND actor = $2
`

type DeleteIdempotencyKeyParams struct {
	Key   string `json:"key"`
	Actor string `json:"actor"`
}

// Used to discard the placeholder row when the handler's response turns out
// not to be storable (non-2xx, or over the size cap): leaves no PK
// collision behind, so a genuine retry starts fresh instead of tripping the
// in-flight 409 path forever.
func (q *Queries) DeleteIdempotencyKey(ctx context.Context, arg DeleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, arg.Key, arg.Actor)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, actor, request_hash, status_code, response_body, created_at, completed_at
FROM idempotency_keys WHERE key = $1 AND actor = $2
`

type GetIdempotencyKeyParams struct {
	Key   string `json:"key"`
	Actor string `json:"actor"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Key, arg.Actor)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Actor,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_keys (key, actor, request_hash)
VALUES ($1, $2, $3)
`

type InsertIdempotencyKeyParams struct {
	Key         string `json:"key"`
	Actor       string `json:"actor"`
	RequestHash []byte `json:"request_hash"`
}

// The (key, actor) primary key is the concurrency guard: a second insert
// for a still-in-flight request fails with 23505, which the middleware
// maps to 409 session-conflict — no lock table needed.
func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey, arg.Key, arg.Actor, arg.RequestHash)
	return err
}

const sweepExpiredIdempotencyKeys = `-- name: SweepExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys WHERE created_at < now() - interval '24 hours'
`

func (q *Queries) SweepExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sweepExpiredIdempotencyKeys)
	return err
}
