// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package idempotencystore

import (
	"context"
)

type Querier interface {
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error
	// Used to discard the placeholder row when the handler's response turns out
	// not to be storable (non-2xx, or over the size cap): leaves no PK
	// collision behind, so a genuine retry starts fresh instead of tripping the
	// in-flight 409 path forever.
	DeleteIdempotencyKey(ctx context.Context, arg DeleteIdempotencyKeyParams) error
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	// The (key, actor) primary key is the concurrency guard: a second insert
	// for a still-in-flight request fails with 23505, which the middleware
	// maps to 409 session-conflict — no lock table needed.
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error
	SweepExpiredIdempotencyKeys(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
